### PR TITLE
Fixing issue #804 Improving delete command to list affected children

### LINKED ISSUE #804: Improve Delete command
- Delete should show what other things get deleted as part the action
  - If cascading delete includes storage, should again ask for removal confirmation

### PR DESCRIPTION
**Pull request by mohammedzee1000**
## What is the purpose of this change? What does it change?
This PR works to make delete more informative, listing affected children before deletion.

## Was the change discussed in an issue?
fixes #804

## How to test changes?
Will list as the PR progresses, for now
```
$ odo component delete nodejs-ex-nodejs-npik
 URL  nodejs-ex-nodejs-npik-8080 ,  nodejs-ex-nodejs-npik-8080-nodejs-ex-qxcx-myproject.192.168.42.70.nip.io will be removed
Are you sure you want to delete nodejs-ex-nodejs-npik from nodejs-ex-qxcx? [y/N]: n
Aborting deletion of component: nodejs-ex-nodejs-npik

```

### CODE REVIEW

**Comment by mohammedzee1000** [comment]
Should i list for project as well, seems like a moot point as everything in the project will be deleted, maybe just list apps in this case?

**Comment by mohammedzee1000** [comment]
Output so far : 
```
$ odo project delete myproject
application  nodejs-ex-qxcx  will be deleted

Are you sure you want to delete project myproject? [y/N]: n
 ✗  Aborting deletion of project: myproject

$ odo application delete nodejs-ex-qxcx
Component nodejs-ex-nodejs-npik will be deleted.

 URL  nodejs-ex-nodejs-npik-8080 ,  nodejs-ex-nodejs-npik-8080-nodejs-ex-qxcx-myproject.192.168.42.70.nip.io will be removed
Are you sure you want to delete the application: nodejs-ex-qxcx from project: myproject? [y/N]: n
Aborting deletion of application: nodejs-ex-qxcx

$ odo component delete nodejs-ex-nodejs-npik
 URL  nodejs-ex-nodejs-npik-8080 ,  nodejs-ex-nodejs-npik-8080-nodejs-ex-qxcx-myproject.192.168.42.70.nip.io will be removed

Are you sure you want to delete nodejs-ex-nodejs-npik from nodejs-ex-qxcx? [y/N]: n
Aborting deletion of component: nodejs-ex-nodejs-npik

```

**Comment by mohammedzee1000** [comment]
Output Now:

```
$ odo project delete myproject  
This project contains the following applications, which will be deleted

 Application  nodejs-ex-irze

  This application has following components that will be deleted

  component named  nodejs-ex-nodejs-fsfx

    The component has following urls that will be deleted with component

     URL named  nodejs-ex-nodejs-fsfx-8080  with value  nodejs-ex-nodejs-fsfx-8080-nodejs-ex-irze-myproject.192.168.42.216.nip.io

 Application  test

Are you sure you want to delete project myproject? [y/N]: n
 ✗  Aborting deletion of project: myproject

$ odo app delete nodejs-ex-irze
This application has following components that will be deleted

 component named  nodejs-ex-nodejs-fsfx

  The component has following urls that will be deleted with component

   URL named  nodejs-ex-nodejs-fsfx-8080  with value  nodejs-ex-nodejs-fsfx-8080-nodejs-ex-irze-myproject.192.168.42.216.nip.io

Are you sure you want to delete the application: nodejs-ex-irze from project: myproject? [y/N]: n
 ✗  Aborting deletion of application: nodejs-ex-irze

$ odo component delete nodejs-ex-nodejs-fsfx
The component has following urls that will be deleted with component

 URL named  nodejs-ex-nodejs-fsfx-8080  with value  nodejs-ex-nodejs-fsfx-8080-nodejs-ex-irze-myproject.192.168.42.216.nip.io

Are you sure you want to delete nodejs-ex-nodejs-fsfx from nodejs-ex-irze? [y/N]: n
 ✗  Aborting deletion of component: nodejs-ex-nodejs-fsfx


```

@anmolbabu @kadel PTAL

File: pkg/odo/cli/project/project.go [hunk 1]
```diff
@@ -66,3 +71,57 @@ func AddProjectFlag(cmd *cobra.Command) {
 	cmd.Flags().String(genericclioptions.ProjectFlagName, "", "Project, defaults to active project")
 	completion.RegisterCommandFlagHandler(cmd, "project", completion.ProjectNameCompletionHandler)
 }
+
+// printDeleteProjectInfo prints objects affected by project deletion
+func printDeleteProjectInfo(client *occlient.Client, projectName string) error {
```
Comment (golangcibot) [inline pkg/odo/cli/project/project.go]: `printDeleteProjectInfo` is unused (from `deadcode`)

Comment (mohammedzee1000) [reply pkg/odo/cli/project/project.go]: Sorted

**Comment by kadel** [comment]
@mohammedzee1000 is this still in progress?

**Comment by mohammedzee1000** [comment]
@kadel im pushing the tests in a few minutes, otherwise its done

File: pkg/odo/cli/application/application.go [hunk 2]
```diff
@@ -77,21 +81,48 @@ func printDeleteAppInfo(client *occlient.Client, appName string, projectName str
...
+			if err != nil {
+				return errors.Wrap(err, "unable to get component description")
+			}
+			log.Info(" component named ", currentComponent.Name)
+
+			if len(componentDesc.Spec.URL) != 0 {
+				log.Info("  The component has following routes, which will be removed")
+				ul, err := url.List(client, componentDesc.Name, appName)
+				if err != nil {
+					errors.Wrap(err, "Could not get url list")
```
Comment (golangcibot) [inline pkg/odo/cli/application/application.go]: Error return value of `errors.Wrap` is not checked (from `errcheck`)

File: pkg/odo/cli/component/component.go [hunk 3]
```diff
@@ -86,3 +92,33 @@ func AddComponentFlag(cmd *cobra.Command) {
...
+	componentDesc, err := component.GetComponent(client, componentName, appName, projectName)
+	if err != nil {
+		return errors.Wrap(err, "unable to get component description")
+	}
+
+	if len(componentDesc.Spec.URL) != 0 {
+		log.Info("This component has following urls that will be deleted with component")
+		ul, err := url.List(client, componentDesc.Name, appName)
+		if err != nil {
+			errors.Wrap(err, "Could not get url list")
```
Comment (golangcibot) [inline pkg/odo/cli/component/component.go]: Error return value of `errors.Wrap` is not checked (from `errcheck`)

File: pkg/odo/cli/project/project.go [hunk 4]
```diff
@@ -66,3 +75,71 @@ func AddProjectFlag(cmd *cobra.Command) {
...
+					componentDesc, err := component.GetComponent(client, currentComponent.Name, app.Name, app.Project)
+					if err != nil {
+						return errors.Wrap(err, "unable to get component description")
+					}
+					log.Info("  component named ", componentDesc.Name)
+
+					if len(componentDesc.Spec.URL) != 0 {
+						ul, err := url.List(client, componentDesc.Name, app.Name)
+						if err != nil {
+							errors.Wrap(err, "Could not get url list")
```
Comment (golangcibot) [inline pkg/odo/cli/project/project.go]: Error return value of `errors.Wrap` is not checked (from `errcheck`)

File: pkg/odo/cli/application/application.go (hunk 2 above)
Comment (mohammedzee1000) [reply pkg/odo/cli/application/application.go]: Addressed

File: pkg/odo/cli/component/component.go (hunk 3 above)
Comment (mohammedzee1000) [reply pkg/odo/cli/component/component.go]: Addressed

File: pkg/odo/cli/project/project.go (hunk 4 above)
Comment (mohammedzee1000) [reply pkg/odo/cli/project/project.go]: Addressed

**Comment by mohammedzee1000** [comment]
> I'm unable to delete app if my cluster doesn't have ServiceCatalog deployed
> 
> ```
> ▶ odo app delete
> This application has following components that will be deleted
> 
>  component named  nodejs-ex-nodejs-fcop
> 
>  ✗  the server could not find the requested resource (get serviceinstances.servicecatalog.k8s.io)
> ```

This should be fixed now

```
$ odo app delete
This application has following components that will be deleted

 component named  odo-nodejs-orbh

  The component has following routes, which will be removed

  This component has following urls that will be deleted with component

   URL named  testu  with value  testu-odo-sihe-testp.192.168.42.30.nip.io

No services / could not get services

? Are you sure you want to delete the application: odo-sihe from project: testp No
 ✗  Aborting deletion of application: odo-sihe

$ odo app delete -v 4

...
No services / could not get services

I0227 20:09:48.377844   22660 application.go:119] unable to list services: unable to list ServiceInstances: serviceinstances.servicecatalog.k8s.io is forbidden: User "test" cannot list serviceinstances.servicecatalog.k8s.io in the namespace "testp": no RBAC policy matched
? Are you sure you want to delete the application: odo-sihe from project: testp No
...
```

**Comment by mohammedzee1000** [comment]
There seems to be a consitent failure on link e2e tests on travis CI. But this PR code does does touch the link e2e test

**Comment by mohammedzee1000** [comment]
Strange i have not touched the link e2e tests. How are they failing here

**Comment by kadel** [comment]
> Strange i have not touched the link e2e tests. How are they failing here

PR that modifies `odo describe` output was recently merged, if you rebase your PR with current master it should fix the issue

**Comment by mohammedzee1000** [comment]
> > Strange i have not touched the link e2e tests. How are they failing here
> 
> PR that modifies `odo describe` output was recently merged, if you rebase your PR with current master it should fix the issue

It is already rebased

File: pkg/odo/cli/application/delete.go [hunk 5]
```diff
@@ -62,7 +63,7 @@ func (o *DeleteOptions) Run() (err error) {
 		}
 		log.Infof("Deleted application: %s from project: %v", o.appName, o.Project)
 	} else {
-		log.Infof("Aborting deletion of application: %v", o.appName)
+		return fmt.Errorf("Aborting deletion of application: %v", o.appName)
```
Comment (girishramnani) [inline pkg/odo/cli/application/delete.go]: shouldn't this be info? user intervention should be an error?

File: tests/e2e/e2e_test.go [hunk 6]
```diff
@@ -725,7 +726,7 @@ var _ = Describe("odoe2e", func() {
 		})
 
 		It("should delete the deployed image-specific component", func() {
-			runCmdShouldPass("odo delete testversioncmp")
+			runCmdShouldPass("odo delete testversioncmp -f")
```
Comment (girishramnani) [inline tests/e2e/e2e_test.go]: was this working before? what I mean is without the `--force` flag this command would have just blocked on the user confirmation. so even then the test was passing?

Comment (mohammedzee1000) [reply tests/e2e/e2e_test.go]: Apparently so, but it no longer works now. Dont know exactly why it was working before

File: pkg/odo/cli/application/delete.go (hunk 5 above)
Comment (mohammedzee1000) [reply pkg/odo/cli/application/delete.go]: Updated
