### PR TITLE
Fix error handling when trying to delete remote resources not present in Devfile

### LINKED ISSUE #6475: PodMetrics is not a deletable resource and needs to handled properly by odo dev
PodMetrics does not allow the DELETE method, this has been handled already but for some reason it still fails, it needs some investigation.
```sh
Expected
      <string>:   __
       /  \__     Developing using the "xpczcj" Devfile
       \__/  \    Namespace: cmd-logs-test189tbj
       /  \__/    odo version: v3.5.0
       \__/
      
      â†ª Deploying to the cluster in developer mode
       â€¢  Waiting for Kubernetes resources  ...
       â€¢  Creating resource Pod/myapp-inner  ...
      
 âœ“  Creating resource Pod/myapp-inner 
       âš   Pod is Pending
       âœ“  Pod is Running
       â€¢  Deleting resources not present in the Devfile: PodMetrics/myapp-inner  ...
      
 âœ“  Deleting resources not present in the Devfile: PodMetrics/myapp-inner [1s]
      Error occurred on Push - watch command was unable to push component: unable to delete remote resources: unable to delete resource: PodMetrics/myapp-inner: the server does not allow this method on the requested resource
      
       â€¢  Deleting resources not present in the Devfile: PodMetrics/myapp-inner  ...
      
 âœ“  Deleting resources not present in the Devfile: PodMetrics/myapp-inner [1s]
      Error occurred on Push - watch command was unable to push component: unable to delete remote resources: unable to delete resource: PodMetrics/myapp-inner: the server does not allow this method on the requested resource
  ```

_Originally posted by @valaparthvi in https://github.com/redhat-developer/odo/issues/6470#issuecomment-1373809523_

/assign valaparthvi

### PR DESCRIPTION
**Pull request by rm3l**
**What type of PR is this:**

/kind bug

**What does this PR do / why we need it:**
Stumbled upon this issue recently, and found a mistake in the `if` condition used to skip non-deletable resources (like `PodMetrics`). 

We had this previously, which would actually never match:
```go
if !kerrors.IsNotFound(err) || !kerrors.IsMethodNotSupported(err) {
```

After adding some unit tests, I also noticed that the way any error is detected might lead to a race condition: multiple Goroutines are trying to assign a shared error variable, and we are using that to determine the return value.
This is solved by using [`errgroup`](https://pkg.go.dev/golang.org/x/sync/errgroup) instead, which looks more appropriate to simplify goroutine error handling.

**Which issue(s) this PR fixes:**
Fixes #6475 

**PR acceptance criteria:**

- [x] Unit test 

- [ ] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**

### CODE REVIEW

File: pkg/devfile/adapters/kubernetes/component/adapter.go [hunk 1]
```diff
@@ -693,40 +692,36 @@ func (a Adapter) deleteRemoteResources(objectsToRemove []unstructured.Unstructur
 		resources = append(resources, fmt.Sprintf("%s/%s", u.GetKind(), u.GetName()))
 	}
 
-	var err error
-	spinner := log.Spinnerf("Deleting resources not present in the Devfile: %s", strings.Join(resources, ", "))
```
Comment (valaparthvi) [inline pkg/devfile/adapters/kubernetes/component/adapter.go:697]: I assume we're sacrificing the spinner message to be able to use errgroup and make sure we don't run into race conditions, yes?

**Review by valaparthvi — APPROVED** [review]

File: pkg/devfile/adapters/kubernetes/component/adapter.go (hunk 1 above)
Comment (rm3l) [reply pkg/devfile/adapters/kubernetes/component/adapter.go:697]: We could have used `errgroup` with the spinner, as the spinner is started outside of the group and its status is updated after all goroutines have exited.
The problem is that `odo` will continuously try to delete such resources that it couldn't delete (and display the spinner over and over again), which adds too much clutter to the terminal, IMO.
Also, I found the final status of the spinner to be a bit misleading by displaying `✓`, because it ignored `PodMetrics` resources (in the example below), but it didn't delete them actually as it will try again to delete them :-).

<details>
<summary>Sample output with the spinner</summary>

```
$ odo dev                                                                                                                                                                                                           
  __                                                                                                                                                                                                                
 /  \__     Developing using the "my-node-app" Devfile                                                                                                                                                              
 \__/  \    Namespace: default                                                                                                                                                                                      
 /  \__/    odo version: v3.8.0                                                                                                                                                                                     
 \__/                                                                                                                                                                                                               
                                                                                                                                                                                                                    
↪ Running on the cluster in Dev mode                                                                                                                                                                                
 •  Waiting for Kubernetes resources  ...                                                                                                                                                                           
 ✓  Creating resource Pod/k8s-deploybydefault-true-and-not-referenced                                                                                                                                               
 ✓  Creating resource Pod/k8s-deploybydefault-false-and-not-referenced                                                                                                                                              
 ✓  Creating resource Pod/ocp-deploybydefault-true-and-not-referenced                                                                                                                                               
 ✓  Creating resource Pod/k8s-deploybydefault-not-set-and-not-referenced                                                                                                                                            
 ✓  Creating resource Pod/ocp-deploybydefault-false-and-not-referenced                                                                                                                                              
 ✓  Creating resource Pod/ocp-deploybydefault-not-set-and-not-referenced                                                                                                                                            
 ⚠  Pod is Pending                                                                                                                                                                                                  
 ✓  Pod is Running                                                                                                                                                                                                  
 ✓  Deleting resources not present in the Devfile: PodMetrics/k8s-deploybydefault-false-and-not-referenced, PodMetrics/k8s-deploybydefault-not-set-and-not-referenced, PodMetrics/k8s-deploybydefault-true-and-not-referenced, PodMetrics/ocp-deploybydefault-false-and-not-referenced, PodMetrics/ocp-deploybydefault-not-set-and-not-referenced, PodMetrics/ocp-deploybydefault-true-and-not-referenced [186ms]
 ✓  Syncing files into the container [101ms]
 ✓  Building your application in container (command: build) [3s]
 •  Executing the application (command: start-app)  ...
 -  Forwarding from 127.0.0.1:20001 -> 3000


↪ Dev mode
 Status:
 Watching for changes in the current directory /home/asoro/work/tmp/5694-implement-autobuild-and-deploybydefault

 Keyboard Commands:
[Ctrl+c] - Exit and delete resources from the cluster 
     [p] - Manually apply local changes to the application on the cluster
 ✓  Deleting resources not present in the Devfile: PodMetrics/k8s-deploybydefault-false-and-not-referenced, PodMetrics/k8s-deploybydefault-not-set-and-not-referenced, PodMetrics/k8s-deploybydefault-true-and-not-referenced, PodMetrics/ocp-deploybydefault-false-and-not-referenced, PodMetrics/ocp-deploybydefault-not-set-and-not-referenced, PodMetrics/ocp-deploybydefault-true-and-not-referenced [215ms]
 ✓  Deleting resources not present in the Devfile: PodMetrics/k8s-deploybydefault-false-and-not-referenced, PodMetrics/k8s-deploybydefault-not-set-and-not-referenced, PodMetrics/k8s-deploybydefault-true-and-not-referenced, PodMetrics/ocp-deploybydefault-false-and-not-referenced, PodMetrics/ocp-deploybydefault-not-set-and-not-referenced, PodMetrics/ocp-deploybydefault-true-and-not-referenced [839ms]
 ✓  Deleting resources not present in the Devfile: PodMetrics/k8s-deploybydefault-false-and-not-referenced, PodMetrics/k8s-deploybydefault-not-set-and-not-referenced, PodMetrics/k8s-deploybydefault-true-and-not-referenced, PodMetrics/ocp-deploybydefault-false-and-not-referenced, PodMetrics/ocp-deploybydefault-not-set-and-not-referenced, PodMetrics/ocp-deploybydefault-true-and-not-referenced [860ms]
 ✓  Deleting resources not present in the Devfile: PodMetrics/k8s-deploybydefault-false-and-not-referenced, PodMetrics/k8s-deploybydefault-not-set-and-not-referenced, PodMetrics/k8s-deploybydefault-true-and-not-r
eferenced, PodMetrics/ocp-deploybydefault-false-and-not-referenced, PodMetrics/ocp-deploybydefault-not-set-and-not-referenced, PodMetrics/ocp-deploybydefault-true-and-not-referenced [853ms]
 ✓  Deleting resources not present in the Devfile: PodMetrics/k8s-deploybydefault-false-and-not-referenced, PodMetrics/k8s-deploybydefault-not-set-and-not-referenced, PodMetrics/k8s-deploybydefault-true-and-not-r
eferenced, PodMetrics/ocp-deploybydefault-false-and-not-referenced, PodMetrics/ocp-deploybydefault-not-set-and-not-referenced, PodMetrics/ocp-deploybydefault-true-and-not-referenced [849ms]
 ✓  Deleting resources not present in the Devfile: PodMetrics/k8s-deploybydefault-false-and-not-referenced, PodMetrics/k8s-deploybydefault-not-set-and-not-referenced, PodMetrics/k8s-deploybydefault-true-and-not-r
eferenced, PodMetrics/ocp-deploybydefault-false-and-not-referenced, PodMetrics/ocp-deploybydefault-not-set-and-not-referenced, PodMetrics/ocp-deploybydefault-true-and-not-referenced [855ms]

...
```

</details>

This is why I thought it would make sense to `klog` this instead.

**Comment by rm3l** [comment]
Flaky tests.

/override windows-integration-test/Windows-test
