### PR TITLE
Fix #1254: don't ignore errors when retrieving service classes and plans

### LINKED ISSUE #1254: odo service create panic when there is no Service Catalog available on cluster
[kind/bug]

## What versions of software are you using?
- Operating System:
- Output of `odo version`: current master -  v0.0.18 (c25f00ef)

## Actual behavior

1. Connect to the cluster that does't have Service Catalog deployed.
2. `odo service create`

```
▶ odo service create
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1ccd6ff]

goroutine 1 [running]:
github.com/redhat-developer/odo/pkg/service.NewServicePlan(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/tkral/Code/goenv/odo/src/github.com/redhat-developer/odo/pkg/service/service.go:353 +0xef
github.com/redhat-developer/odo/pkg/odo/cli/service/ui.enterServicePropertiesInteractively(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/tkral/Code/goenv/odo/src/github.com/redhat-developer/odo/pkg/odo/cli/service/ui/ui.go:259 +0x92
github.com/redhat-developer/odo/pkg/odo/cli/service/ui.EnterServicePropertiesInteractively(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/tkral/Code/goenv/odo/src/github.com/redhat-developer/odo/pkg/odo/cli/service/ui/ui.go:253 +0x76
github.com/redhat-developer/odo/pkg/odo/cli/service.(*ServiceCreateOptions).Complete(0xc000bba6c0, 0x2485701, 0x6, 0xc000660900, 0x376fc58, 0x0, 0x0, 0xc000b6dc40, 0x0)
	/Users/tkral/Code/goenv/odo/src/github.com/redhat-developer/odo/pkg/odo/cli/service/create.go:90 +0x434
github.com/redhat-developer/odo/pkg/odo/cli/service.NewCmdServiceCreate.func1(0xc000660900, 0x376fc58, 0x0, 0x0)
	/Users/tkral/Code/goenv/odo/src/github.com/redhat-developer/odo/pkg/odo/cli/service/create.go:188 +0x6d
github.com/redhat-developer/odo/vendor/github.com/spf13/cobra.(*Command).execute(0xc000660900, 0x376fc58, 0x0, 0x0, 0xc000660900, 0x376fc58)
	/Users/tkral/Code/goenv/odo/src/github.com/redhat-developer/odo/vendor/github.com/spf13/cobra/command.go:702 +0x2d3
github.com/redhat-developer/odo/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000678000, 0x8, 0xc000000300, 0x20b1a82)
	/Users/tkral/Code/goenv/odo/src/github.com/redhat-developer/odo/vendor/github.com/spf13/cobra/command.go:783 +0x2dc
github.com/redhat-developer/odo/vendor/github.com/spf13/cobra.(*Command).Execute(0xc000678000, 0x2585f38, 0xc000706600)
	/Users/tkral/Code/goenv/odo/src/github.com/redhat-developer/odo/vendor/github.com/spf13/cobra/command.go:736 +0x2b
main.main()
	/Users/tkral/Code/goenv/odo/src/github.com/redhat-developer/odo/cmd/odo/odo.go:64 +0x350
```

## Expected behavior

odo should show error message explaining that cluster that user is connected to doesn't support Service Catalog.

### PR DESCRIPTION
**Pull request by metacosm**
## Was the change discussed in an issue?
fixes #1254 

## How to test changes?
`odo service create` while connected to a non service catalog enabled cluster.

### CODE REVIEW

File: pkg/occlient/occlient.go [hunk 1]
```diff
@@ -2233,7 +2233,7 @@ func (c *Client) GetServiceClassesByCategory() (categories map[string][]scv1beta
 	categories = make(map[string][]scv1beta1.ClusterServiceClass)
 	classes, err := c.GetClusterServiceClasses()
 	if err != nil {
-		return nil, errors.Wrap(err, "unable to get cluster service classes")
+		return nil, err
```
Comment (anmolbabu) [inline pkg/occlient/occlient.go]: why is this required?

Comment (anmolbabu) [reply pkg/occlient/occlient.go]: I mean wrap also returns error just that the err is wrapped with a custom msg

File: pkg/odo/cli/service/create.go [hunk 2]
```diff
@@ -68,10 +69,16 @@ func (o *ServiceCreateOptions) Complete(name string, cmd *cobra.Command, args []
 
 	var class scv1beta1.ClusterServiceClass
 	if o.interactive {
-		classesByCategory, _ := client.GetServiceClassesByCategory()
+		classesByCategory, err := client.GetServiceClassesByCategory()
+		if err != nil {
+			return fmt.Errorf("unable to retrieve service classes: %v", err)
```
Comment (anmolbabu) [inline pkg/odo/cli/service/create.go]: can we use errors.Wrapf here?

File: pkg/odo/cli/service/create.go [hunk 3]
```diff
@@ -68,10 +69,16 @@ func (o *ServiceCreateOptions) Complete(name string, cmd *cobra.Command, args []
...
+		}
 		class, o.serviceType = ui.SelectClassInteractively(classesByCategory)
 
-		plans, _ := client.GetMatchingPlans(class)
+		plans, err := client.GetMatchingPlans(class)
+		if err != nil {
+			return fmt.Errorf("couldn't retrieve plans for class %s: %v", class.GetExternalName(), err)
```
Comment (anmolbabu) [inline pkg/odo/cli/service/create.go]: same as above

File: pkg/occlient/occlient.go (hunk 1 above)
Comment (metacosm) [reply pkg/occlient/occlient.go]: The problem is that LogErrorAndExit will unwrap all causes loses all context. We might need to revisit this function so that it's more useful.

Comment (anmolbabu) [reply pkg/occlient/occlient.go]: ok

**Comment by amitkrout** [comment]
@metacosm Thanks for the pr, However i find some issue while i run manual test.

Test environment i used: 
```
macOS, minishift v1.30.0
```
Steps i followed to hit the issue: 

1. minishift start
```
$ MINISHIFT_ENABLE_EXPERIMENTAL=y ./minishift start --extra-clusterup-flags "--enable=*,service-catalog"
```
2. odo login (Got binary from running "make bin" on master branch)
```
$ ./odo login 
[...]
Using project "myproject".
```
3. odo service create
```
$ ./odo service create
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1c742d3]

goroutine 1 [running]:
github.com/redhat-developer/odo/pkg/service.NewServicePlan(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/amit/go/src/github.com/redhat-developer/odo/pkg/service/service.go:364 +0xc3
github.com/redhat-developer/odo/pkg/odo/cli/service/ui.enterServicePropertiesInteractively(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/amit/go/src/github.com/redhat-developer/odo/pkg/odo/cli/service/ui/ui.go:240 +0x92
github.com/redhat-developer/odo/pkg/odo/cli/service/ui.EnterServicePropertiesInteractively(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/amit/go/src/github.com/redhat-developer/odo/pkg/odo/cli/service/ui/ui.go:234 +0x76
github.com/redhat-developer/odo/pkg/odo/cli/service.(*ServiceCreateOptions).Complete(0xc4207c5f20, 0x247b099, 0x6, 0xc420868900, 0x32b1bd8, 0x0, 0x0, 0xc420a25c30, 0x0)
	/Users/amit/go/src/github.com/redhat-developer/odo/pkg/odo/cli/service/create.go:98 +0x5c0
github.com/redhat-developer/odo/pkg/odo/cli/service.NewCmdServiceCreate.func1(0xc420868900, 0x32b1bd8, 0x0, 0x0)
	/Users/amit/go/src/github.com/redhat-developer/odo/pkg/odo/cli/service/create.go:196 +0x6d
github.com/redhat-developer/odo/vendor/github.com/spf13/cobra.(*Command).execute(0xc420868900, 0x32b1bd8, 0x0, 0x0, 0xc420868900, 0x32b1bd8)
	/Users/amit/go/src/github.com/redhat-developer/odo/vendor/github.com/spf13/cobra/command.go:702 +0x2c6
github.com/redhat-developer/odo/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4208c0240, 0xc420a25ea0, 0x8, 0x2091514)
	/Users/amit/go/src/github.com/redhat-developer/odo/vendor/github.com/spf13/cobra/command.go:783 +0x2e4
github.com/redhat-developer/odo/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4208c0240, 0x257b4c0, 0xc4200aea80)
	/Users/amit/go/src/github.com/redhat-developer/odo/vendor/github.com/spf13/cobra/command.go:736 +0x2b
main.main()
	/Users/amit/go/src/github.com/redhat-developer/odo/cmd/odo/odo.go:64 +0x382
```

However user scenario works fine for ```odo service create while connected to a non service catalog enabled cluster```. Steps

1. minishift start
2. odo login
3. odo service create
```
$ ./odo service create
 ✗  unable to retrieve service classes: unable to list cluster service classes: clusterserviceclasses.servicecatalog.k8s.io is forbidden: User "developer" cannot list clusterserviceclasses.servicecatalog.k8s.io at the cluster scope: no RBAC policy matched
```

@metacosm Would you please confirm if the issue is reproducible from your end (@mik-dass Could not reproduce it) and also would be great if you add these scenario in integration test in a separate pr.

**Comment by metacosm** [comment]
@amitkrout how long have you waited after you started minishift with the service catalog to run the tests? Service catalog is notoriously tricky when it comes to timing and it needs quite a bit of time to be properly ready to serve. I use a cluster where service catalog is set up and running and never saw this issue.

**Comment by amitkrout** [comment]
> how long have you waited after you started minishift with the service catalog to run the tests? 

Ahh...this could be the issue. Let me try it with some time gap then

**Comment by amitkrout** [comment]
> Service catalog is notoriously tricky when it comes to timing and it needs quite a bit of time to be properly ready to serve. I use a cluster where service catalog is set up and running and never saw this issue. 

No luck even after a long gap of 1 hr :( .Any thoughts 
@mik-dass is not able to reproduce it because he follows same the steps that you following.
