### PR TITLE
Removing bash for building images using podman/docker

### LINKED ISSUE #5588: `odo deploy` and `odo build-images` is not working on windows
It is not possible to build images on Windows

/kind bug
/priority high
/area windows
/area deploy

```
-  Building image locally  ...
/bin/bash: line 1: podman: command not found
 X  Building image locally [376ms]
 X  error running podman command: exit status 127
```

Problem is that odo is trying to execute it inside bash
https://github.com/redhat-developer/odo/blob/7618e8f3e4385bdca620e934c0b27d8fcc878099/pkg/devfile/image/docker_compatible.go#L39

### PR DESCRIPTION
**Pull request by mohammedzee1000**
Signed-off-by: Mohammed Zeeshan Ahmed <mohammed.zee1000@gmail.com>

**What type of PR is this:**
/kind bug


**What does this PR do / why we need it:**

**Which issue(s) this PR fixes:**
<!-- 
Specifying the issue will automatically close it when this PR is merged
-->

Fixes #5588 

**PR acceptance criteria:**

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**
On windows:
initialize component with a deploy devfile like for eg `tests/examples/source/devfiles/nodejs/devfile-deploy.yaml`
You may want to change image name for full deploy expirence so push can happen

```
C:\Users\Mohammed Zeeshan\work\odo\testing>"C:\Users\Mohammed Zeeshan\Downloads\odo.exe" deploy
  __
 /  \__     Deploying the application using nodejs-prj1-api-abhz Devfile
 \__/  \    Namespace: default
 /  \__/    odo version: v2.5.0
 \__/
 
- Building & Pushing Container: docker.io/mohammedzee1000/myimage
 -  Building image locally  ...
failed to get console mode for stdin: The handle is invalid.
[+] Building 1.4s (10/10) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                                                                             0.0s
 => => transferring dockerfile: 32B                                                                                                                                                                                              0.0s
 => [internal] load .dockerignore                                                                                                                                                                                                0.1s
 => => transferring context: 2B                                                                                                                                                                                                  0.0s
 => [internal] load metadata for quay.io/phmartin/node:17                                                                                                                                                                        0.9s
 => [1/5] FROM quay.io/phmartin/node:17@sha256:204a4603f9eac642121286b1dd8cd629809461929af5700073024eaef9fe4931                                                                                                                  0.0s
 => [internal] load build context                                                                                                                                                                                                0.1s
 => => transferring context: 405B                                                                                                                                                                                                0.0s
 => CACHED [2/5] WORKDIR /usr/src/app                                                                                                                                                                                            0.0s
 => CACHED [3/5] COPY package*.json ./                                                                                                                                                                                           0.0s
 => CACHED [4/5] RUN npm install                                                                                                                                                                                                 0.0s
 => CACHED [5/5] COPY . .                                                                                                                                                                                                        0.0s
 => exporting to image                                                                                                                                                                                                           0.2s
 => => exporting layers                                                                                                                                                                                                          0.0s
 => => writing image sha256:75c845a99439e2667fed274c9a8a08372455c7f54cc325046642f8ffc2e9e0b2                                                                                                                                     0.0s
 => => naming to docker.io/mohammedzee1000/myimage                                                                                                                                                                               0.0s
 
Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
 V  Building image locally [2s]
 -  Pushing image to container registry  ...
Using default tag: latest
The push refers to repository [docker.io/mohammedzee1000/myimage]
a46da801cfaa: Layer already exists
6cba780e5482: Layer already exists
2c14ea7cd532: Layer already exists
1b9c941aeeb4: Layer already exists
013fc0144002: Layer already exists
5723726afdfd: Layer already exists
02784cd376a2: Layer already exists
3525f11eba01: Layer already exists
8f56c3340629: Pushed
ba6e5ff31f23: Layer already exists
9f9f651e9303: Layer already exists
0b3c02b5d746: Layer already exists
62a747bf1719: Layer already exists
latest: digest: sha256:c82dc22348c465d7c3363e8ba0d5a845c8c4082903d8812fb3bb1a67cbcba5d3 size: 3048
 V  Pushing image to container registry [6m]
 
- Deploying Kubernetes Component: my-component
 V  Searching resource in cluster
 V  Creating kind Deployment [12ms]
 
Your Devfile has been successfully deployed
```

### CODE REVIEW

File: pkg/devfile/image/docker_compatible.go [hunk 1]
```diff
@@ -34,9 +35,22 @@ func (o *DockerCompatibleBackend) Build(image *devfile.ImageComponent, devfilePa
...
+	}
+
+	err = os.Setenv("PROJECT_SOURCE", devfilePath)
+	if err != nil {
+		return err
+	}
 
-	cmd := exec.Command("bash", "-c", shell)
+	//get command to run, expand the environment variables and convert command to array
+	shellCmd, err := util.ParseCommandLine(os.ExpandEnv(getShellCommand(o.name, image, devfilePath)))
```
Comment (kadel) [inline pkg/devfile/image/docker_compatible.go:49]: could we modify `getShellCommand` to return `[]string` so we can skip `ParseCommandLine`:

**Comment by mohammedzee1000** [comment]
updated, ptal

File: pkg/devfile/image/docker_compatible.go [hunk 2]
```diff
@@ -57,21 +69,29 @@ func (o *DockerCompatibleBackend) Build(image *devfile.ImageComponent, devfilePa
...
+		dockerfile,
+		buildpath,
+	}
 	if len(args) > 0 {
-		shell = shell + " " + strings.Join(args, " ")
+		shellCmd = append(shellCmd, args...)
 	}
-	klog.V(4).Infof("Running command: %s", shell)
-	return shell
+	klog.V(4).Infof("Running command: %v", shellCmd)
```
Comment (dharmit) [inline pkg/devfile/image/docker_compatible.go:93]: IMO, this `klog` would make more sense to put between these two statements:
```go
shellCmd := getShellCommand(o.name, image, devfilePath)
for i := 0; i < len(shellCmd); i++ {
```

File: pkg/devfile/image/docker_compatible.go [hunk 3]
```diff
@@ -57,21 +69,29 @@ func (o *DockerCompatibleBackend) Build(image *devfile.ImageComponent, devfilePa
 	return nil
 }
 
-func getShellCommand(cmdName string, image *devfile.ImageComponent, devfilePath string) string {
+func getShellCommand(cmdName string, image *devfile.ImageComponent, devfilePath string) []string {
```
Comment (dharmit) [inline pkg/devfile/image/docker_compatible.go:72]: A comment that briefly explains what `getShellCommand` function does would be helpful. I understand that I'm requesting comment for an internal function.

File: pkg/devfile/image/docker_compatible.go [hunk 4]
```diff
@@ -34,9 +34,21 @@ func (o *DockerCompatibleBackend) Build(image *devfile.ImageComponent, devfilePa
...
+	err = os.Setenv("PROJECT_SOURCE", devfilePath)
+	if err != nil {
+		return err
+	}
 
-	cmd := exec.Command("bash", "-c", shell)
+	shellCmd := getShellCommand(o.name, image, devfilePath)
+	for i := 0; i < len(shellCmd); i++ {
+		shellCmd[i] = os.ExpandEnv(shellCmd[i])
+	}
```
Comment (dharmit) [inline pkg/devfile/image/docker_compatible.go:50]: I think below would be more readable, WDYT?:
```go
for i, cmd := range shellCmd {
	shellCmd[i] = os.ExpandEnv(cmd)
}
```

**Review by dharmit — CHANGES_REQUESTED** [review]

File: pkg/devfile/image/docker_compatible.go (hunk 4 above)
Comment (mohammedzee1000) [reply pkg/devfile/image/docker_compatible.go:50]: Sure

File: pkg/devfile/image/docker_compatible.go (hunk 3 above)
Comment (mohammedzee1000) [reply pkg/devfile/image/docker_compatible.go:72]: ok

File: pkg/devfile/image/docker_compatible.go [hunk 5]
```diff
@@ -57,21 +70,30 @@ func (o *DockerCompatibleBackend) Build(image *devfile.ImageComponent, devfilePa
...
+		"build",
+		"-t",
+		imageName,
+		"-f",
+		dockerfile,
+		buildpath,
+	}
 	if len(args) > 0 {
-		shell = shell + " " + strings.Join(args, " ")
+		shellCmd = append(shellCmd, args...)
```
Comment (rm3l) [inline pkg/devfile/image/docker_compatible.go:94]: Per the Devfile spec, `args` are `arguments to supply to the dockerfile build`. Since they are passed to the `<docker|podman> build ...` command, they could be expandable as well, no?

Comment (mohammedzee1000) [reply pkg/devfile/image/docker_compatible.go:94]: Yes that is why the for loop for expansion iterates over the entire array

Comment (rm3l) [reply pkg/devfile/image/docker_compatible.go:94]: My bad, I didn't see that this was already inside `getShellCommand`. Fine then.

**Comment by rm3l** [comment]
@mohammedzee1000 Could we trigger the Windows tests, to make sure this is also covered by the existing tests? Since the original issue was more about building images on Windows.

**Comment by rm3l** [comment]
@mohammedzee1000 Could we trigger the Windows tests in CI, to make sure the existing integration tests cover your changes? Since the original issue was specifically about both `build-images` and `deploy` on Windows.

BTW, I manually tested your changes on Windows, and it worked great 👍🏿

**Comment by mohammedzee1000** [comment]
> @mohammedzee1000 Could we trigger the Windows tests in CI, to make sure the existing integration tests cover your changes? Since the original issue was specifically about running both `build-images` and `deploy` on Windows.
> 
> BTW, I manually tested your changes on Windows, and they worked great 👍🏿

@rm3l I would love to but by the looks of it all tests have run for the PR but it does not seem to have windows test.
Also, we would need windows without `bash` installed for one test.

@anandrkskd @rnapoles-rh one of you guys know about win testing?

**Comment by rm3l** [comment]
> > @mohammedzee1000 Could we trigger the Windows tests in CI, to make sure the existing integration tests cover your changes? Since the original issue was specifically about running both `build-images` and `deploy` on Windows.
> > BTW, I manually tested your changes on Windows, and they worked great 👍🏿
> 
> @rm3l I would love to but by the looks of it all tests have run for the PR but it does not seem to have windows test. Also, we would need windows without `bash` installed for one test.
> 
Yup, I saw them triggered for some other PRs like #5675 but not for this one (where it could have been interesting), and was wondering what would be the condition to run them.

**Comment by dharmit** [comment]
> Yup, I saw them triggered for some other PRs like #5675

On that PR, I force pushed after a rebase because of a panic I saw in Windows test. But after the force push, I don't see Windows tests in the list.

**Comment by mohammedzee1000** [comment]
That is inconsistant behavior

**Comment by rm3l** [comment]
@mohammedzee1000 Can you rebase your branch onto `main`, so we can see if the Windows tests get triggered by chance? ¯\_(ツ)_/¯

**Comment by mohammedzee1000** [comment]
@anandrkskd not sure what happened for windows ocp test there

**Comment by anandrkskd** [comment]
> @anandrkskd not sure what happened for windows ocp test there

The windows tests failed with some network error, as tests failed on project creation, for multiple test cases.

**Comment by mohammedzee1000** [comment]
Retriggering by using @valaparthvi hack :D

**Comment by mohammedzee1000** [comment]
odd win test did not trigger

**Comment by mohammedzee1000** [comment]
@rm3l well, it passed

**Comment by rm3l** [comment]
> @rm3l well, it passed

Awesome 🎉 - thanks.

/lgtm
/approve
