### PR TITLE
Fix parametrized integration tests

### LINKED ISSUE #5814: Dynamically generated specs with for loop do not work with ginkgo
We recently started using `for` loops for test cases that share the same test logic but require different parameters. But it does not seem to work as we would have hoped.
For example, consider the following test:
https://github.com/redhat-developer/odo/blob/4ba943986dd85e773626659567c73ce69db55213/tests/integration/cmd_namespace_test.go#L26-L49

The parameters `[]string{"namespace", "project"}` works well for the `Describe` and `It` blocks' text, but not with the logic of the test. For some reason, it always takes "project" into account while testing.

Following is the output of a test run(tests have been explicitly set to fail in order to see the output) - https://gist.github.com/valaparthvi/3d178d3e495a4c42746501cc51c33080. Notice that for both the test runs, it uses `odo create project`.

A solution to writing parametrized test cases would be to use `DescribeTable`. See https://onsi.github.io/ginkgo/#table-specs.

I was unable to find `DescribeTable` with the ginkgo pkg that we have at the moment.
I noticed that the ginkgo pkg we use is actually github.com/openshift/onsi-ginkgo which happens to be a very very old copy of github.com/onsi/ginkgo. And, the version that we are using also happens to be quite old, the latest that I see of openshift/onsi-ginkgo is 4.9, while we're still on 4.7. I am not sure why we decided to use it in the first place, but perhaps we can move to using the onsi/ginkgo pkg for our test cases.

### PR DESCRIPTION
**Pull request by valaparthvi**
**What type of PR is this:**
/kind tests

**What does this PR do / why we need it:**
This PR makes an attempt at fixing dynamically generated specs. We have been using for loops with our integration tests, but it doesn't work as expected. The fix introduced with this PR attempts at fixing that.

**Which issue(s) this PR fixes:**

Fixes #5814 

**PR acceptance criteria:**

- [ ] Unit test 

- [x] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**
1. Debug tests, make sure correct data is taken into account.

### CODE REVIEW

File: tests/integration/cmd_namespace_test.go [hunk 1]
```diff
@@ -22,13 +22,13 @@ var _ = Describe("odo create/delete/list/set namespace/project tests", func() {
 	AfterEach(func() {
 		helper.CommonAfterEach(commonVar)
 	})
-
 	for _, commandName := range []string{"namespace", "project"} {
-
+		// this is a workaround to ensure that the for loop works with `It` blocks
+		commandName := commandName
```
Comment (feloy) [inline tests/integration/cmd_namespace_test.go:27]: You are creating shadowed variables this way. It would be better to use different names for the two variables

Comment (valaparthvi) [reply tests/integration/cmd_namespace_test.go:27]: > This will generate several Its - one for each category. Note that you must assign a copy of the loop variable to a local variable (that's what category := category is doing) - otherwise the It closure will capture the mutating loop variable and all the specs will run against the last element in the loop. It is idiomatic to give the local copy the same name as the loop variable.(https://onsi.github.io/ginkgo/#dynamically-generating-specs)

It is by design if I am understanding it correctly.

Comment (rm3l) [reply tests/integration/cmd_namespace_test.go:27]: I was also surprised to see that this was not reported by `golangci-lint` (and `govet`) as a potential issue.
I guess this is particularly fine for `govet` as we are shadowing the variable with itself.
It would be detected by `golangci-lint` if we assigned a different value, I think.

File: tests/integration/devfile/cmd_delete_test.go [hunk 2]
```diff
@@ -36,7 +36,7 @@ var _ = Describe("odo delete command tests", func() {
 	}{
 		{
 			title:       "a component is bootstrapped",
-			devfileName: "devfile-deploy-with-multiple-resources",
+			devfileName: "devfile-deploy-with-multiple-resources.yaml",
```
Comment (rm3l) [inline tests/integration/devfile/cmd_delete_test.go:39]: Thanks for fixing this, and adding the missing Devfile 👍🏿

**Review by rm3l — COMMENTED** [review]
/approve

Thanks for fixing these tests, @valaparthvi!
