### PR TITLE
Make port-forwarding work on Podman with apps listening on the loopback interface, via a new `--forward-localhost` flag

### LINKED ISSUE #6510: On Podman, unable to access local ports forwarded to container applications listening on the loopback interface (e.g. debug endpoints)
/kind bug
/area dev
/area odo-on-podman

## What versions of software are you using?

**Operating System:**
Fedora 37, kernel 6.1.6-200.fc37.x86_64

**Output of `odo version`:**
`odo v3.5.0` (8dbf42e5e)

## How did you run odo exactly?

```
$ mkdir /tmp/nodejs && cd /tmp/nodejs
$ odo init --name debug-nodejs --devfile nodejs --starter nodejs-starter
$ ODO_EXPERIMENTAL_MODE=t odo dev --platform=podman --debug

...
 •  Executing the application (command: debug)  ...
 -  Forwarding from 127.0.0.1:40001 -> 3000
 -  Forwarding from 127.0.0.1:40002 -> 5858

...
```

As expected, trying to access the forwarded application port (40001 here) works correctly:
```
$ curl -i http://localhost:40001
HTTP/1.1 200 OK
X-Powered-By: Express
Content-Type: text/html; charset=utf-8
Content-Length: 39
ETag: W/"27-Jw3xdDamjf5jthPp3a/zd95HG0Y"
Date: Wed, 18 Jan 2023 15:04:06 GMT
Connection: keep-alive
Keep-Alive: timeout=5

Hello from Node.js Starter Application!%
```

But trying to access the application on the forwarded debug port (40002 here) returns an error:
```
$ curl -i http://localhost:40002
curl: (56) Recv failure: Connection reset by peer
```

## Actual behavior
Accessing the application on the forwarded debug port (40002 here) returns an error:
```
$ curl -i http://localhost:40002
curl: (56) Recv failure: Connection reset by peer
```

## Expected behavior
When running `odo dev` against a cluster, we get the expected HTTP response from the forwarded application debug port:
```
$ curl -i http://localhost:40002
HTTP/1.0 400 Bad Request
Content-Type: text/html; charset=UTF-8

WebSockets request was expected
```

I was expecting the same behavior on Podman.

## Any logs, error output, etc?

<details>
<summary>podman kube generate</summary>

```yaml
# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.3.1
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.kubernetes.cri-o.ContainerType/debug-nodejs-app-runtime: container
    io.kubernetes.cri-o.SandboxID/debug-nodejs-app-runtime: 269e89e69b091b501843a3c29f0578568cd91f76496c92da296c57cef27c62c
    io.podman.annotations.autoremove/debug-nodejs-app-runtime: "FALSE"
    io.podman.annotations.init/debug-nodejs-app-runtime: "FALSE"
    io.podman.annotations.privileged/debug-nodejs-app-runtime: "FALSE"
    io.podman.annotations.publish-all/debug-nodejs-app-runtime: "FALSE"
  creationTimestamp: "2023-01-18T15:17:30Z"
  labels:
    app: debug-nodejs-app
  name: debug-nodejs-app
spec:
  automountServiceAccountToken: false
  containers:
  - args:
    - tail
    - -f
    - /dev/null
    env:
    - name: PROJECTS_ROOT
      value: /projects
    - name: DEBUG_PORT
      value: "5858"
    - name: PROJECT_SOURCE
      value: /projects
    image: registry.access.redhat.com/ubi8/nodejs-16:latest
    name: debug-nodejs-app-runtime
    ports:
    - containerPort: 3000
      hostPort: 40001
    - containerPort: 5858
      hostPort: 40002
    resources:
      limits:
        memory: 1Gi
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    volumeMounts:
    - mountPath: /projects
      name: odo-projects-debug-nodejs-app-pvc
    - mountPath: /opt/odo/
      name: odo-shared-data-debug-nodejs-app-pvc
  enableServiceLinks: false
  hostname: debug-nodejs-app
  restartPolicy: Always
  volumes:
  - name: odo-projects-debug-nodejs-app-pvc
    persistentVolumeClaim:
      claimName: odo-projects-debug-nodejs-app
  - name: odo-shared-data-debug-nodejs-app-pvc
    persistentVolumeClaim:
      claimName: odo-shared-data-debug-nodejs-app
status: {}
```

</details>

### PR DESCRIPTION
**Pull request by rm3l**
**What type of PR is this:**
/kind feature
/area odo-on-podman
/area dev

**What does this PR do / why we need it:**
This is the second and last PR (building on https://github.com/redhat-developer/odo/pull/6620) to address #6510.

For some context, the way `odo` currently does port-forwarding on Podman is via a `HostPort` in the relevant container in the pod spec. But as reported in https://github.com/redhat-developer/odo/issues/6510 and https://github.com/containers/podman/issues/17353, Podman won't forward traffic to the container if the container port is bound to the container loopback interface.
As discussed in https://github.com/redhat-developer/odo/issues/6510#issuecomment-1439986558 (and similar to how things work on DevSpaces), https://github.com/redhat-developer/odo/pull/6620 tried to detect if ports that need to be forwarded are bound to the container loopback interface. If this is the case:
- by default, `odo dev` on Podman will error out with an error message indicating the issue, along with a recommendation to either change the application to listen on 0.0.0.0, or to run `odo dev` with  `--forward-localhost`.
- if `odo dev` is run with `--ignore-localhost`, this message will be displayed as a warning, but this won't prevent `odo dev` from running. However, any request sent out to the local port forwarded to the container on its loopback interface might not work with Podman.

This PR is about supporting a new `--forward-localhost` flag, to make port-forwarding work on Podman with applications bound to the loopback interface. It does so by injecting a dedicated side container (running the [`quay.io/devfile/base-developer-image`](https://quay.io/repository/devfile/base-developer-image?tab=tags) image). Port-forwarding is then done by running a `socat` command in this container. It will listen on one port on all interfaces, and on the other hand forward traffic to the second port (which might be bound to the loopback interface).

The main interest of having this flag on Podman is to have on Podman the same behaviour as `kubectl port-forward` on Kubernetes, which is able to port-forward a container port bound on localhost. This is primarily useful for working with the debugger on localhost, without exposing it on all interfaces, for security reasons.

**Which issue(s) this PR fixes:**
Fixes #6510 

**PR acceptance criteria:**

- [x] Unit test 

- [x] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**
This behavior should *not* affect the default cluster mode.

To test the changes on Podman, either use a project with an application listening on some port on localhost, or leverage some existing stacks like Node.JS which have debuggers listening on localhost.

```
$ mkdir /tmp/nodejs && cd /tmp/nodejs
$ odo init --name debug-nodejs --devfile nodejs --starter nodejs-starter
```

- Without `--forward-localhost`, the behavior depends on the value of `--ignore-localhost`. See https://github.com/redhat-developer/odo/pull/6620#issue-1597224571.

- With `--forward-localhost`, `odo dev` on Podman should start and requests sent to the debug port should work as expected:
```
$ ODO_EXPERIMENTAL_MODE=t odo dev --platform=podman --debug --forward-localhost

...
↪ Running on podman in Dev mode
 ✓  Deploying pod [3s]
 ✓  Building your application in container (command: install) [4s]
 •  Executing the application (command: debug)  ...
 -  Forwarding from 127.0.0.1:20001 -> 3000
 -  Forwarding from 127.0.0.1:20002 -> 5858

↪ Dev mode
 Status:
 Watching for changes in the current directory /tmp/test/nodejs

 Keyboard Commands:
[Ctrl+c] - Exit and delete resources from podman
     [p] - Manually apply local changes to the application on podman
```

NOTE: a sidecar is added as long as `--forward-localhost` is passed, even if the application is not listening on the loopback interface. But this does not prevent port-forwarding from working correctly. In the example above, if I run `ODO_EXPERIMENTAL_MODE=t odo dev --platform=podman --forward-localhost` (without `--debug`), `odo dev` should start and work normally.

### CODE REVIEW

File: pkg/odo/genericclioptions/clientset/clientset.go [hunk 1]
```diff
@@ -236,14 +238,20 @@ func Fetch(command *cobra.Command, platform string) (*Clientset, error) {
 		dep.BindingClient = binding.NewBindingClient(dep.ProjectClient, dep.KubernetesClient)
 	}
 	if isDefined(command, PORT_FORWARD) {
-		dep.PortForwardClient = portForward.NewPFClient(dep.KubernetesClient, dep.StateClient)
+		switch platform {
+		case commonflags.PlatformPodman:
+			dep.PortForwardClient = podmanportforward.NewPFClient(dep.ExecClient)
```
Comment (feloy) [inline pkg/odo/genericclioptions/clientset/clientset.go:243]: I think you will need to add EXEC as dependency of PORT_FORWARD in `subdeps`.

I works as is now because EXEC is added as a direct dependency of the dev command, but this could change in the future

Comment (rm3l) [reply pkg/odo/genericclioptions/clientset/clientset.go:243]: Good point indeed! I've updated the sub-deps in [`7b384d3` (#6629)](https://github.com/redhat-developer/odo/pull/6629/commits/7b384d3aa85641ed81a15615ceea713df126ea04). Also noted that `EXEC` might also be missing the `PODMAN_NULLABLE`.

**Review by feloy — APPROVED** [review]
