### PR TITLE
replacing timeout with time interval

### LINKED ISSUE #6368: Flake: odo list namespace/project -o json fails
Test case  `odo list namespace/project -o json`  fails with flake 
- [FAIL] odo create/delete/list/set namespace/project tests list project [It] should successfully list all the projects in JSON format
- [FAIL] odo create/delete/list/set namespace/project tests list namespace [It] should successfully list all the namespaces in JSON format

/kind tests

### PR DESCRIPTION
**Pull request by anandrkskd**
Signed-off-by: anandrkskd <anandrkskd@gmail.com>

**What type of PR is this:**

/kind tests

**What does this PR do / why we need it:**
this PR fixes flaky tests for `odo list project/namespace -o json`

**Which issue(s) this PR fixes:**

Fixes #6368 

**PR acceptance criteria:**

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**

### CODE REVIEW

File: tests/integration/cmd_namespace_test.go [hunk 1]
```diff
@@ -196,7 +196,7 @@ ComponentSettings:
 					g.Expect(gjson.Get(out, gjsonStr).String()).To(Equal("true"))
 					// ensure that some namespace is marked as "active: false"
 					g.Expect(gjson.Get(out, "namespaces.#[active==false]#.name").String()).ShouldNot(ContainSubstring(commonVar.Project))
-				}).WithTimeout(10 * time.Second).Should(Succeed())
+				}, 10*time.Second, 1*time.Second).Should(Succeed())
```
Comment (rm3l) [inline tests/integration/cmd_namespace_test.go:199]: Isn't this already covered by https://github.com/redhat-developer/odo/commit/70c5bd505b67cbb1cb84e90581b6aacc4b1598a1? Or are we still getting issues because the default polling interval is relatively low (10ms)?
The first time I noticed similar flakes was because of the way the test was written: calling `odo list namespace` first, then calling `odo list namespace -o json`, but sometimes the second call would not contain the expected namespace/project.

Anyways, the changes here make sense to me. But I find it more readable to use the `With*` methods. I usually need to think twice to determine which argument is the polling interval and which one is the timeout :D

```suggestion
				}).WithPolling(1*time.Second).WithTimeout(10 * time.Second)Should(Succeed())
```

Comment (anandrkskd) [reply tests/integration/cmd_namespace_test.go:199]: I didn't notice this was a recent change, I noticed we are using withTimeout, and not added value for WithPolling.
Thanks.

Comment (rm3l) [reply tests/integration/cmd_namespace_test.go]: Whoops, there was a missing `.` in the change suggested :/

Comment (anandrkskd) [reply tests/integration/cmd_namespace_test.go]: fixed

**Review by rm3l — APPROVED** [review]

**Comment by rm3l** [comment]
```
X  Building your application in container on cluster (command: build) [300ms]
    [odo] go: could not create module cache: mkdir /opt/app-root/src/go: permission denied

...
Summarizing 1 Failure:
  [FAIL] E2E Test starting with non-empty Directory add Binding [It] should verify developer workflow of using binding as env in innerloop
  C:/Users/Administrator.ANSIBLE-TEST-VS/2673/tests/helper/helper_run.go:51

Ran 7 of 7 Specs in 509.253 seconds
FAIL! -- 6 Passed | 1 Failed | 0 Pending | 0 Skipped
```

E2E tests are failing due to https://github.com/devfile/api/issues/994
