### PR TITLE
fix: manage podman inspect result as a list also

### LINKED ISSUE #7252: Error running commands when using platform=podman
/kind bug

## What versions of software are you using?

**Operating System:**
Fedora 40

**Output of `odo version`:**
odo v3.15.0 (10b5e8a8f)
also tried:
odo v3.16.1 (cd346c5e6-nightly)

## How did you run odo exactly?
odo dev --platform=podman

## Actual behavior
The pods startup in podman, but commands fail. I also get this error during startup:

 ✗  Building your application in container (command: install) [436ms]
Error occurred on Push - unable to log error unable to exec command [/bin/sh -c cd ${PROJECT_SOURCE} && (npm install) 1>>/proc/1/fd/1 2>>/proc/1/fd/2]: exit status 254: a running component clientapp doesn't exist on the cluster: json: cannot unmarshal array into Go value of type podman.PodInspectData

## Expected behavior
odo startup should start podman pods without errors. Issuing `odo run <command>` should also work.

## Any logs, error output, etc?
 ✗  Building your application in container (command: install) [436ms]
Error occurred on Push - unable to log error unable to exec command [/bin/sh -c cd ${PROJECT_SOURCE} && (npm install) 1>>/proc/1/fd/1 2>>/proc/1/fd/2]: exit status 254: a running component clientapp doesn't exist on the cluster: json: cannot unmarshal array into Go value of type podman.PodInspectData

### PR DESCRIPTION
**Pull request by too-common-name**
**What type of PR is this:**

/kind bug
/area odo-on-podman

**What does this PR do / why we need it:**

This PR addresses an issue when using the `odo` commands with Podman, specifically related to the `podman pod inspect` command. Due to a recent change in Podman (see [podman PR #21514](https://github.com/containers/podman/pull/21514)), the output now returns a JSON array instead of a JSON object. This PR modifies `odo` to correctly handle this change, preventing errors in commands like `odo debug` and `odo logs` when running on Podman.

**Which issue(s) this PR fixes:**

Fixes #7252

**PR acceptance criteria:**

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**

### CODE REVIEW

File: pkg/podman/inspect.go [hunk 1]
```diff
@@ -34,8 +34,13 @@ func (o *PodmanCli) PodInspect(podname string) (PodInspectData, error) {
...
+	var result []PodInspectData
 	err = json.Unmarshal(out, &result)
-	return result, err
+	if err != nil {
+		var singleResult PodInspectData
+		err = json.Unmarshal(out, &singleResult)
+		return singleResult, err
+	}
+
+	return result[0], err
```
Comment (rm3l) [inline pkg/podman/inspect.go:45]:
```suggestion
	if len(result) == 0 {
		return PodInspectData{}, nil
	}
	return result[0], nil
```

Just to be safe and avoid panicking if the list is empty for some reason.

**Review by rm3l — CHANGES_REQUESTED** [review]

**Review by rm3l — APPROVED** [review]
Thanks @too-common-name !!

**Comment by too-common-name** [comment]
Thank you for merging this! This was my first contribution as a RedHatter, and I'm really excited to have been able to help improve odo. I hope this is just the first of many contributions to come. Looking forward to learning more and contributing further to the community!
