### PR TITLE
Fix: Starterproject not replace existing devfile stack files of the context dir

### LINKED ISSUE #6489: Downloading starterproject replaces existing contents of a directory
The issue with registry-support has been fixed so the extra stack files will be downloaded, but the problem still remains. If you opt to download the starter project, it overrides the extra stack files. So what remains now is to fix that.

In the below example, when  we do not use starterproject, it downloads the extra stack files under `docker` and `kubernetes` directories.

```sh
$ odo init --name java-springboot-starter --devfile java-springboot --devfile-registry DefaultDevfileRegistry --devfile-version 2.0.0                            
  __
 /  \__     Initializing a new component
 \__/  \    
 /  \__/    odo version: v3.5.0
 \__/

 ✓  Downloading devfile "java-springboot:2.0.0" from registry "DefaultDevfileRegistry" [18s]

Your new component 'java-springboot-starter' is ready in the current directory.
To start editing your component, use 'odo dev' and open this folder in your favorite IDE.
Changes will be directly reflected on the cluster.
To deploy your component to a cluster use "odo deploy".

$ ls
devfile.yaml  docker  kubernetes
```

In the below example, we use starterproject which deletes the `docker` and `kubernetes` directories.

```sh
$ odo init --name java-springboot-starter --devfile java-springboot --devfile-registry DefaultDevfileRegistry --devfile-version 2.0.0 --starter springbootproject
  __
 /  \__     Initializing a new component
 \__/  \    
 /  \__/    odo version: v3.5.0
 \__/

 ✓  Downloading devfile "java-springboot:2.0.0" from registry "DefaultDevfileRegistry" [3s]
 ✓  Downloading starter project "springbootproject" [686ms]

Your new component 'java-springboot-starter' is ready in the current directory.
To start editing your component, use 'odo dev' and open this folder in your favorite IDE.
Changes will be directly reflected on the cluster.
To deploy your component to a cluster use "odo deploy".

$ ls
devfile.yaml  HELP.md  mvnw  mvnw.cmd  pom.xml  src
```

_Originally posted by @valaparthvi in https://github.com/redhat-developer/odo/issues/6448#issuecomment-1381894379_

### PR DESCRIPTION
**Pull request by valaparthvi**
**What type of PR is this:**
/kind bug

**What does this PR do / why we need it:**
This PR ensures that downloading a starter project does not replace an existing stack files downloading as a part of the Devfile.
**Which issue(s) this PR fixes:**

Fixes #6489 

**PR acceptance criteria:**

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**
0. Setup a custom devfile registry by using quay.io/pvala18/devfile-index:latest and go Devfile.
1. Running the `odo init --devfile go --devfile-version latest --starter go-starter --name my-go-app` should show the following result:
```sh
➜  ls
README.md    devfile.yaml docker       go.mod       kubernetes   main.go
```
Here `docker` and `kubernetes` are a part of the Devfile stack.
2. Run `odo init --devfile go --devfile-version latest --starter conflicting-starter-project-demo --name my-go-app`. A CONFLICT_STARTER_PROJECT should have been created containing the starter project and a warning must be printed listing the conflicting files.
3. Run `odo init --devfile go --devfile-version latest --starter starterproject-with-devfile-demo --name my-go-app`. Downloading the starter project should replace devfile.yaml and the stack files.

### CODE REVIEW

**Comment by valaparthvi** [comment]
/override Kubernetes-Integration-Tests/Kubernetes-Integration-Tests

```sh
  Expected
      <string>:  âš   Pod is Terminating
       âœ—  Finished executing the application (command: devrun) [43s]
       âš   No pod exists
       âš   Pod is Pending
       âœ“  Pod is Running
       â€¢  Syncing files into the container  ...
      
 âœ“  Syncing files into the container [501ms]
       â€¢  Building your application in container (command: devbuild)  ...
      
 âœ“  Building your application in container (command: devbuild) [3s]
       â€¢  Executing the application (command: devrun)  ...
       -  Forwarding from 127.0.0.1:39429 -> 3000
      
      
      â†ª Dev mode
       Keyboard Commands:
      [Ctrl+c] - Exit and delete resources from the cluster
           [p] - Manually apply local changes to the application on the cluster
      
  To satisfy at least one of these matchers: [%!s(*matchers.ContainSubstringMatcher=&{Pushing files... []}) %!s(*matchers.ContainSubstringMatcher=&{Updating Component... []})]
  In [BeforeEach] at: /go/odo_1/tests/helper/helper_run.go:64
------------------------------
â€¢â€¢â€¢â€¢â€¢â€¢â€¢


Summarizing 1 Failure:
  [FAIL] odo dev command tests port-forwarding for the component when devfile has single endpoint when running odo dev when modifying memoryLimit for container in Devfile [BeforeEach] should react on the Devfile modification
  /go/odo_1/tests/helper/helper_run.go:64
```

**Comment by valaparthvi** [comment]
/override windows-integration-test/Windows-test

```sh
  Expected
      <*url.Error | 0xc0002ec8a0>: {
          Op: "Post",
          URL: "http://127.0.0.1:64534/api/newuser",
          Err: <*errors.errorString | 0xc000088130>{s: "EOF"},
      }
  to be nil
  In [It] at: C:/Users/Administrator.ANSIBLE-TEST-VS/3416/tests/e2escenarios/e2e_test.go:306

  There were additional failures detected after the initial failure.  Here's a summary - for full details run Ginkgo in verbose mode:
    [FAILED] in [AfterEach] at C:/Users/Administrator.ANSIBLE-TEST-VS/3416/tests/helper/helper_filesystem.go:48
------------------------------


Summarizing 1 Failure:
  [FAIL] E2E Test starting with non-empty Directory add Binding [It] should verify developer workflow of using binding as env in innerloop
  C:/Users/Administrator.ANSIBLE-TEST-VS/3416/tests/e2escenarios/e2e_test.go:306

```

File: pkg/registry/registry.go [hunk 1]
```diff
@@ -54,9 +60,122 @@ func (o RegistryClient) DownloadFileInMemory(params dfutil.HTTPRequestParams) ([
...
+		return err
+	}
+	for _, f := range dir {
+		// a bit of cheating by using absolute file name to make sure this works with a fake filesystem, especially a memory map which is used by our unit tests
+		// memorymap's Name() method trims the full path and returns just the file name, which then becomes impossible to find by the RemoveAll method that looks for prefix
+		// See: https://github.com/redhat-developer/odo/blob/d717421494f746a5cb12da135f561d12750935f3/vendor/github.com/spf13/afero/memmap.go#L282
+		absFileName := filepath.Join(path, f.Name())
+		err = fsys.RemoveAll(absFileName)
+		if err != nil {
+			return fmt.Errorf("failed to remove %s; cause: %s", absFileName, err)
```
Comment (rm3l) [inline pkg/registry/registry.go:140]: In case we need to `Unwrap` it.

```suggestion
			return fmt.Errorf("failed to remove %s; cause: %w", absFileName, err)
```

File: pkg/registry/registry.go [hunk 2]
```diff
@@ -269,11 +388,20 @@ func createRegistryDevfiles(registry api.Registry, devfileIndex []indexSchema.Sc
 func (o RegistryClient) retrieveDevfileDataFromRegistry(ctx context.Context, registryName string, devfileName string) (api.DevfileData, error) {
 
 	// Create random temporary file
-	tmpFile, err := os.MkdirTemp("", "odo")
+	tmpFile, err := o.fsys.TempDir("", "odo")
 	if err != nil {
 		return api.DevfileData{}, err
 	}
-	defer os.Remove(tmpFile)
+	err = o.fsys.MkdirAll(tmpFile, 0700)
```
Comment (rm3l) [inline pkg/registry/registry.go:395]: I think `o.fsys.TempDir` should create the temporary directory, so not sure we need this extra call.

File: pkg/util/util.go [hunk 3]
```diff
@@ -228,7 +224,7 @@ func IsValidProjectDir(path string, devfilePath string) error {
 // takes an absolute path prefixed with file:// and extracts it to a destination.
 // pathToUnzip specifies the path within the zip folder to extract
 // TODO(feloy) sync with devfile library?
-func GetAndExtractZip(zipURL string, destination string, pathToUnzip string, starterToken string) error {
+func GetAndExtractZip(zipURL string, destination string, pathToUnzip string, starterToken string, fsys filesystem.Filesystem) error {
```
Comment (rm3l) [inline pkg/util/util.go:227]: Can `fsys` be the first parameter of this function, just to be consistent with the other functions like `IsValidProjectDir`?

File: pkg/util/util.go [hunk 4]
```diff
@@ -252,21 +252,21 @@ func GetAndExtractZip(zipURL string, destination string, pathToUnzip string, sta
...
 		}
-		err := dfutil.DownloadFile(params)
+		err = dfutil.DownloadFile(params)
 		if err != nil {
 			return err
 		}
 
 		defer func() {
-			if err := dfutil.DeletePath(pathToZip); err != nil {
+			if err = fsys.Remove(pathToZip); err != nil && !os.IsNotExist(err) {
```
Comment (rm3l) [inline pkg/util/util.go:261]: `os.IsNotExist(err)` seems to not be recommended: https://pkg.go.dev/os#IsNotExist

```suggestion
			if err = fsys.Remove(pathToZip); err != nil && !errors.Is(err, fs.ErrNotExist) {
```

**Review by rm3l — CHANGES_REQUESTED** [review]

File: pkg/registry/registry.go [hunk 5]
```diff
@@ -54,9 +60,122 @@ func (o RegistryClient) DownloadFileInMemory(params dfutil.HTTPRequestParams) ([
...
+// Case 2: If there is no devfile, but contents of the temp directory match some contents of the contextDir, copy contents of the temp dir into a dir named CONFLICT_STARTER_PROJECT; warn about this
+// Case 3: If there is no devfile, and no contents of the temp dir matching contents of the contextDir, copy contents of the temp dir into contextDir.
 func (o RegistryClient) DownloadStarterProject(starterProject *devfilev1.StarterProject, decryptedToken string, contextDir string, verbose bool) error {
-	return DownloadStarterProject(starterProject, decryptedToken, contextDir, verbose)
+	// Let the project be downloaded in a temp directory
+	starterProjectTmpDir, err := o.fsys.TempDir("", "odostarterproject")
+	if err != nil {
+		return err
+	}
+	err = o.fsys.MkdirAll(starterProjectTmpDir, 0755)
```
[the remark this answers is not in the document]
Comment (valaparthvi) [reply pkg/registry/registry.go:73]: I remember simply using TempDir, but it didn't not create one, at least not while I was testing unit test IIRC. But I'll check again.

[the remark this answers is not in the document]
Comment (valaparthvi) [reply pkg/registry/registry.go:73]: You're right, it works fine.

File: pkg/registry/registry.go [hunk 6]
```diff
@@ -54,9 +60,122 @@ func (o RegistryClient) DownloadFileInMemory(params dfutil.HTTPRequestParams) ([
...
+		return downloadStarterProjectErr
+	}
+
+	// Case 1
+	if containsDevfile, _ := location.DirectoryContainsDevfile(o.fsys, starterProjectTmpDir); containsDevfile {
+		fmt.Println()
+		log.Warning("devfile.yaml is present inside the starter project; replacing the entire content of the current directory with the starter project")
+		err = removeDirectoryContents(contextDir, o.fsys)
+		if err != nil {
+			klog.V(0).Infof(err.Error())
```
[the remark this answers is not in the document]
Comment (valaparthvi) [reply pkg/registry/registry.go:95]: You're right. I should've done that.

File: tests/integration/cmd_devfile_init_test.go [hunk 7]
```diff
@@ -247,17 +247,6 @@ var _ = Describe("odo devfile init command tests", func() {
 				})
 			})
 
-			When("a devfile is provided which has a starter that has its own devfile", func() {
-				BeforeEach(func() {
-					helper.Cmd("odo", "init", "--name", "aname", "--starter", "nodejs-starter", "--devfile-path", helper.GetExamplePath("source", "devfiles", "nodejs", "devfile-with-starter-with-devfile.yaml")).ShouldPass()
-				})
-				It("should pass and keep the devfile in starter", func() {
```
[the remark this answers is not in the document]
Comment (valaparthvi) [reply tests/integration/cmd_devfile_init_test.go:254]: We could, if we keep this, I was also thinking to add one more where starterproject does not have conflicting files. But then we have these tests essentially covered in unit test, so I didn't bother to add them here.

File: pkg/util/util.go (hunk 3 above)
Comment (valaparthvi) [reply pkg/util/util.go:228]: I've changed the position of `fsys` in `IsValidProjectDir` just to be more consistent with other functions.

**Comment by valaparthvi** [comment]
/override Kubernetes-Integration-Tests/Kubernetes-Docs-Integration-Tests
```
  user-guides/quickstart/docs-mdx/dotnet/dotnet_odo_dev_output.mdx
  Expected
      <string>:   (
        	"""
        	... // 9 identical lines
        	â€¢  Waiting for Kubernetes resources  ...
        	âš   Pod is Pending
      - 	âœ“  Pod is Running
        	âœ“  Syncing files into the container [1s]
        	âœ“  Building your application in container (command: build) [1s]
        	... // 9 identical lines
        	[Ctrl+c] - Exit and delete resources from the cluster
        	[p] - Manually apply local changes to the application on the cluster
      + 	âœ“  Pod is Running
        	```
        	"""
        )
      
  to be empty
  In [It] at: /go/odo_1/tests/documentation/user-guides/doc_user_guides_quickstart_test.go:208
------------------------------
Spawning '/go/bin/odo init' from /tmp/2337855403
â€¢â€¢Spawning '/go/bin/odo init' from /tmp/4264151494
â€¢Spawning '/go/bin/odo init' from /tmp/1110626714
â€¢


Summarizing 1 Failure:
  [FAIL] User guides: Quickstart test .NET quickstart guide [It] should test the complete dotnet quickstart output in order
  /go/odo_1/tests/documentation/user-guides/doc_user_guides_quickstart_test.go:208
```

**Comment by valaparthvi** [comment]
/override windows-integration-test/Windows-test
```
  Expected
      <*url.Error | 0xc0005dac00>: {
          Op: "Post",
          URL: "http://127.0.0.1:61953/api/newuser",
          Err: <*errors.errorString | 0xc000088130>{s: "EOF"},
      }
  to be nil
  In [It] at: C:/Users/Administrator.ANSIBLE-TEST-VS/3429/tests/e2escenarios/e2e_test.go:306

  There were additional failures detected after the initial failure.  Here's a summary - for full details run Ginkgo in verbose mode:
    [FAILED] in [AfterEach] at C:/Users/Administrator.ANSIBLE-TEST-VS/3429/tests/helper/helper_filesystem.go:48
------------------------------


Summarizing 1 Failure:
  [FAIL] E2E Test starting with non-empty Directory add Binding [It] should verify developer workflow of using binding as env in innerloop
  C:/Users/Administrator.ANSIBLE-TEST-VS/3429/tests/e2escenarios/e2e_test.go:306
```

**Review by rm3l — CHANGES_REQUESTED** [review]

File: pkg/registry/registry.go [hunk 8]
```diff
@@ -54,9 +60,124 @@ func (o RegistryClient) DownloadFileInMemory(params dfutil.HTTPRequestParams) ([
...
+}
+
+// getConflictingFiles fetches the contents of the two directories in question and compares them to check for conflicting files.
+// it returns a list of conflicting files (if any) along with an error (if any).
+func getConflictingFiles(spDir, contextDir string, fsys filesystem.Filesystem) (conflictingFiles []string, err error) {
+	var (
+		contextDirMap = map[string]struct{}{}
+	)
+	// walk through the contextDir, trim the file path from the file name and append it to a map
+	err = fsys.Walk(contextDir, func(path string, info fs.FileInfo, err error) error {
```
Comment (rm3l) [inline pkg/registry/registry.go:151]: From my understanding of the documentation of the [`WalkFunc` type](https://pkg.go.dev/path/filepath#WalkFunc), `Walk` might call this handler with a non-nil error:

> The err argument reports an error related to path, signaling that Walk will not walk into that directory. The function can decide how to handle that error; as described earlier, returning the error will cause Walk to stop walking the entire tree.

So I'd suggest returning the error, if any, earlier in this handler.

**Review by rm3l — CHANGES_REQUESTED** [review]
Thanks for the changes. LGTM overall. I had one last comment on error handling when walking the directory tree.

**Review by rm3l — APPROVED** [review]
Thanks for the changes.

File: pkg/registry/registry.go [hunk 9]
```diff
@@ -54,9 +60,130 @@ func (o RegistryClient) DownloadFileInMemory(params dfutil.HTTPRequestParams) ([
...
 // DownloadStarterProject downloads a starter project referenced in devfile
-// This will first remove the content of the contextDir
+// There are 3 cases to consider here:
+// Case 1: If there is devfile in the starterproject, replace all the contents of contextDir with that of the starterproject; warn about this
+// Case 2: If there is no devfile, and there is no conflict between the contents of contextDir and starterproject, then copy the contents of the starterproject into contextDir.
+// Case 3: If there is no devfile, and there is conflict between the contents of contextDir and starterproject, copy contents of starterproject into a dir named CONFLICT_STARTER_PROJECT; warn about this
 func (o RegistryClient) DownloadStarterProject(starterProject *devfilev1.StarterProject, decryptedToken string, contextDir string, verbose bool) error {
-	return DownloadStarterProject(starterProject, decryptedToken, contextDir, verbose)
+	// Let the project be downloaded in a temp directory
+	starterProjectTmpDir, err := o.fsys.TempDir("", "odostarterproject")
```
Comment (rm3l) [inline pkg/registry/registry.go:69]: I think it should be our responsibility to remove this temporary folder when we are done with it. I just noticed I had several non-empty left-over `odostarterproject*` folders on my temporary fielsystem.

**Review by rm3l — CHANGES_REQUESTED** [review]
Whoops, sorry. I just approved this PR feature-wise, but just noticed I had a lot of `odostarterproject*`  and `odo*` non-empty folders filling up my temporary filesystem.

File: pkg/registry/registry.go (hunk 9 above)
Comment (valaparthvi) [reply pkg/registry/registry.go:69]: I figured that since they were temporary files, they would delete themselves on a reboot, but maybe you're right, it would be better to delete them as we go.

File: pkg/registry/registry.go [hunk 10]
```diff
@@ -271,11 +398,10 @@ func createRegistryDevfiles(registry api.Registry, devfileIndex []indexSchema.Sc
 func (o RegistryClient) retrieveDevfileDataFromRegistry(ctx context.Context, registryName string, devfileName string) (api.DevfileData, error) {
 
 	// Create random temporary file
-	tmpFile, err := os.MkdirTemp("", "odo")
+	tmpFile, err := o.fsys.TempDir("", "odo")
 	if err != nil {
 		return api.DevfileData{}, err
 	}
-	defer os.Remove(tmpFile)
```
[the remark this answers is not in the document]
Comment (valaparthvi) [reply pkg/registry/registry.go:278]: Same reason as above.

File: pkg/registry/registry.go (hunk 9 above)
Comment (rm3l) [reply pkg/registry/registry.go:69]: Yes, upon reboot, but it depends on how frequently you reboot :D
