### PR TITLE
Display error message when odo dev fails on podman and clean resources

### LINKED ISSUE #6487: `odo dev` on podman exits in case of failure without an error message
/kind bug

## What versions of software are you using?

**Operating System:**
Fedora 35
**Output of `odo version`:**
odo v3.5.0 (da9a9efb8f)
## How did you run odo exactly?
1. `odo init --devfile nodejs --starter nodejs-starter --name my-nodejs-app`
2. `sed -i "s/registry.access.redhat.com\/ubi8\/nodejs-16:latest/adsffdfe/" devfile.yaml`
3. `ODO_EXPERIMENTAL_MODE=true odo dev --platform=podman`

## Actual behavior
```sh
$ ODO_EXPERIMENTAL_MODE=true odo dev --platform=podman
============================================================================
⚠ Experimental mode enabled. Use at your own risk.
More details on https://odo.dev/docs/user-guides/advanced/experimental-mode
============================================================================

  __
 /  \__     Developing using the "my-nodejs-app" Devfile
 \__/  \    Platform: podman
 /  \__/    odo version: v3.5.0
 \__/

↪ Running on podman in Dev mode
 ✗  Deploying pod [2s]
Cleaning up resources
 ✗  exit status 125: 
```
`odo dev` fails because it did not find the image, but it exits without an error message.

## Expected behavior
`odo dev` should exit with an appropriate error message.

### PR DESCRIPTION
**Pull request by valaparthvi**
Signed-off-by: Parthvi Vala <pvala@redhat.com>

**What type of PR is this:**
/kind bug

**What does this PR do / why we need it:**
This PR ensures `odo dev` on podman exits with actual failure from podman and also cleans up pod if it was created.

**Which issue(s) this PR fixes:**

Fixes #6487 

**PR acceptance criteria:**

- [ ] Unit test 

- [x] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**
1. `odo init --devfile nodejs --starter nodejs-starter --name my-nodejs-app`
2. `sed -i "s/registry.access.redhat.com\/ubi8\/nodejs-16:latest/adsffdfe/" devfile.yaml`
3. `ODO_EXPERIMENTAL_MODE=true odo dev --platform=podman`

For 6501
1. `export PODMAN_CMD=echo`
2. `ODO_EXPERIMENTAL_MODE=true odo dev --platform=podman`

### CODE REVIEW

File: pkg/podman/podman.go [hunk 1]
```diff
@@ -81,7 +82,10 @@ func (o *PodmanCli) PlayKube(pod *corev1.Pod) error {
 	}()
 	if err = cmd.Wait(); err != nil {
 		if exiterr, ok := err.(*exec.ExitError); ok {
-			err = fmt.Errorf("%s: %s", err, string(exiterr.Stderr))
+			out := strings.Split(podmanOut, "\n")
+			// the last line is an empty new line; so we revert to the second last line for error
+			errLine := out[len(out)-2]
+			err = fmt.Errorf("%s: %s\n%s", err, string(exiterr.Stderr), errLine)
```
Comment (feloy) [inline pkg/podman/podman.go:88]: Why do we want to display only the last non-blank line, and not the entire content?
This seems very specific to a use-case where the error message would be in the last non-blank line.

File: pkg/dev/podmandev/cleanup.go [hunk 2]
```diff
@@ -4,12 +4,24 @@ import (
...
 	if o.deployedPod == nil {
-		return nil
+		compName := odocontext.GetComponentName(ctx)
+		appName := odocontext.GetApplication(ctx)
+		name, err := util.NamespaceKubernetesObject(compName, appName)
+		if err != nil {
+			return nil
+		}
+		o.deployedPod = &corev1.Pod{}
+		o.deployedPod.SetName(name)
```
Comment (feloy) [inline pkg/dev/podmandev/cleanup.go:24]: Is this related to this PR? What is the problem fixed by this change?

**Review by feloy — CHANGES_REQUESTED** [review]

File: pkg/dev/podmandev/cleanup.go (hunk 2 above)
Comment (valaparthvi) [reply pkg/dev/podmandev/cleanup.go:24]: In case of some failures, pod is still created, this change attempts at fixing this problem.

File: pkg/podman/podman.go (hunk 1 above)
Comment (valaparthvi) [reply pkg/podman/podman.go:88]: On a second thought, the last line (err line) usually sums up the core issue, so showing just that should be fine. WDYT?

Comment (feloy) [reply pkg/podman/podman.go:88]: I would prefer for the first versions to display the complete output, to have the maximum of information. If we consider it is too much, we could reduce it

File: pkg/dev/podmandev/cleanup.go (hunk 2 above)
Comment (feloy) [reply pkg/dev/podmandev/cleanup.go:24]: I would prefer to fix the problem why deployedPod is null when a Pod is actually deployed

Comment (valaparthvi) [reply pkg/dev/podmandev/cleanup.go]: Podman creates the pod even if something is incorrect with the manifest, for e.g. non-existent image.

**Review by feloy — APPROVED** [review]

**Comment by feloy** [comment]
/override windows-integration-test/Windows-test
Flaky e2e test
