### PR TITLE
Fixing #1160: Fixing error message user creating application without project

### LINKED ISSUE #1160: misleading  error message if there is no project
[kind/bug]

## What versions of software are you using?
- Operating System:
- Output of `odo version`:

## How did you run odo exactly?

when there is no project
```
odo create redhat-openjdk18-openshift:1.4
```

## Actual behavior
```
unable to get current application
```

## Expected behavior
show a message about no existing project or automatically creating one

### PR DESCRIPTION
**Pull request by mohammedzee1000**
## What is the purpose of this change? What does it change?

If user does not have an active project or is using project 'default',
then error message appropriately tells user to create or set a new
project.

'default' project is not recommended anyway as its fallback project for
any non-assigned project case and user may not have permissions for same

## Was the change discussed in an issue?
fixes #1160 

## How to test changes?
Login to openshift cluster without an active project or 'default' project set as active project and do

`odo create redhat-openjdk18-openshift:1.4` or any other command that attempts to create or delete anything other than a project

Expected output : 

```
# No current project
could not get current project.  Please create or set a project
    odo project create|set <project_name>
# 'default' is set as current project
current project is 'default'. Please create or set a different project
    odo project create|set <project_name>
```
Signed-off-by: Mohammed Zeeshan Ahmed <mohammed.zee1000@gmail.com>

### CODE REVIEW

**Comment by metacosm** [comment]
You need to update the e2e login test since it will now fail if there is project.

**Comment by mohammedzee1000** [comment]
Actually, if you look at https://travis-ci.org/redhat-developer/odo/jobs/487363141#L654-L657, the root cause is it failed to create the test project because current project was set to default. I actually need to alter the check that i wrote for context to specifically allow `odo project create blah` or `odo project set blah` which is essentially what i want the user to do in these cases, create or set a different project

**Comment by mohammedzee1000** [comment]
@metacosm this should be fixed now, by allowing all project subcommands only to be used if project is 'default'. 

The point here is default project is fallback for user without any project and as such user should not do anything to it, rather creating or setting his own project.

**Comment by amitkrout** [comment]
@mohammedzee1000 Would you please add a proper scenario in the pr description area or in a new comment with few expected terminal output. This way probably we can find some potential integration test scenario.

File: pkg/odo/genericclioptions/context.go [hunk 1]
```diff
@@ -74,8 +72,36 @@ func newContext(command *cobra.Command, createAppIfNeeded bool) *Context {
...
+			}
+		}
+		// If 'default' project set
+		if ns == "default" {
+			// If user directly tries to create or delete anything other than a project, stop him, with correct error message
+			if command.HasParent() && command.Parent().Name() != "project" && (command.Name() == "create" || command.Name() == "delete") {
+				errFormat := "current project is 'default' and is read only. Please create or set a different project\n\t%s project create|set <project_name>"
+				err := fmt.Errorf(errFormat, command.Root().Name())
+				util.LogErrorAndExit(err, "")
+			} else {
```
Comment (golangcibot) [inline pkg/odo/genericclioptions/context.go]: empty branch (from `staticcheck`)

**Comment by mohammedzee1000** [comment]
> @mohammedzee1000 Would you please add a proper scenario in the pr description area or in a new comment with few expected terminal output. This way probably we can find some potential integration test scenario.

@amitkrout Updated expected output to description

File: pkg/odo/genericclioptions/context.go (hunk 1 above)
Comment (mohammedzee1000) [reply pkg/odo/genericclioptions/context.go]: addressed

**Comment by amitkrout** [comment]
> Updated expected output to description

@mohammedzee1000 If possible can you add these user specific scenario in the integration test file

**Comment by mohammedzee1000** [comment]
> > Updated expected output to description
> 
> @mohammedzee1000 If possible can you add these user specific scenario in the integration test file

@amitkrout do you mean add tests for this output. I am not sure we have separate integration tests per se here though

**Comment by amitkrout** [comment]
> I am not sure we have separate integration tests per se here though

@mohammedzee1000 Not necessarily in a separate file. You can add this to login test file in a separate scenario.

File: tests/e2e/login_test.go [hunk 2]
```diff
@@ -77,6 +68,34 @@ var _ = Describe("odoLoginE2e", func() {
 				Expect(session).To(ContainSubstring(loginTestUser))
 			})
 
+			It("Should fail login on invalid token with appropriate message", func() {
```
Comment (amitkrout) [inline tests/e2e/login_test.go]: +1

File: tests/e2e/login_test.go [hunk 3]
```diff
@@ -77,6 +68,34 @@ var _ = Describe("odoLoginE2e", func() {
...
+				for _, p := range projects {
+					if len(p) > 0 {
+						waitOut = waitForCmdOut(fmt.Sprintf("%s %s", baseOdoProjectDelete, p), 15, func(out string) bool {
+							return strings.Contains(out, fmt.Sprintf("Deleted project : %s", p))
+						})
+						Expect(waitOut).To(BeTrue())
+					}
+				}
+				// A short delay to ensure proper cleanup
+				// This ensures no more projects remain
```
Comment (amitkrout) [inline tests/e2e/login_test.go]: +1, Code comments are really helpful

File: tests/e2e/login_test.go [hunk 4]
```diff
@@ -88,10 +107,15 @@ var _ = Describe("odoLoginE2e", func() {
...
-			It("Should fail login on invalid token with appropriate message", func() {
-				session = runFailCmd(testUserLoginFailCommandWithToken, 1)
-				Expect(session).To(ContainSubstring("The token provided is invalid or expired"))
+			It("Should login successfully with token single project with appropriate message", func() {
 				runCmd(testUserLoginCommand)
+				runCmd(testUserCreateProject1Command)
+				runCmd(backToCurrentUserCommand)
+				session = runCmd(testUserLoginCommandWithToken)
+				Expect(session).To(ContainSubstring("Logged into"))
+				Expect(session).To(ContainSubstring(odoTestProject1))
```
Comment (amitkrout) [inline tests/e2e/login_test.go]: Looks OK, But could be better if line no 115 and 116 combined to a single line.

File: pkg/odo/genericclioptions/context.go [hunk 5]
```diff
@@ -74,8 +81,27 @@ func newContext(command *cobra.Command, createAppIfNeeded bool) *Context {
...
 		// otherwise use the current project
 		ns = project.GetCurrent(client)
+		// if no current project, then check if user is trying to create or delete something other than project
+		if len(ns) <= 0 {
+			errFormat := "could not get current project.  Please create or set a project\n\t%s project create|set <project_name>"
+			checkProjectCreateOrDeleteOnlyOnInvalidNamespace(command, errFormat)
+		}
+		// If 'default' project set then check if user is trying to create or delete something other than project
+		if ns == "default" {
+			errFormat := "Current project is default, which is read only.  Please create or set different project\n\t%s project create|set <project_name>"
```
Comment (cdrage) [inline pkg/odo/genericclioptions/context.go]: Should be `read-only`.

A bit of an odd message, `default` for my cluster isn't read only?

Comment (cdrage) [reply pkg/odo/genericclioptions/context.go]: `Please create or set a different project`.

Also the next section is a bit odd... It has a new-line and tab which is unconventional to our other log messages?

Comment (mohammedzee1000) [reply pkg/odo/genericclioptions/context.go]: > Should be `read-only`.
> 
> A bit of an odd message, `default` for my cluster isn't read only?

It is technically not read only, and i will go ahead and remove that bit, but default project is set when any user does not have a project, and OpenShift considers you not having an active project  in a standard OpenShift environment that comes as is by default. 

Its an edge case, so its simply safer to prevent user from doing things in 'default' project which:
- could potentially be manipulated by multiple users, without having knowledge about it (Tom may find his component deleted by Jerry, though he does not remember allowing Jerry access to the project, while Jerry is complaining how did he get a project that has some random component he did not ask for)

Comment (mohammedzee1000) [reply pkg/odo/genericclioptions/context.go]: > `Please create or set a different project`.
> 
> Also the next section is a bit odd... It has a new-line and tab which is unconventional to our other log messages?

could you please point me to a sample where a command is recommended to be run, after the error message so that I can update accordingly. Currently I am just following pattern of OpenShift messaging

File: pkg/odo/genericclioptions/context.go [hunk 6]
```diff
@@ -74,8 +81,27 @@ func newContext(command *cobra.Command, createAppIfNeeded bool) *Context {
 	} else {
 		// otherwise use the current project
 		ns = project.GetCurrent(client)
+		// if no current project, then check if user is trying to create or delete something other than project
+		if len(ns) <= 0 {
+			errFormat := "could not get current project.  Please create or set a project\n\t%s project create|set <project_name>"
```
Comment (cdrage) [inline pkg/odo/genericclioptions/context.go]: `Could` isn't capitalized

Comment (cdrage) [reply pkg/odo/genericclioptions/context.go]: There is an extra space after your first sentence.

File: pkg/odo/genericclioptions/context.go [hunk 7]
```diff
@@ -74,8 +81,27 @@ func newContext(command *cobra.Command, createAppIfNeeded bool) *Context {
...
+			checkProjectCreateOrDeleteOnlyOnInvalidNamespace(command, errFormat)
+		}
+		// If 'default' project set then check if user is trying to create or delete something other than project
+		if ns == "default" {
+			errFormat := "Current project is default.  Please create or set a different project\n\t%s project create|set <project_name>"
```
Comment (cdrage) [inline pkg/odo/genericclioptions/context.go]: There is an extra space after your first sentence.

File: pkg/odo/genericclioptions/context.go (hunk 6 above)
Comment (mohammedzee1000) [reply pkg/odo/genericclioptions/context.go]: Addressed

File: pkg/odo/genericclioptions/context.go (hunk 5 above)
Comment (mohammedzee1000) [reply pkg/odo/genericclioptions/context.go]: Addressed

File: pkg/odo/genericclioptions/context.go (hunk 7 above)
Comment (mohammedzee1000) [reply pkg/odo/genericclioptions/context.go]: Addressed

**Comment by cdrage** [comment]
@mohammedzee1000 I'm unable to replicate the changes:

```sh
github.com/redhat-developer/odo  pr_1241 ✔                                                                                                                                                                                                                                8h6m  ⍉
▶ ./odo project
The current project is: myproject

github.com/redhat-developer/odo  pr_1241 ✔                                                                                                                                                                                                                                 8h6m
▶ ./odo project delete myproject
Are you sure you want to delete project myproject? [y/N]: y
 ✓  Deleting project myproject
Deleted project : myproject
You are not a member of any projects. You can request a project to be created using the `odo project create <project_name>` command

github.com/redhat-developer/odo  pr_1241 ✔                                                                                                                                                                                                                                 8h6m
▶ ./odo create nodejs
 ✗  unable to get current application
```

**Comment by mohammedzee1000** [comment]
> @mohammedzee1000 I'm unable to replicate the changes:
> 
> ```shell
> github.com/redhat-developer/odo  pr_1241 ✔                                                                                                                                                                                                                                8h6m  ⍉
> ▶ ./odo project
> The current project is: myproject
> 
> github.com/redhat-developer/odo  pr_1241 ✔                                                                                                                                                                                                                                 8h6m
> ▶ ./odo project delete myproject
> Are you sure you want to delete project myproject? [y/N]: y
>  ✓  Deleting project myproject
> Deleted project : myproject
> You are not a member of any projects. You can request a project to be created using the `odo project create <project_name>` command
> 
> github.com/redhat-developer/odo  pr_1241 ✔                                                                                                                                                                                                                                 8h6m
> ▶ ./odo create nodejs
>  ✗  unable to get current application
> ```

This is a different issue where current project is not being unset after deleted

```
$ ./odo project
Debug : project is  default
The current project is: default

$ ./odo project create test
Debug : project is  default
 ✓  New project created and now using project : test

$ ./odo create nodejs
Debug : project is  default
 ✗  Current project is default. Please create or set a different project
	odo project create|set <project_name>

$ ./odo create nodejs      
Debug : project is  test
 ✓  Checking component
 ✓  Checking component version
 ✓  Initializing 'odo-nodejs-mqzt' component
 ✓  Creating component odo-nodejs-mqzt
 ✓  Component 'odo-nodejs-mqzt' was created and port 8080/TCP was opened
 ✓  Component 'odo-nodejs-mqzt' is now set as active component
To push source code to the component run 'odo push'

This may take few moments to be ready

$ ./odo project delete test
Debug : project is  test
? Are you sure you want to delete project test Yes
 ✓  Deleting project test
Deleted project : test
You are not a member of any projects. You can request a project to be created using the `odo project create <project_name>` command

$ ./odo project
Debug : project is  test
The current project is: test

$ oc project   
error: you do not have rights to view project "test".


```

The fix for this should happen during project deletion, so long as that happens, this works as expected

**Comment by mohammedzee1000** [comment]
> e2e test for this would be really useful

Added

**Comment by mohammedzee1000** [comment]
Output :
```
$  odo create nodejs
 ✗  You dont have permission to project 'default' or it doesnt exist. Please create or set a different project
	odo project create|set <project_name>

$ odo project create test
 ✓  New project created and now using project : test

$  odo create nodejs      
 ✓  Checking component
 ✓  Checking component version
 ✓  Initializing 'odo-nodejs-uvni' component
 ✓  Creating component odo-nodejs-uvni
 ✓  Component 'odo-nodejs-uvni' was created and port 8080/TCP was opened
 ✓  Component 'odo-nodejs-uvni' is now set as active component
To push source code to the component run 'odo push'

This may take few moments to be ready

$ odo project delete test
? Are you sure you want to delete project test Yes
 ✓  Deleting project test
Deleted project : test
You are not a member of any projects. You can request a project to be created using the `odo project create <project_name>` command

$ odo project
The current project is: test

$  odo create nodejs      
 ✗  You dont have permission to project 'test' or it doesnt exist. Please create or set a different project
	odo project create|set <project_name>


```

@cdrage This should address our case as well

**Comment by mohammedzee1000** [comment]
@girishramnani PTAL

**Comment by girishramnani** [comment]
@mohammedzee1000 tests are failing

**Comment by mohammedzee1000** [comment]
Java tests failing?

File: tests/e2e/e2e.go [hunk 8]
```diff
@@ -183,20 +184,28 @@ func pollNonRetCmdStdOutForString(cmdStr string, timeout time.Duration, check fu
 	}
 }
 
+func odoCreateProject(projectName string) {
+	runCmdShouldPass("odo project create " + projectName)
+	waitForCmdOut("odo project set "+projectName, 4, false, func(output string) bool {
+		if strings.Contains(output, "Already on project : "+projectName) {
```
Comment (golangcibot) [inline tests/e2e/e2e.go]: S1008: should use 'return <expr>' instead of 'if <expr> { return <bool> }; return <bool>' (from `gosimple`)

Comment (mohammedzee1000) [reply tests/e2e/e2e.go]: Addressed

File: tests/e2e/app_test.go [hunk 9]
```diff
@@ -0,0 +1,52 @@
...
+import (
+	"fmt"
+
+	. "github.com/onsi/ginkgo"
+	. "github.com/onsi/gomega"
+)
+
+var _ = Describe("odoAppE2e", func() {
+	// user related constants
+	const loginTestUserApplicationWithoutProject1 = "odoappwithoutprojectuser1"
```
Comment (amitkrout) [inline tests/e2e/app_test.go]: Cannot you use ```odoappwithoutprojectuser1, ...``` directly in the scenario itself instead of assigning it to a ```const``` variable and using the same ```const``` variable multiple times.

File: tests/e2e/e2e.go [hunk 10]
```diff
@@ -183,20 +184,25 @@ func pollNonRetCmdStdOutForString(cmdStr string, timeout time.Duration, check fu
 	}
 }
 
+func odoCreateProject(projectName string) {
```
Comment (amitkrout) [inline tests/e2e/e2e.go]: Please remove this function to ```util.go```. Also feel free to move those function to ```util.go``` which are not using directly ginkgo package

Comment (mohammedzee1000) [reply tests/e2e/e2e.go]: Moved

**Comment by mohammedzee1000** [comment]
> Looks OK to me but this PR ended being quite complex with changes unrelated to the core change…
@metacosm Yes i do agree, but its mostly the login stuff that is unrelated.

The creation of the `odoCreateProject` was needed though as this change means that if project is not set in time before next operation, it can result in failure. 
Note, after doing 
$ `odo project create <project>`
Even though, create says it has been set, it may not yet have been completely set by the api for a couple of milliseconds, resulting in project.Exists(), used for giving correct message, to returns false, causing the failure in tests as they do next operation too quickly (race condition)

**Comment by mohammedzee1000** [comment]
@metacosm

**Comment by amitkrout** [comment]
@mohammedzee1000 Can you please have a look why e2e_test file is failing in ```ci/circleci```

**Comment by mohammedzee1000** [comment]
> @mohammedzee1000 Can you please have a look why e2e_test file is failing in `ci/circleci`

ah project names cannot have caps. Fixed.
@amitkrout should go green now, anything else?
