### PR TITLE
Fix infinite loop in e2e tests

### LINKED ISSUE #368: Infinite loop in e2e
There is a for loop that can run forever in e2e tests

https://github.com/redhat-developer/odo/blob/master/tests/e2e/e2e_test.go#L219

### PR DESCRIPTION
**Pull request by ashetty1**
Fixes #368

### CODE REVIEW

File: tests/e2e/e2e_test.go [hunk 1]
```diff
@@ -73,6 +73,29 @@ func pingSvc(url string) {
...
+		case <-pingTimeout:
+			Fail("timeout out after 5 minutes")
+
+		case <-tick:
+			out, err := exec.Command("/bin/sh", "-c", cmd).Output()
+			if err != nil {
+				Fail(err.Error())
+			}
+
+			outInt, _ := strconv.Atoi(string(out))
```
Comment (kadel) [inline tests/e2e/e2e_test.go]: why are we converting the output to int?

File: tests/e2e/e2e_test.go [hunk 2]
```diff
@@ -73,6 +73,29 @@ func pingSvc(url string) {
...
+			if outInt > 0 {
```
Comment (kadel) [inline tests/e2e/e2e_test.go]: what happens when `outInt` is 0 or less?

File: tests/e2e/e2e_test.go (hunk 1 above)
Comment (ashetty1) [reply tests/e2e/e2e_test.go]: @kadel I need the output in int since I am doing `wc -l` comparison

File: tests/e2e/e2e_test.go (hunk 2 above)
Comment (ashetty1) [reply tests/e2e/e2e_test.go]: @kadel continues in the loop for 5 minutes

File: tests/e2e/e2e_test.go (hunk 1 above)
Comment (kadel) [reply tests/e2e/e2e_test.go]: then we need a different name for this function. It is really specific one command, and it won't work for anything that is not ending with `wc`

Comment (kadel) [reply tests/e2e/e2e_test.go]: :+1: that looks better. 
It might be good to change function name `pingCmd` doesn't really indicate what this function does. 
Also, don't forget to add a comment with a description what this function is for.

File: tests/e2e/e2e_test.go [hunk 3]
```diff
@@ -73,6 +73,29 @@ func pingSvc(url string) {
...
 }
 
+func pingCmd(cmd string) bool {
+	pingTimeout := time.After(5 * time.Minute)
+	tick := time.Tick(time.Second)
+
+	for {
+		select {
+		case <-pingTimeout:
+			Fail("timeout out after 5 minutes")
```
Comment (kadel) [inline tests/e2e/e2e_test.go]: Shouldn't be this timeout shorter? 5mins is really long time.
How about 1min? Is there a chance that after 1min the command will succeed?

Comment (ashetty1) [reply tests/e2e/e2e_test.go]: Sure.  Have changed it to 1min for now. ALso, have changed the function name to `waitForCmdOut`

File: tests/e2e/e2e_test.go [hunk 4]
```diff
@@ -73,6 +73,35 @@ func pingSvc(url string) {
 	}
 }
 
+func waitForCmdOut(cmd string, expOut string) bool {
+	// This function runs the command until it \
```
Comment (kadel) [inline tests/e2e/e2e_test.go]: The comment should be before the function.
Check this out https://blog.golang.org/godoc-documenting-go-code

**Comment by ashetty1** [comment]
@kadel hope this works.
