### PR TITLE
Make odo dev work if no endpoint is defined

### LINKED ISSUE #6460: odo dev fails with no port to forward
/kind bug

```
Johnathan Kupferer (https://kubernetes.slack.com/archives/C01D6L2NUAG/p1672853000273189)
Hello! I am trying to use a devfile without any container endpoints and odo dev is failing to start with the error Failed to setup port-forwarding: you must specify at least 1 port. Is this a bug? or is there something I can do with my devfile to tell odo not to bother with setting up port forwarding?
```

```
 Deploying to the cluster in developer mode
 •  Waiting for Kubernetes resources  ...
 ⚠  Pod is Pending
 ✓  Pod is Running
 ✓  Syncing files into the container [834ms]
 ✓  Building your application in container on cluster (command: build) [951ms]
 •  Executing the application (command: run)  ...
Failed to setup port-forwarding: you must specify at least 1 port
Failed to setup port-forwarding: you must specify at least 1 port
```

## What versions of software are you using?

**Operating System:**

**Output of `odo version`:**

### PR DESCRIPTION
**Pull request by feloy**
**What type of PR is this:**

/kind bug

**What does this PR do / why we need it:**

**Which issue(s) this PR fixes:**

Fixes #6460 

**PR acceptance criteria:**

- [x] Unit test 

- [x] Integration test 

- [x] Documentation 

**How to test changes / Special notes to the reviewer:**

### CODE REVIEW

File: pkg/portForward/portForward.go [hunk 1]
```diff
@@ -67,6 +67,10 @@ func (o *PFClient) StartPortForwarding(
 
 	o.StopPortForwarding()
 
+	if len(ceMapping) == 0 {
+		return nil
```
Comment (rm3l) [inline pkg/portForward/portForward.go:71]: From the end-user standpoint, could we display some message indicating that no ports will be forwarded? Or just `klog` the information?

File: tests/integration/cmd_dev_test.go [hunk 2]
```diff
@@ -615,6 +615,42 @@ ComponentSettings:
...
+							Expect(err).ToNot(HaveOccurred())
+						})
+
+						AfterEach(func() {
+							devSession.Stop()
+							devSession.WaitEnd()
+						})
+
+						It("should have no endpoint forwarded", func() {
+							Expect(len(ports)).To(BeZero())
```
Comment (rm3l) [inline tests/integration/cmd_dev_test.go:649]: nit: I find this more readable :-)

```suggestion
							Expect(ports).To(BeEmpty())
```

**Review by rm3l — CHANGES_REQUESTED** [review]
Added a few minor comments.

**Review by rm3l — APPROVED** [review]
Thanks.
