### PR TITLE
Fixing #1278: Changing cleanup to run as needed

### LINKED ISSUE #1278: login e2e tests are incorrect / dangerous
login e2e tests currently attempt to delete all projects. This might not work and is quite dangerous if the tests are run by an unsuspecting user on a cluster with elevated rights. Moreover, it might be difficult to ensure that the state is appropriate (i.e. no projects) when the tests are launched so end to end testing of the different login scenarios might be difficult/impossible.

### PR DESCRIPTION
**Pull request by mohammedzee1000**
## What is the purpose of this change? What does it change?
See title
 - Project deletion does not happen now when it is not needed
 - Project deletion, when run only targets specific projects

## Was the change discussed in an issue?
fixes #1278 

Signed-off-by: Mohammed Zeeshan Ahmed <mohammed.zee1000@gmail.com>

### CODE REVIEW

File: tests/e2e/login_test.go [hunk 1]
```diff
@@ -17,7 +19,6 @@ var _ = Describe("odoLoginE2e", func() {
 	// Comand related constants
 	const baseOdoLoginCommand = "odo login"
 	const baseOdoProjectCreate = "odo project create"
-	const baseOdoProjectDelete = "odo project delete -f "
 	const ocWhoamiCommand = "oc whoami"
```
Comment (metacosm) [inline tests/e2e/login_test.go]: I feel the tests would read better without these constants and variables (i.e. if the commands were inlined in the code directly).

File: tests/e2e/login_test.go [hunk 2]
```diff
@@ -41,18 +42,8 @@ var _ = Describe("odoLoginE2e", func() {
...
-				var waitOut bool
-				for _, p := range projects {
-					if len(p) > 0 {
-						waitOut = waitForCmdOut(fmt.Sprintf("%s %s", baseOdoProjectDelete, p), 10, func(out string) bool {
-							return strings.Contains(out, fmt.Sprintf("Deleted project : %s", p))
-						})
-						Expect(waitOut).To(BeTrue())
-					}
-				}
 				runCmd(backToCurrentUserCommand)
```
Comment (metacosm) [inline tests/e2e/login_test.go]: What happens if no user was initially logged in? Wouldn't it be better to log the current user out? (Not sure, just asking)

Comment (mohammedzee1000) [reply tests/e2e/login_test.go]: BeforeSuite actually ensures that.  It gets current project so a user has to be logged in, with an active project Infact

File: tests/e2e/login_test.go (hunk 1 above)
Comment (mohammedzee1000) [reply tests/e2e/login_test.go]: I can remove them no problem.

I did that because the same command was being used in multiple places and it would make it easier to update the command,  should anything change.

Comment (metacosm) [reply tests/e2e/login_test.go]: Yep, I understand but I think it'd be better to be more explicit in this case… :)

File: tests/e2e/login_test.go (hunk 2 above)
Comment (metacosm) [reply tests/e2e/login_test.go]: Tests shouldn't really assume an initial state, otherwise they are not independent… but yes, it's probably better to leave the state how the tests found it so maybe, remember the previous user to be able revert to it but do a logout after that, so that the login tests can work without a user being logged in?

File: tests/e2e/login_test.go (hunk 1 above)
Comment (mohammedzee1000) [reply tests/e2e/login_test.go]: Updated locally, pushing shortly

File: tests/e2e/login_test.go (hunk 2 above)
Comment (mohammedzee1000) [reply tests/e2e/login_test.go]: Will do

File: tests/e2e/login_test.go [hunk 3]
```diff
@@ -10,89 +10,83 @@ import (
...
+				session = runCmd("oc whoami")
+				Expect(session).To(ContainSubstring(loginTestBaseUser))
 			})
 
 			It("Should fail login on invalid token with appropriate message", func() {
-				session = runFailCmd(testUserLoginFailCommandWithToken, 1)
+				session = runFailCmd("odo login -t verybadtoken", 1)
 				Expect(session).To(ContainSubstring("The token provided is invalid or expired"))
-				runCmd(testUserLoginCommand)
+				runCmd(fmt.Sprintf("oc login -t %s", testUserToken))
```
[the remark this answers is not in the document]
Comment (mohammedzee1000) [reply tests/e2e/login_test.go]: The actual tests checks for invalid login (with invalid token), and cleanup always does logout, this is to ensure a user is logged in and logout does not fail

File: tests/e2e/login_test.go [hunk 4]
```diff
@@ -59,28 +60,33 @@ var _ = Describe("odoLoginE2e", func() {
 			})
 		})
 
-		Context("Run login tests with single active project", func() {
+		Context("Run login tests with single active project with username and password", func() {
 			AfterEach(func() {
-				runCmd("oc logout")
+				cleanUpAfterProjects([]string{odoTestProjectForSingleProject1})
```
Comment (metacosm) [inline tests/e2e/login_test.go]: 👍

**Comment by mohammedzee1000** [comment]
Rebased on master

File: tests/e2e/login_test.go [hunk 5]
```diff
@@ -10,89 +10,89 @@ import (
...
-				testUserLoginCommand = fmt.Sprintf("%s -u %s -p %s", baseOdoLoginCommand, loginTestUser, loginTestUserPassword)
-				testUserCreateProject1Command = fmt.Sprintf("%s %s", baseOdoProjectCreate, odoTestProject1)
-				testUserLoginFailCommandWithToken = fmt.Sprintf("%s -t verybadtoken", baseOdoLoginCommand)
+				// Logout of current user to ensure state
+				runCmd("oc logout")
 			})
 		})
 
-		Context("Run login tests", func() {
+		Context("Run login tests with no active projects, having default is also considered as not having active project", func() {
```
Comment (geoand) [inline tests/e2e/login_test.go]: Great test name!

**Comment by mohammedzee1000** [comment]
> Looks like logging out after each test doesn't work properly… :(

Issues due to overlap of deletion are fixed and this should take care of the above failures. Waiting for CI to go green :)

File: tests/e2e/login_test.go [hunk 6]
```diff
@@ -8,91 +8,96 @@ import (
...
+				Expect(session).To(ContainSubstring("Login successful"))
+				Expect(session).To(ContainSubstring(odoTestProjectForSingleProject1))
+				session = runCmd("oc whoami")
+				Expect(session).To(ContainSubstring(loginTestUserForSingleProject1))
 			})
 		})
 	})
 })
+
+func cleanUpAfterProjects(projects []string) {
```
Comment (amitkrout) [inline tests/e2e/login_test.go]: Can you keep function ```cleanUpAfterProjects``` in e2e.go file just to make sure the consistency of the test structure.

File: tests/e2e/login_test.go [hunk 7]
```diff
@@ -8,91 +8,96 @@ import (
...
+	for _, p := range projects {
+		deleteProject(p)
+	}
+	// log back in as original user
+	runCmd(fmt.Sprintf("oc login --token %s", currentUserToken))
+}
+
+func deleteProject(project string) {
```
Comment (amitkrout) [inline tests/e2e/login_test.go]: Same as above comment

File: tests/e2e/login_test.go (hunk 6 above)
Comment (mohammedzee1000) [reply tests/e2e/login_test.go]: Done

File: tests/e2e/login_test.go (hunk 7 above)
Comment (mohammedzee1000) [reply tests/e2e/login_test.go]: Done
