### PR TITLE
[podman] show logs when command fails

### LINKED ISSUE #6434: Implement Logs for podman platform
/kind feature

## Which functionality do you think we should add?

For the moment, displaying the logs of a container running in Podman is not implemented. For example, if the build or run command fails, the logs should be displayed. For the moment, odo panics.

### PR DESCRIPTION
**Pull request by feloy**
**What type of PR is this:**

/kind feature

**What does this PR do / why we need it:**

**Which issue(s) this PR fixes:**

Fixes #6434 

**PR acceptance criteria:**

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**

### CODE REVIEW

File: pkg/podman/logs.go [hunk 1]
```diff
@@ -1,10 +1,35 @@
...
+	args := []string{"pod", "logs"}
+	if containerName != "" {
+		args = append(args, "--container", podName+"-"+containerName)
+	}
+	args = append(args, podName)
+
+	cmd := exec.Command(o.podmanCmd, args...)
+	klog.V(3).Infof("executing %v", cmd.Args)
+	// We get the commbined output as podman logs outputs logs in stdout && stderr (when kubectl outputs all logs on stdout)
+	resultBytes, err := cmd.CombinedOutput()
```
Comment (rm3l) [inline pkg/podman/logs.go:25]: I was thinking of the case where "podman pod logs" returns a lot of lines, and this might increase memory usage.
I thought Go would propose a `CombinedOutputPipe` (similar to `Std{out,err}Pipe`, but it seems it is not the case. Instead, maybe we can use the solution depicted in https://github.com/golang/go/issues/27611#issuecomment-423525751, to return both stdout and stderr pipes as an `io.ReadCloser`?

```go
out, err := cmd.StdoutPipe()
// ... handle err
cmd.Stderr = cmd.Stdout
// ...
```

**Comment by feloy** [comment]
/override windows-integration-test/Windows-test
Flaky e2e test
