### PR TITLE
Try to reload config when disconnected from the cluster

### LINKED ISSUE #5668: odo dev - improve error msg when exiting interactive mode and user was not authenticated to cluster
/kind bug
## What versions of software are you using?

**Operating System:**
MacOS

**Output of `odo version`:**
odo v2.5.0 (46387f798)

## How did you run odo exactly?

1. Connected to ocp cluster
2. Run `odo init` and selected java > WebSphere Liberty Maven project type
3. Run `odo dev`, project got deployed to cluster as expected
4. Waited for authentication to cluster to timeout or run `oc logout`
5. Exited interactive mode

## Actual behavior
This error is provided when exiting interactive mode:
```
Cancelling deployment.
This is non-preemptive operation, it will wait for other tasks to finish first

failed to delete inner loop resources: Unauthorized ✗  Unauthorized
```
## Expected behavior
The error message can be improved to include _verify authentication to cluster_

### PR DESCRIPTION
**Pull request by feloy**
**What type of PR is this:**

/kind bug

**What does this PR do / why we need it:**

1. When disconnected from the cluster and `odo dev` is interrupted with Ctrl-c, this message is displayed:
```
Error connecting to the cluster, the resources were not cleaned up.
Please log in again and cleanup the resource with `odo delete component
```

2. When disconnected from the cluster, `odo dev` tries to reload the configuration from kubeconfig file.
- If a change of namespace or cluster in the current context is detected, the configuration is not updated. The user can still update the current namespace / cluster 
- if the namespace and cluster are the same, the new configuration is loaded, and `odo dev` continues with it

```
Keyboard Commands:
[Ctrl+c] - Exit and delete resources from the cluster
     [p] - Manually apply local changes to the application on the cluster
pPushing files...

Error connecting to the cluster. Please log in again

Error updating Kubernetes config: namespace changed ("prj3" -> "prj4"), won't refresh the configuration
Error connecting to the cluster. Please log in again

[...]
 Keyboard Commands:
[Ctrl+c] - Exit and delete resources from the cluster
     [p] - Manually apply local changes to the application on the cluster
pPushing files...

Error connecting to the cluster. Please log in again

Error updating Kubernetes config: cluster changed ("api-crc-testing:6443" -> "kubernetes"), won't refresh the configuration
Error connecting to the cluster. Please log in again

Error updating Kubernetes config: cluster changed ("api-crc-testing:6443" -> "kubernetes"), won't refresh the configuration
Error connecting to the cluster. Please log in again

[...]

Error connecting to the cluster. Please log in again

Updated Kubernetes config
 •  Waiting for Kubernetes resources  ...
 ✓  Syncing files into the container [1ms]

↪ Dev mode
 Status:
 Watching for changes in the current directory /home/phmartin/Documents/tests/go

 Keyboard Commands:
[Ctrl+c] - Exit and delete resources from the cluster
     [p] - Manually apply local changes to the application on the cluster

```

**Which issue(s) this PR fixes:**
Fixes #5668 

**PR acceptance criteria:**

- [x] Unit test 

- [ ] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**

```
[terminal 1]
$ crc start
$ oc login -u developer https://api.crc.testing:6443
```

```
[terminal 2]
$ odo dev
[...]
↪ Dev mode
 Status:
 Watching for changes in the current directory /home/phmartin/Documents/tests/go

 Keyboard Commands:
[Ctrl+c] - Exit and delete resources from the cluster
     [p] - Manually apply local changes to the application on the cluster
```

```
[terminal 1]
$ oc logout
```

```
[terminal 2]
(repeat press [p] until the token is expired and error occurs)
pPushing files...

Error connecting to the cluster. Please log in again

Updated Kubernetes config
Error connecting to the cluster. Please log in again
[...]
```

```
[terminal 1]
$ oc login -u developer https://api.crc.testing:6443
```

```
[terminal 2]
Error connecting to the cluster. Please log in again

Updated Kubernetes config
 •  Waiting for Kubernetes resources  ...
 ✓  Syncing files into the container [1ms]

↪ Dev mode
 Status:
 Watching for changes in the current directory /home/phmartin/Documents/tests/go

 Keyboard Commands:
[Ctrl+c] - Exit and delete resources from the cluster
     [p] - Manually apply local changes to the application on the cluster
```

### CODE REVIEW

File: pkg/watch/watch.go [hunk 1]
```diff
@@ -484,7 +496,11 @@ func (o *WatchClient) CleanupDevResources(devfileObj parser.DevfileObj, componen
 	fmt.Fprintln(out, "Cleaning resources, please wait")
 	isInnerLoopDeployed, resources, err := o.deleteClient.ListResourcesToDeleteFromDevfile(devfileObj, "app", componentName, labels.ComponentDevMode)
 	if err != nil {
-		fmt.Fprintf(out, "failed to delete inner loop resources: %v", err)
+		if kerrors.IsUnauthorized(err) {
+			fmt.Fprintf(out, "Error connecting to the cluster, the resources were not cleaned up.\nPlease log in again and cleanup the resource with `odo delete component`\n\n")
+		} else {
```
Comment (rm3l) [inline pkg/watch/watch.go:501]: Wondering if we shouldn't display a similar message when we get a Forbidden error.

When trying to reproduce the issue (`oc logout` while a Dev session is running, then stop the Dev session after logging out), sometimes I got the following error message instead:

```
W0919 11:42:11.676741 4131044 warnings.go:70] would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "runtime" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "runtime" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "runtime" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "runtime" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")

Error connecting to the cluster. Please log in again

Updated Kubernetes config
Error connecting to the cluster. Please log in again

Error connecting to the cluster. Please log in again

Error connecting to the cluster. Please log in again

^C ✗  Dev mode interrupted by user
Cleaning resources, please wait
Failed to delete inner loop resources: deployments.apps "my-sample-go-app" is forbidden: User "system:anonymous" cannot get resource "deployments" in API group "apps" in the namespace "default"

```

Comment (feloy) [reply pkg/watch/watch.go:501]: You are right. To be consistent with the other test when DevfileWatchHandler fails, I've added a test if IsForbidden

**Review by rm3l — COMMENTED** [review]
Thanks for your work on this. LGTM feature-wise.

/approve

**Comment by feloy** [comment]
Restart Windows tests

**Comment by feloy** [comment]
Problem resolving registry.npmjs.org on cluster dedicated to Windows tests. 

Retesting

**Comment by dharmit** [comment]
@feloy I'm seeing a weird behaviour in that, when I do `odo logout`, odo manages to push the files just fine! I tried this multiple times to be sure before writing it here. It sounds/seems super absurd to me.

However, if I change the namespaces using `odo set project`, it complains about a changed namespace as well as it complains about not being able to connect to the cluster which I expected the first time around as well.

**Comment by feloy** [comment]
> @feloy I'm seeing a weird behaviour in that, when I do `odo logout`, odo manages to push the files just fine! I tried this multiple times to be sure before writing it here. It sounds/seems super absurd to me.

Could you please share the exact commands and output

> 
> However, if I change the namespaces using `odo set project`, it complains about a changed namespace as well as it complains about not being able to connect to the cluster which I expected the first time around as well.

**Comment by feloy** [comment]
> > @feloy I'm seeing a weird behaviour in that, when I do `odo logout`, odo manages to push the files just fine! I tried this multiple times to be sure before writing it here. It sounds/seems super absurd to me.
> 
> Could you please share the exact commands and output
> 

Sorry, I didn't see the video you shared.

As said in the Steps to reproduce:

```
(repeat press [p] until the token is expired and error occurs)
```

When you execute `oc logout`, the token is removed from your kubeconfig, and so next kubectl commands fail because it does not have access anymore to the token.

On the other side, `odo dev` has saved the token and will still use it until an error occurs. Errors occur only when the token is de-activated on the cluster side, which can happen long after `oc logout`.

I experimented very different duration for the token to be deactivated on the cluster, from 1 minute to ~ 10 minutes.

**Comment by dharmit** [comment]
/lgtm

Looked at 4 failed Windows jobs for this PR. A lot of failures are related to network issue:
```
npm ERR! network This is a problem related to network connectivity.
```

Hence, overriding Windows tests here because:
1. All other tests are passing
2. We need this feature in the next release.

/override windows-integration-test/Windows-test
