### PR TITLE
[#5322] Add `PROJECT_SOURCE` to the container image build command environment

### LINKED ISSUE #5322: `odo deploy`/`odo build-images` fails for docker backend
/kind bug

## What versions of software are you using?

**Operating System:** Fedora 35

**Output of `odo version`:** `main`

## How did you run odo exactly?
```sh
$ git clone https://github.com/kadel/devfile-nodejs-deploy
$ cd devfile-nodejs-deploy
$ sed -i 's/kadel/<my-quay-username>/' devfile.yaml
$ odo project create nodejs-example
$ odo create
$ odo deploy
```

## Actual behavior
```sh
$ odo deploy

Building image quay.io/dharmit_rh/devfile-nodejs-deploy:latest
"docker build" requires exactly 1 argument.
See 'docker build --help'.

Usage:  docker build [OPTIONS] PATH | URL | -

Build an image from a Dockerfile
 ✗  command execution failed: error running docker command: exit status 1

$ odo build-images

Building image quay.io/dharmit_rh/devfile-nodejs-deploy:latest
"docker build" requires exactly 1 argument.
See 'docker build --help'.

Usage:  docker build [OPTIONS] PATH | URL | -

Build an image from a Dockerfile
 ✗  error running docker command: exit status 1
```

## Expected behavior
Both commands should pass

## Any logs, error output, etc?

* The `docker build` command that's generated by odo is: `docker build -t "quay.io/dharmit_rh/devfile-nodejs-deploy:latest" -f "/home/dshah/src/devfile-nodejs-deploy/Dockerfile" ${PROJECT_SOURCE}`

* Appending above command with a `.` (period) or path to the directory containing the devfile (`devfilePath`) in the function below solves the issue. https://github.com/redhat-developer/odo/blob/b20103c9f38b8291c92aa8bfdf048455e2d6d499/pkg/devfile/image/docker_compatible.go#L46

### PR DESCRIPTION
**Pull request by rm3l**
**What type of PR is this:**
/kind bug

**What does this PR do / why we need it:**

**Which issue(s) this PR fixes:**
Fixes #5322

**PR acceptance criteria:**

- [ ] Unit test 

- [x] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**
Run the reproduction steps depicted in #5322:

```shell
$ git clone https://github.com/kadel/devfile-nodejs-deploy && cd devfile-nodejs-deploy
$ sed -i "s/tkral/<quay-username>/" devfile.yaml
$ # Force odo to use Docker for building images
$ export PODMAN_CMD=a-command-not-found-should-make-odo-use-docker 
$ # Both odo deploy and odo build-images should now be able to build the container images
$ odo deploy
$ odo build-images
```

To run the integration tests related to this issue:
```shell
ginkgo -v -focus 'using a devfile.yaml containing an Image component with a build context' tests/integration/devfile
```

### CODE REVIEW

**Comment by valaparthvi** [comment]
/approve
/override ci/prow/v4.10-integration-e2e 
IBM tests pass.

File: tests/integration/devfile/cmd_devfile_deploy_test.go [hunk 1]
```diff
@@ -138,4 +140,48 @@ var _ = Describe("odo devfile deploy command tests", func() {
 			Expect(td.Properties.CmdProperties[segment.ProjectType]).To(ContainSubstring("nodejs"))
 		})
 	})
+
+	When("using a devfile.yaml containing an Image component with a build context", func() {
```
Comment (dharmit) [inline tests/integration/devfile/cmd_devfile_deploy_test.go:144]: In my understanding, `build-image` is executed every time someone does `odo deploy`. It's just invisible to the user, and we have extracted `odo build-image` as a standalone command to provide users the ability to build images without having to leave the odo CLI.

In that case, when build-image is executed every time for deploy logic, does having the same test separately for `odo deploy` add value? I'm wondering because integration tests take a good deal of time to finish, and duplication would only cause it to take more time.

Comment (rm3l) [reply tests/integration/devfile/cmd_devfile_deploy_test.go:144]: I understand and agree with reducing the testing time whenever possible.
But as I saw in the code, the paths used by `odo build-images` and `odo deploy` seemed slightly different, even if they end up calling the same `buildPushImage` function in the `image` package.
This, to me, could justify having separate tests.
If for any reason, we have an issue with `odo deploy` no longer building images, we might want to detect it, no?
