### PR TITLE
Stop test as soon as expectation is verified

### LINKED ISSUE #6890: Failing nightly test
/kind bug

```
 [FAILED] [120.782 seconds]
odo deploy interactive command tests directory is not empty when Alizer cannot determine a Devfile based on the current source code [It] should not fail but fallback to the interactive mode
/go/src/github.com/redhat-developer/odo/tests/integration/interactive_deploy_test.go:159
```

### PR DESCRIPTION
**Pull request by feloy**
**What type of PR is this:**

/kind bug
/area testing

**What does this PR do / why we need it:**

**Which issue(s) this PR fixes:**

Fixes #6890 

**PR acceptance criteria:**

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**

### CODE REVIEW

File: tests/integration/interactive_deploy_test.go [hunk 1]
```diff
@@ -159,20 +159,8 @@ var _ = Describe("odo deploy interactive command tests", func() {
...
-					helper.SendLine(ctx, "")
-
-					helper.ExpectString(ctx, "Enter component name")
-					helper.SendLine(ctx, "my-php-app")
-
-					helper.ExpectString(ctx, "no default deploy command found in devfile")
+					ctx.StopCommand()
 				})
 
 				Expect(err).To(Not(BeNil()))
```
Comment (rm3l) [inline tests/integration/interactive_deploy_test.go:166]: I guess we also need to remove the expectations below this..

File: tests/integration/interactive_deploy_test.go [hunk 2]
```diff
@@ -159,20 +159,8 @@ var _ = Describe("odo deploy interactive command tests", func() {
 			It("should not fail but fallback to the interactive mode", func() {
```
Comment (rm3l) [inline tests/integration/interactive_deploy_test.go:159]: I just checked and it seems we have this same test with the PHP stack for `odo init`: https://github.com/redhat-developer/odo/blob/main/tests/integration/interactive_init_test.go#L655-L672. I guess those should have failed as well. Can we do the same thing there as well?

**Review by rm3l — APPROVED** [review]

**Comment by rm3l** [comment]
```
[FAILED] Timed out after 420.000s.
  Expected
      <string>:   __
       /  \__     Developing using the "hmyitr" Devfile
       \__/  \    Namespace: cmd-dev-test468jix
       /  \__/    odo version: v3.11.0
       \__/
      
      â†ª Running on the cluster in Dev mode
       â€¢  Waiting for Kubernetes resources  ...
       âš   Pod is Pending
       âš   0/3 nodes are available: 3 pod has unbound immediate PersistentVolumeClaims. preemption: 0/3 nodes are available: 3 Preemption is not helpful for scheduling.
       âš   0/3 nodes are available: 3 pod has unbound immediate PersistentVolumeClaims. preemption: 0/3 nodes are available: 3 Preemption is not helpful for scheduling.
       âš   0/3 nodes are available: 3 pod has unbound immediate PersistentVolumeClaims. preemption: 0/3 nodes are available: 3 Preemption is not helpful for scheduling.
       âš   AttachVolume.Attach failed for volume "pvc-749a3dd3-69d6-4702-b08d-cffc6d2d5122" : timed out waiting for external-attacher of vpc.block.csi.ibm.io CSI driver to attach volume r010-c4b78560-c7c1-4002-9923-297cdef71201
       âš   Unable to attach or mount volumes: unmounted volumes=[odo-projects], unattached volumes=[odo-shared-data kube-api-access-d622r odo-projects]: timed out waiting for the condition
       âš   AttachVolume.Attach failed for volume "pvc-749a3dd3-69d6-4702-b08d-cffc6d2d5122" : timed out waiting for external-attacher of vpc.block.csi.ibm.io CSI driver to attach volume r010-c4b78560-c7c1-4002-9923-297cdef71201
       âš   Unable to attach or mount volumes: unmounted volumes=[odo-projects], unattached volumes=[odo-projects odo-shared-data kube-api-access-d622r]: timed out waiting for the condition
       âš   AttachVolume.Attach failed for volume "pvc-749a3dd3-69d6-4702-b08d-cffc6d2d5122" : timed out waiting for external-attacher of vpc.block.csi.ibm.io CSI driver to attach volume r010-c4b78560-c7c1-4002-9923-297cdef71201
       âš   Unable to attach or mount volumes: unmounted volumes=[odo-projects], unattached volumes=[odo-shared-data kube-api-access-d622r odo-projects]: timed out waiting for the condition
      
  to contain substring
      <string>: [Ctrl+c] - Exit
```

Issues with volume mounting on OpenShift clusters - should not be related to the tests here, but this is something we need to investigate.

/override OpenShift-Integration-tests/OpenShift-Integration-tests
/override windows-integration-test/Windows-test
