### PR TITLE
Fix: `odo init` overwrites personalized configuration when downloading starter project

### LINKED ISSUE #6752: Add interactive integration test for personalizing configuration with `odo init`
/area testing
There are no tests at the moment testing configuration personalization while using `odo init`.

### LINKED ISSUE #6799: `odo init` overwrites personalized configuration when downloading starter project
/kind bug

## What versions of software are you using?

**Operating System:**
macOS
**Output of `odo version`:**
odo v3.10.0 (6241a6612)
## How did you run odo exactly?
1. `odo init` Run it in the interactive mode from an empty dir.
2. Personalize the configuration, add a new env var, delete an old env var, add a new port, delete an old port.
3. Select the starter project.
4. Once the command exits, check the devfile to see if the configuration was maintained.

## Actual behavior
The configuration is overwritten with the original config.

## Expected behavior
The configuration should stay as personalized by the user.

## Any logs, error output, etc?
The issue was discovered while working on https://github.com/redhat-developer/odo/issues/6752.

### PR DESCRIPTION
**Pull request by valaparthvi**
**What type of PR is this:**
/kind bug

**What does this PR do / why we need it:**

**Which issue(s) this PR fixes:**

Fixes #6799 
Fixes #6752

**PR acceptance criteria:**

- [x] Unit test 

- [ ] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**

### CODE REVIEW

File: pkg/registry/registry_test.go [hunk 1]
```diff
@@ -793,8 +795,13 @@ func TestRegistryClient_DownloadStarterProject(t *testing.T) {
...
 				kubeClient:       tt.fields.kubeClient,
 			}
-			if err := o.DownloadStarterProject(tt.args.starterProject, tt.args.decryptedToken, tt.args.contextDir, tt.args.verbose); (err != nil) != tt.wantErr {
-				t.Errorf("DownloadStarterProject() error = %v, wantErr %v", err, tt.wantErr)
+			gotContainsDevfile, gotErr := o.DownloadStarterProject(tt.args.starterProject, tt.args.decryptedToken, tt.args.contextDir, tt.args.verbose)
+			if (gotErr != nil) != tt.wantErr {
+				t.Errorf("DownloadStarterProject() error = %v, wantErr %v", gotErr, tt.wantErr)
+				return
+			}
+			if tt.wantContainsDevfile && !gotContainsDevfile {
```
Comment (rm3l) [inline pkg/registry/registry_test.go:803]: Why don't you test an exact match? Otherwise, we might not check some cases (e.g., if `tt.wantContainsDevfile` is `false`, but `gotContainsDevfile` is `true`).

```suggestion
			if tt.wantContainsDevfile != gotContainsDevfile {
```

**Review by rm3l — CHANGES_REQUESTED** [review]
LGTM. I just had one comment about the unit tests.

**Review by rm3l — APPROVED** [review]
