### PR TITLE
Fix UX inconsistency when handling commands bound to events

### LINKED ISSUE #6573: UX inconsistency when handling commands bound to events
/kind bug
/area dev

## What versions of software are you using?

**Operating System:**
Fedora 37, kernel 6.1.9-200.fc37.x86_64

**Output of `odo version`:**
odo v3.6.0 (eeda644cc)

## How did you run odo exactly?

```
$ odo init --name my-java-wildfly --devfile java-wildfly --starter microprofile-openapi
$ odo dev
```

## Actual behavior
```
$ odo dev
  __
 /  \__     Developing using the "my-java-wildfly" Devfile
 \__/  \    Namespace: default
 /  \__/    odo version: v3.6.0
 \__/

↪ Running on the cluster in Dev mode
 •  Waiting for Kubernetes resources  ...
 ✓  Added storage m2-repository to component
 ⚠  Pod is Pending
 ✓  Pod is Running
 ✓  Syncing files into the container [109ms]
 ✓  Executing copy-galleon command "cp -Rf /opt/jboss/container/wildfly/s2i/galleon/galleon-m2-repository /tmp/. && cp -Rf /opt/wildfly /tmp/." on container "wildfly" [960ms]
 ✓  Executing provision-server command "/usr/local/s2i/assemble && cp -Rf $JBOSS_HOME ." on container "wildfly" [8s]
 ✓  Executing store-config command "mkdir $STANDALONE_RESTORE && cp -f $JBOSS_HOME/standalone/configuration/standalone.xml $STANDALONE_RESTORE/standalone.xml" on container "wildfly" [47ms]
 ✓  Building your application in container (command: compile) [47s]
 ✓  Building your application in container (command: copy-artifact) [51ms]
 •  Executing the application (command: run)  ...
 -  Forwarding from 127.0.0.1:20001 -> 16686

 -  Forwarding from 127.0.0.1:20002 -> 8080
```

## Expected behavior

The following lines provide too much info, and are not consistent with how the other commands (build, run, debug) are displayed in the output.
Here we display the whole command lines, which adds a lot of unnecessary clutter.

```
 ✓  Executing copy-galleon command "cp -Rf /opt/jboss/container/wildfly/s2i/galleon/galleon-m2-repository /tmp/. && cp -Rf /opt/wildfly /tmp/." on container "wildfly" [960ms]
 ✓  Executing provision-server command "/usr/local/s2i/assemble && cp -Rf $JBOSS_HOME ." on container "wildfly" [8s]
 ✓  Executing store-config command "mkdir $STANDALONE_RESTORE && cp -f $JBOSS_HOME/standalone/configuration/standalone.xml $STANDALONE_RESTORE/standalone.xml" on container "wildfly" [47ms]
```

Maybe we could instead display something shorter like below, to have a consistent and decluttered output:
```
$ odo dev
  __
 /  \__     Developing using the "my-java-wildfly" Devfile
 \__/  \    Namespace: default
 /  \__/    odo version: v3.6.0
 \__/

↪ Running on the cluster in Dev mode
 •  Waiting for Kubernetes resources  ...
 ✓  Added storage m2-repository to component
 ⚠  Pod is Pending
 ✓  Pod is Running
 ✓  Syncing files into the container [96ms]
 ✓  Executing post-start command in container (command: copy-galleon) [835ms]
 ✓  Executing post-start command in container (command: provision-server) [8s]
 ✓  Executing post-start command in container (command: store-config) [52ms]
 ✓  Building your application in container (command: compile) [54s]
 ✓  Building your application in container (command: copy-artifact) [57ms]
 •  Executing the application (command: run)  ...
 -  Forwarding from 127.0.0.1:20001 -> 8080

 -  Forwarding from 127.0.0.1:20002 -> 16686

```

### PR DESCRIPTION
**Pull request by rm3l**
**What type of PR is this:**
/kind bug
/area UX
/area dev

**What does this PR do / why we need it:**
See https://github.com/redhat-developer/odo/issues/6573.

For the example provided in the issue description, this PR changes the `odo dev` output from:
```
 ✓  Executing copy-galleon command "cp -Rf /opt/jboss/container/wildfly/s2i/galleon/galleon-m2-repository /tmp/. && cp -Rf /opt/wildfly /tmp/." on container "wildfly" [960ms]
 ✓  Executing provision-server command "/usr/local/s2i/assemble && cp -Rf $JBOSS_HOME ." on container "wildfly" [8s]
 ✓  Executing store-config command "mkdir $STANDALONE_RESTORE && cp -f $JBOSS_HOME/standalone/configuration/standalone.xml $STANDALONE_RESTORE/standalone.xml" on container "wildfly" [47ms]
```

to

```
 ✓  Executing post-start command in container (command: copy-galleon) [835ms]
 ✓  Executing post-start command in container (command: provision-server) [8s]
 ✓  Executing post-start command in container (command: store-config) [52ms]
```

**Which issue(s) this PR fixes:**
Fixes #6573 

**PR acceptance criteria:**

- [ ] Unit test 

- [x] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**
```
$ odo init --name my-java-wildfly --devfile java-wildfly --starter microprofile-openapi
$ odo dev
```

### CODE REVIEW

File: pkg/component/exec_handler.go [hunk 1]
```diff
@@ -55,7 +55,7 @@ func (o *execHandler) ApplyOpenShift(openshift v1alpha2.Component) error {
 func (o *execHandler) Execute(command v1alpha2.Command) error {
 	msg := o.msg
 	if msg == "" {
-		msg = fmt.Sprintf("Executing %s command %q on container %q", command.Id, command.Exec.CommandLine, command.Exec.Component)
+		msg = fmt.Sprintf("Executing %s command on container %q", command.Id, command.Exec.Component)
```
Comment (anandrkskd) [inline pkg/component/exec_handler.go:58]: @rm3l just to understand better, this function is used to execute command inside the container?

Comment (rm3l) [reply pkg/component/exec_handler.go:58]: Yes, it is an implementation of a generic [`libdevfile.Handler` interface](https://github.com/redhat-developer/odo/blob/main/pkg/libdevfile/libdevfile.go#L26), used to "handle" commands defined in the Devfile that odo needs to take into account, depending on their type (`apply`, `exec`, ...).
Here it is the handler for `exec` commands, and it delegates to an `exec` client that does the job of executing the command inside the container (via again a generic platform client interface, with different implementations for Podman and K8s).

**Review by valaparthvi — APPROVED** [review]
