### PR TITLE
(odo init): Add input validation for component name

### LINKED ISSUE #5765: odo init - input validation fails, component name prompt allows invalid component name characters
/kind bug

## What versions of software are you using?

**Operating System:**
MacOS Big Sur 11.6.5

**Output of `odo version`:**
odo v3.0.0-alpha2 (f4b9d45fd)

## How did you run odo exactly?
Found while testing command injection.
**Should we add an input-validation label ?**

In an empty dir run `odo init`
at the component name prompt enter `my-go-app1;ls -las` 
the command injection won't work, however the component is created successfully named as `my-go-app1;ls -las`:
```
? Enter component name: my-go-app1;ls -las
 ✓  Downloading starter project "go-starter" [508ms]

Your new component 'my-go-app1;ls -las' is ready in the current directory.
To start editing your component, use 'odo dev' and open this folder in your favorite IDE.
Changes will be directly reflected on the cluster.
```

or `myapp-<script>alert('Injected!');</script>`

the script injection won't work, however the component is created successfully named as `myapp-<script>alert('Injected!');</script>`:
```
? Enter component name: myapp-<script>alert('Injected!');</script>
 ✓  Downloading starter project "go-starter" [4s]

Your new component 'myapp-<script>alert('Injected!');</script>' is ready in the current directory.
To start editing your component, use 'odo dev' and open this folder in your favorite IDE.
Changes will be directly reflected on the cluster.
```
Run `odo dev` 
odo can not push the component due to invalid characters in the component name.

## Actual behavior
```
-> % odo dev 
  __
 /  \__     Developing using the myapp-<script>alert('Injected!');</script> Devfile
 \__/  \    Namespace: default
 /  \__/    odo version: v3.0.0-alpha2
 \__/

↪ Deploying to the cluster in developer mode
Cleaning resources, please wait
 ✗  failed to create the component: unable to determine if component myapp-<script>alert('Injected!');</script> exists: unable to get Deployments for the selector: app.kubernetes.io/instance=myapp-<script>alert('Injected!');</script>,app.kubernetes.io/managed-by=odo,app.kubernetes.io/part-of=app,odo.dev/mode=Dev: unable to list Deployments: unable to parse requirement: values[0][app.kubernetes.io/instance]: Invalid value: "myapp-": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')

```
## Expected behavior
We must prevent the creation of components with invalid names by validating input.

### PR DESCRIPTION
**Pull request by valaparthvi**
Signed-off-by: Parthvi Vala <pvala@redhat.com>

**What type of PR is this:**
/kind bug

**What does this PR do / why we need it:**
This PR adds validation to component name input to make sure it aligns with K8s naming convention.
**Which issue(s) this PR fixes:**

Fixes #5765 

**PR acceptance criteria:**

- [ ] Unit test 

- [x] Integration test 

- [x] Documentation 

**How to test changes / Special notes to the reviewer:**
1. `odo init --devfile go --name 123`
2. `odo init` - use name `myapp-<script>alert('Injected!');</script>` or `my-go-app1;ls -las` when asked for devfile name.

Both should fail.

### CODE REVIEW

**Comment by valaparthvi** [comment]
/retest-required
Flaky unit test.

**Comment by valaparthvi** [comment]
/override  ci/prow/v4.10-integration-e2e

IBM cloud passes.

File: pkg/odo/cli/init/init.go [hunk 1]
```diff
@@ -248,7 +248,7 @@ func NewCmdInit(name, fullName string) *cobra.Command {
 	}
 	clientset.Add(initCmd, clientset.PREFERENCE, clientset.FILESYSTEM, clientset.REGISTRY, clientset.INIT)
 
-	initCmd.Flags().String(backend.FLAG_NAME, "", "name of the component to create")
+	initCmd.Flags().String(backend.FLAG_NAME, "", "name of the component to create; it should follow the RFC 1123 Label Names")
```
Comment (rm3l) [inline pkg/odo/cli/init/init.go:251]: Same comment about us requiring non-all-numeric names:

```suggestion
	initCmd.Flags().String(backend.FLAG_NAME, "", "name of the component to create; it must follow the RFC 1123 Label Name standard and not be all-numeric")
```

File: docs/website/docs/command-reference/init.md [hunk 2]
```diff
@@ -14,7 +14,7 @@ The command can be executed in two flavors, either interactive or non-interactiv
 In interactive mode, you will be guided to choose:
 - a devfile from the list of devfiles present in the registry or registries referenced (using the `odo registry` command),
 - a starter project referenced by the selected devfile,
-- a name for the component present in the devfile.
+- a name for the component present in the devfile; this name should follow the [the Kubernetes naming convention](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-label-names).
```
Comment (rm3l) [inline docs/website/docs/command-reference/init.md:17]: Besides that, we have an additional requirement: the name must not be all-numeric. Maybe you could add that as well.
To me (and as I already reported so in #5652), "123" is a valid RFC 1123 value, accepted by Kubernetes as a resource name.

```suggestion
- a name for the component present in the devfile; this name must follow the [Kubernetes naming convention](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-label-names) and not be all-numeric.
```

File: docs/website/docs/command-reference/init.md [hunk 3]
```diff
@@ -27,7 +27,7 @@ If you prefer to download a devfile from an URL or from the local filesystem, yo
 
 The `--starter` flag indicates the name of the starter project (as referenced in the selected devfile), that you want to use to start your development. To see the available starter projects for devfile stacks in the official devfile registry use its [web interface](https://registry.devfile.io/viewer) to view its content.  
 
-The required `--name` flag indicates how the component initialized by this command should be named.
+The required `--name` flag indicates how the component initialized by this command should be named. The name should follow the [the Kubernetes naming convention](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-label-names).
```
Comment (rm3l) [inline docs/website/docs/command-reference/init.md:30]: Same comment about us requiring non-all-numeric names.

```suggestion
The required `--name` flag indicates how the component initialized by this command should be named. The name must follow the [Kubernetes naming convention](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-label-names) and not be all-numeric.
```

**Review by rm3l — CHANGES_REQUESTED** [review]

File: docs/website/docs/command-reference/init.md (hunk 2 above)
Comment (rm3l) [reply docs/website/docs/command-reference/init.md:17]: The suggested change seems to have disappeared..

File: docs/website/docs/command-reference/init.md (hunk 3 above)
Comment (rm3l) [reply docs/website/docs/command-reference/init.md:30]: The suggested change seems to have disappeared..

File: pkg/odo/cli/init/init.go (hunk 1 above)
Comment (rm3l) [reply pkg/odo/cli/init/init.go:251]: The suggested change seems to have disappeared..

File: tests/integration/interactive_init_test.go [hunk 4]
```diff
@@ -64,6 +64,29 @@ var _ = Describe("odo init interactive command tests", func() {
...
 
+	It("should fail when an invalid component name is passed", func() {
+		command := []string{"odo", "init"}
+		_, err := helper.RunInteractive(command, nil, func(ctx helper.InteractiveContext) {
+
+			helper.ExpectString(ctx, "Select language")
+			helper.SendLine(ctx, "go")
+
+			helper.ExpectString(ctx, "Select project type")
+			helper.SendLine(ctx, "\n")
```
Comment (feloy) [inline tests/integration/interactive_init_test.go:75]: Please send `""` instead of `"\n"` as the newline is already handled by SendLine (see https://github.com/redhat-developer/odo/pull/6091)

File: pkg/init/init.go [hunk 5]
```diff
@@ -234,7 +234,15 @@ func (o *InitClient) PersonalizeName(devfile parser.DevfileObj, flags map[string
...
-	return backend.PersonalizeName(devfile, flags)
+	name, err := backend.PersonalizeName(devfile, flags)
+	if err != nil {
+		return "", err
+	}
+	err = dfutil.ValidateK8sResourceName("name", name)
+	if err != nil {
+		return "", err
+	}
+	return name, nil
```
Comment (feloy) [inline pkg/init/init.go:245]: Could we have an infinite loop somewhere, to repeat asking the name until the syntax is ok, instead of to quit when an error occurs?

**Review by feloy — CHANGES_REQUESTED** [review]

File: docs/website/docs/command-reference/init.md (hunk 2 above)
Comment (valaparthvi) [reply docs/website/docs/command-reference/init.md:17]: I think that's because I forgot to pull the remote changes and force pushed local changes. sorry about this.

File: pkg/init/backend/interactive.go [hunk 6]
```diff
@@ -133,8 +134,21 @@ func (o *InteractiveBackend) PersonalizeName(devfile parser.DevfileObj, flags ma
...
+	}
+	// keep asking the name until the user enters a valid name
+	for validK8sNameErr := dfutil.ValidateK8sResourceName("name", userReturnedName); validK8sNameErr != nil; {
+		log.Error(validK8sNameErr)
+		userReturnedName, err = o.askerClient.AskName(name)
+		if err != nil {
+			return "", err
+		}
+		validK8sNameErr = dfutil.ValidateK8sResourceName("name", userReturnedName)
+	}
```
Comment (feloy) [inline pkg/init/backend/interactive.go:150]: You are repeating the AskName related code, and executing `ValidateK8sResourceName` twice on every loop.

You can do something similar to:

```
for {
   userReturnedName, err = o.askerClient.AskName(name)

  validK8sNameErr = dfutil.ValidateK8sResourceName("name", userReturnedName)
  if validK8sNameErr == nil {
    break
  }
}
```

**Review by feloy — CHANGES_REQUESTED** [review]

File: pkg/init/backend/interactive.go (hunk 6 above)
Comment (valaparthvi) [reply pkg/init/backend/interactive.go:150]: >executing ValidateK8sResourceName twice on every loop

I don't think it's executed twice on every loop, but what you've suggested here looks like a better solution.

Comment (feloy) [reply pkg/init/backend/interactive.go:150]: oh yes you are right, it is called only once. But the code is still repeated

**Review by rm3l — COMMENTED** [review]
/approve

**Comment by feloy** [comment]
/override ci/prow/unit-and-validate-test
Tests pass on IBM Cloud

**Comment by feloy** [comment]
/override ci/prow/v4.10-integration-e2e
Tests pass on IBM Cloud

**Comment by feloy** [comment]
Merging manually to fix misunderstanding with GitHub

```
Required status checks "Kubernetes-Integration-Tests/Kubernetes-Integration-Tests", "OpenShift-Integration-tests/OpenShift-Integration-tests", and "Unit-Tests/Unit-Tests" were not set by the expected GitHub apps.
```
