### PR TITLE
Configurable watch

### LINKED ISSUE #639: `odo watch component-name` fails with `Op:"read", Path:"", Err:0x6` when editing file from VSCode on WIndows
Here is my `odo watch nodejs-test1 -v` output
```
c:\p\nodejs-ex>odo watch node-test1 -v
[37mDEBU[0m[0000] Trying to connect to server 10.0.0.48:8443 - %!v(MISSING)
[37mDEBU[0m[0000] Server https://10.0.0.48:8443 is up
[37mDEBU[0m[0000] isLoggedIn err:  <nil>
 output: "developer"
[37mDEBU[0m[0000] Getting BuildConfig: node-test1-a3
[37mDEBU[0m[0000] Source for component node-test1 is file://C:/p/nodejs-ex (local)
[37mDEBU[0m[0000] starting WatchAndPush, path: /p/nodejs-ex, component: node-test1
[37mDEBU[0m[0000] adding watch on path /p/nodejs-ex
[37mDEBU[0m[0000] ignoring watch for \p\nodejs-ex\.git
[37mDEBU[0m[0000] ignoring watch for \p\nodejs-ex\.git\hooks
[37mDEBU[0m[0000] ignoring watch for \p\nodejs-ex\.git\info
[37mDEBU[0m[0000] ignoring watch for \p\nodejs-ex\.git\logs
[37mDEBU[0m[0000] ignoring watch for \p\nodejs-ex\.git\logs\refs
[37mDEBU[0m[0000] ignoring watch for \p\nodejs-ex\.git\logs\refs\heads
[37mDEBU[0m[0000] ignoring watch for \p\nodejs-ex\.git\logs\refs\remotes
[37mDEBU[0m[0000] ignoring watch for \p\nodejs-ex\.git\logs\refs\remotes\origin
[37mDEBU[0m[0000] ignoring watch for \p\nodejs-ex\.git\objects
[37mDEBU[0m[0000] ignoring watch for \p\nodejs-ex\.git\objects\03
[37mDEBU[0m[0000] ignoring watch for \p\nodejs-ex\.git\objects\58
[37mDEBU[0m[0000] ignoring watch for \p\nodejs-ex\.git\objects\65
[37mDEBU[0m[0000] ignoring watch for \p\nodejs-ex\.git\objects\78
[37mDEBU[0m[0000] ignoring watch for \p\nodejs-ex\.git\objects\7f
[37mDEBU[0m[0000] ignoring watch for \p\nodejs-ex\.git\objects\81
[37mDEBU[0m[0000] ignoring watch for \p\nodejs-ex\.git\objects\88
[37mDEBU[0m[0000] ignoring watch for \p\nodejs-ex\.git\objects\a4
[37mDEBU[0m[0000] ignoring watch for \p\nodejs-ex\.git\objects\c2
[37mDEBU[0m[0000] ignoring watch for \p\nodejs-ex\.git\objects\ca
[37mDEBU[0m[0000] ignoring watch for \p\nodejs-ex\.git\objects\d4
[37mDEBU[0m[0000] ignoring watch for \p\nodejs-ex\.git\objects\ef
[37mDEBU[0m[0000] ignoring watch for \p\nodejs-ex\.git\objects\f7
[37mDEBU[0m[0000] ignoring watch for \p\nodejs-ex\.git\objects\info
[37mDEBU[0m[0000] ignoring watch for \p\nodejs-ex\.git\objects\pack
[37mDEBU[0m[0000] ignoring watch for \p\nodejs-ex\.git\refs
[37mDEBU[0m[0000] ignoring watch for \p\nodejs-ex\.git\refs\heads
[37mDEBU[0m[0000] ignoring watch for \p\nodejs-ex\.git\refs\remotes
[37mDEBU[0m[0000] ignoring watch for \p\nodejs-ex\.git\refs\remotes\origin
[37mDEBU[0m[0000] ignoring watch for \p\nodejs-ex\.git\refs\tags
[37mDEBU[0m[0000] adding watch on path \p\nodejs-ex\helm
[37mDEBU[0m[0000] adding watch on path \p\nodejs-ex\helm\nodejs
[37mDEBU[0m[0000] adding watch on path \p\nodejs-ex\helm\nodejs\templates
[37mDEBU[0m[0000] adding watch on path \p\nodejs-ex\openshift
[37mDEBU[0m[0000] adding watch on path \p\nodejs-ex\openshift\pipeline
[37mDEBU[0m[0000] adding watch on path \p\nodejs-ex\openshift\templates
[37mDEBU[0m[0000] adding watch on path \p\nodejs-ex\tests
[37mDEBU[0m[0000] adding watch on path \p\nodejs-ex\views
Waiting for something to change in /p/nodejs-ex
[37mDEBU[0m[0005] filesystem watch event: "\\p\\nodejs-ex\\.git": WRITE
[37mDEBU[0m[0005] ignoring watch for \p\nodejs-ex\.git
[37mDEBU[0m[0005] ignoring watch for \p\nodejs-ex\.git\hooks
[37mDEBU[0m[0005] ignoring watch for \p\nodejs-ex\.git\info
[37mDEBU[0m[0005] ignoring watch for \p\nodejs-ex\.git\logs
[37mDEBU[0m[0005] ignoring watch for \p\nodejs-ex\.git\logs\refs
[37mDEBU[0m[0005] ignoring watch for \p\nodejs-ex\.git\logs\refs\heads
[37mDEBU[0m[0005] ignoring watch for \p\nodejs-ex\.git\logs\refs\remotes
[37mDEBU[0m[0005] ignoring watch for \p\nodejs-ex\.git\logs\refs\remotes\origin
[37mDEBU[0m[0005] ignoring watch for \p\nodejs-ex\.git\objects
[37mDEBU[0m[0005] ignoring watch for \p\nodejs-ex\.git\objects\03
[37mDEBU[0m[0005] ignoring watch for \p\nodejs-ex\.git\objects\58
[37mDEBU[0m[0005] ignoring watch for \p\nodejs-ex\.git\objects\65
[37mDEBU[0m[0005] ignoring watch for \p\nodejs-ex\.git\objects\78
[37mDEBU[0m[0005] ignoring watch for \p\nodejs-ex\.git\objects\7f
[37mDEBU[0m[0005] ignoring watch for \p\nodejs-ex\.git\objects\81
[37mDEBU[0m[0005] ignoring watch for \p\nodejs-ex\.git\objects\88
[37mDEBU[0m[0005] ignoring watch for \p\nodejs-ex\.git\objects\a4
[37mDEBU[0m[0005] ignoring watch for \p\nodejs-ex\.git\objects\c2
[37mDEBU[0m[0005] ignoring watch for \p\nodejs-ex\.git\objects\ca
[37mDEBU[0m[0005] ignoring watch for \p\nodejs-ex\.git\objects\d4
[37mDEBU[0m[0005] ignoring watch for \p\nodejs-ex\.git\objects\ef
[37mDEBU[0m[0005] ignoring watch for \p\nodejs-ex\.git\objects\f7
[37mDEBU[0m[0005] ignoring watch for \p\nodejs-ex\.git\objects\info
[37mDEBU[0m[0005] ignoring watch for \p\nodejs-ex\.git\objects\pack
[37mDEBU[0m[0005] ignoring watch for \p\nodejs-ex\.git\refs
[37mDEBU[0m[0005] ignoring watch for \p\nodejs-ex\.git\refs\heads
[37mDEBU[0m[0005] ignoring watch for \p\nodejs-ex\.git\refs\remotes
[37mDEBU[0m[0005] ignoring watch for \p\nodejs-ex\.git\refs\remotes\origin
[37mDEBU[0m[0005] ignoring watch for \p\nodejs-ex\.git\refs\tags
[37mDEBU[0m[0005] filesystem watch event: "\\p\\nodejs-ex\\.git": WRITE
[37mDEBU[0m[0005] ignoring watch for \p\nodejs-ex\.git
[37mDEBU[0m[0005] ignoring watch for \p\nodejs-ex\.git\hooks
[37mDEBU[0m[0005] ignoring watch for \p\nodejs-ex\.git\info
[37mDEBU[0m[0005] ignoring watch for \p\nodejs-ex\.git\logs
[37mDEBU[0m[0005] ignoring watch for \p\nodejs-ex\.git\logs\refs
[37mDEBU[0m[0005] ignoring watch for \p\nodejs-ex\.git\logs\refs\heads
[37mDEBU[0m[0005] ignoring watch for \p\nodejs-ex\.git\logs\refs\remotes
[37mDEBU[0m[0005] ignoring watch for \p\nodejs-ex\.git\logs\refs\remotes\origin
[37mDEBU[0m[0005] ignoring watch for \p\nodejs-ex\.git\objects
[37mDEBU[0m[0005] ignoring watch for \p\nodejs-ex\.git\objects\03
[37mDEBU[0m[0005] ignoring watch for \p\nodejs-ex\.git\objects\58
[37mDEBU[0m[0005] ignoring watch for \p\nodejs-ex\.git\objects\65
[37mDEBU[0m[0005] ignoring watch for \p\nodejs-ex\.git\objects\78
[37mDEBU[0m[0005] ignoring watch for \p\nodejs-ex\.git\objects\7f
[37mDEBU[0m[0005] ignoring watch for \p\nodejs-ex\.git\objects\81
[37mDEBU[0m[0005] ignoring watch for \p\nodejs-ex\.git\objects\88
[37mDEBU[0m[0005] ignoring watch for \p\nodejs-ex\.git\objects\a4
[37mDEBU[0m[0005] ignoring watch for \p\nodejs-ex\.git\objects\c2
[37mDEBU[0m[0005] ignoring watch for \p\nodejs-ex\.git\objects\ca
[37mDEBU[0m[0005] ignoring watch for \p\nodejs-ex\.git\objects\d4
[37mDEBU[0m[0005] ignoring watch for \p\nodejs-ex\.git\objects\ef
[37mDEBU[0m[0005] ignoring watch for \p\nodejs-ex\.git\objects\f7
[37mDEBU[0m[0005] ignoring watch for \p\nodejs-ex\.git\objects\info
[37mDEBU[0m[0005] ignoring watch for \p\nodejs-ex\.git\objects\pack
[37mDEBU[0m[0005] ignoring watch for \p\nodejs-ex\.git\refs
[37mDEBU[0m[0005] ignoring watch for \p\nodejs-ex\.git\refs\heads
[37mDEBU[0m[0005] ignoring watch for \p\nodejs-ex\.git\refs\remotes
[37mDEBU[0m[0005] ignoring watch for \p\nodejs-ex\.git\refs\remotes\origin
[37mDEBU[0m[0005] ignoring watch for \p\nodejs-ex\.git\refs\tags
[37mDEBU[0m[0006] filesystem watch event: "\\p\\nodejs-ex\\views\\index.html": WRITE
[37mDEBU[0m[0006] adding watch on path \p\nodejs-ex\views\index.html
[37mDEBU[0m[0006] filesystem watch event: "\\p\\nodejs-ex\\views\\index.html": WRITE
[37mDEBU[0m[0006] adding watch on path \p\nodejs-ex\views\index.html
File \p\nodejs-ex\.git changed
File \p\nodejs-ex\views\index.html changed
Pushing files...
[37mDEBU[0m[0007] Copying files [\p\nodejs-ex\.git \p\nodejs-ex\views\index.html] to pod
[37mDEBU[0m[0007] Waiting for deploymentconfig=node-test1-a3 pod
[37mDEBU[0m[0007] Status of node-test1-a3-1-rxc6n pod is Running
[37mDEBU[0m[0007] Pod node-test1-a3-1-rxc6n is running.
[37mDEBU[0m[0007] Copying to pod node-test1-a3-1-rxc6n
my localpath is /p/nodejs-ex
[31mERRO[0m[0007] Error while creating tar: &os.PathError{Op:"read", Path:"\\p\\nodejs-ex\\.git", Err:0x6}
```

### LINKED ISSUE #640: Is there a way to configure `odo watch comp-name' behavior?
Would be good to be able to control:
* the frequency odo is checking for changes
* include/exclude patterns

Current implementation seems gives no control for watch:
```
odo watch -h
Watch for changes, update component on change.

Usage:
  odo watch [component name] [flags]

Examples:
  # Watch for changes in directory for current component
  odo watch

  # Watch for changes in directory for component called frontend
  odo watch frontend


Flags:
  -h, --help   help for watch

Global Flags:
      --skip-connection-check   Skip cluster check
  -v, --verbose                 Verbose output
```

### PR DESCRIPTION
**Pull request by anmolbabu**
Make odo watch command configurable

This PR makes the list of filepath patterns to be ignored
and also the watch-push delay configurable which can now be
passed as arguements to the command. It also performs the
following fixes to the watch command:

1. Ignore watch on directories and files matching the ignore paths
2. Avoid pushing changes in files and folders that match ignore paths

2 above is required in-spite of 1, because, 1 can only ignore paths
that match the ignores along with their children but not their parents.
So, the watch on parent dir still can potentially catch a change in its
immediate child which can only be ignored at the time of push.

fixes #639 #640
Signed-off-by: anmolbabu <anmolbudugutta@gmail.com>

### CODE REVIEW

**Comment by anmolbabu** [comment]
@tkral
Ref: https://github.com/redhat-developer/odo/issues/640#issuecomment-413465371
It seems as in https://github.com/mattn/go-zglob, zlogb.Glob expects the executing code to chdir to watch path and then check matches and Match does not actually seem to match */.git or even .git/ and internally relies wholly on the regexp and `*` is expected only b/w slashes...

When I tried locally it(and also filepath.Glob or even filepath.Match...) didn't seem to work well or may be I am missing something...

File: cmd/watch.go [hunk 1]
```diff
@@ -15,6 +15,11 @@ import (
 	"github.com/spf13/cobra"
 )
 
+var (
+	ignores []string
```
Comment (cdrage) [inline cmd/watch.go]: we need to change this variable elsewhere, but in english, "ignoring" is better as "ignores" is third-person.

doesn't really matter though to be honest.

File: cmd/watch.go [hunk 2]
```diff
@@ -65,12 +70,16 @@ var watchCmd = &cobra.Command{
...
+		err = component.WatchAndPush(client, componentName, applicationName, watchPath, stdout, ignores, delay)
 		checkError(err, "Error while trying to watch %s", watchPath)
 	},
 }
 
 func init() {
+	// ignore git as it can change even if no source file changed
+	// for example some plugins providing git info in PS1 doing that
+	watchCmd.Flags().StringSliceVar(&ignores, "ignores", []string{".*\\.git.*"}, "Files and/or folders to be recursively ignored for watch")
+	watchCmd.Flags().IntVar(&delay, "delay", 1, "Time in seconds between a detection of a diff in component source to the push of diff. delay=0 means changes will be pushed as soon as they are detected which can cause performance issues")
```
Comment (cdrage) [inline cmd/watch.go]: too long of description. 

Maybe `Time in seconds between a detection in code push` ?

File: pkg/component/watch.go [hunk 3]
```diff
@@ -16,6 +16,24 @@ import (
 	"github.com/pkg/errors"
 )
 
+func isIgnore(path string, patterns []string) bool {
```
Comment (cdrage) [inline pkg/component/watch.go]: need tests

File: pkg/component/watch.go [hunk 4]
```diff
@@ -16,6 +16,24 @@ import (
...
+	for _, pattern := range patterns {
+		if matched, _ := regexp.MatchString(pattern, path); matched {
+			return true
+		}
+	}
+	return false
+}
+
+func stringinSlice(str string, strSlice []string) bool {
```
Comment (cdrage) [inline pkg/component/watch.go]: need tests

File: pkg/component/watch.go [hunk 5]
```diff
@@ -39,29 +58,28 @@ func addRecursiveWatch(watcher *fsnotify.Watcher, path string, ignores []string)
...
 
+	// If path to be watched is directory, walk the directory recursively ignoring all ignores path and paths under them and accumulate list of all such(eligible) files
 	folders := []string{}
 	err = filepath.Walk(path, func(newPath string, info os.FileInfo, err error) error {
 		if err != nil {
 			return err
 		}
-
-		if info.IsDir() {
+		// If the src root is watched, automatically all files and folders under it will be watched immaterial of contents of ignores.
```
Comment (cdrage) [inline pkg/component/watch.go]: `all files and folders underneath will be watched immaterial of the ignored content`

File: pkg/component/watch.go [hunk 6]
```diff
@@ -39,29 +58,28 @@ func addRecursiveWatch(watcher *fsnotify.Watcher, path string, ignores []string)
...
+		// So, inorder to avoid the above, src root dir is not watched
```
Comment (cdrage) [inline pkg/component/watch.go]: `in order`

File: pkg/component/watch.go (hunk 4 above)
Comment (kadel) [inline pkg/component/watch.go]: should be named `stringInSlice`, also please add a comment explaining what this function does.

File: pkg/component/watch.go (hunk 3 above)
Comment (kadel) [reply pkg/component/watch.go]: please add comment explaining that this does and what arguments are

File: cmd/watch.go [hunk 7]
```diff
@@ -65,12 +70,16 @@ var watchCmd = &cobra.Command{
...
-		err = component.WatchAndPush(client, componentName, applicationName, watchPath, stdout)
+		err = component.WatchAndPush(client, componentName, applicationName, watchPath, stdout, ignores, delay)
 		checkError(err, "Error while trying to watch %s", watchPath)
 	},
 }
 
 func init() {
+	// ignore git as it can change even if no source file changed
+	// for example some plugins providing git info in PS1 doing that
+	watchCmd.Flags().StringSliceVar(&ignores, "ignores", []string{".*\\.git.*"}, "Files and/or folders to be recursively ignored for watch")
```
Comment (kadel) [inline cmd/watch.go]: It looks like current implementation only allows to ignore directories, not files.
This needs to be fixed, either it the code or this message needs to reflect what is in code.

File: pkg/component/watch.go [hunk 8]
```diff
@@ -39,29 +58,28 @@ func addRecursiveWatch(watcher *fsnotify.Watcher, path string, ignores []string)
...
+		// Watch the regular(non-dir) files whose parents are not already watched => watch on the src root dir's non-folder files
+		if parent := filepath.Dir(newPath); !stringinSlice(parent, folders) && !info.IsDir() && !isIgnore(newPath, ignores) {
 			folders = append(folders, newPath)
```
Comment (kadel) [inline pkg/component/watch.go]: this is weird. 
If I understand it correctly it adds regular files to the variable called `folders` :-(

File: cmd/watch.go (hunk 1 above)
Comment (anmolbabu) [reply cmd/watch.go]: So, may I retain it as it is ? Its also not user facing message anyway :)

File: cmd/watch.go (hunk 2 above)
Comment (anmolbabu) [reply cmd/watch.go]: Ack

File: pkg/component/watch.go (hunk 3 above)
Comment (anmolbabu) [reply pkg/component/watch.go]: Ack

File: pkg/component/watch.go (hunk 4 above)
Comment (anmolbabu) [reply pkg/component/watch.go]: Removing it in updated PR no more in use

File: pkg/component/watch.go (hunk 5 above)
Comment (anmolbabu) [reply pkg/component/watch.go]: Updated PR is expected not to have these

File: pkg/component/watch.go (hunk 6 above)
Comment (anmolbabu) [reply pkg/component/watch.go]: Updated PR is expected not to have these

File: pkg/component/watch.go (hunk 4 above)
Comment (anmolbabu) [reply pkg/component/watch.go]: Removing it in updated PR no more in use

File: pkg/component/watch.go (hunk 8 above)
Comment (anmolbabu) [reply pkg/component/watch.go]: restoring it now...
Had some misunderstanding about addwatcher it seems addwatch on a directory watches only everything immediately under it and is most essential to track any creations/deletions within a directory while only updates can be caught using watch on files...
So restored the old code with a slight change to fix https://github.com/redhat-developer/odo/issues/639

File: pkg/component/watch.go [hunk 9]
```diff
@@ -120,7 +139,11 @@ func WatchAndPush(client *occlient.Client, componentName string, applicationName
 						break
 					}
 				}
-				if !alreadyInChangedFiles {
+				matched, err := isRegExpMatch(event.Name, ignores)
```
Comment (kadel) [inline pkg/component/watch.go]: Why are we checking for ignored files here?
If the file was ignored, the watch shouldn't be added to it and there shouldn't be event for the ignored file.

File: cmd/watch.go (hunk 1 above)
Comment (cdrage) [reply cmd/watch.go]: yeah, it's fine!

File: pkg/component/watch.go (hunk 9 above)
Comment (anmolbabu) [reply pkg/component/watch.go]: @kadel Because, the watch on a directory watches every file and folder immediately(not recursive though) under it and notifies our code of the changes in them. If we remove the watch on parent directory and only watch end/leaf level files then we run the risk of not detecting new files created(which necessiates us to watch parent directories). I have noticed even with the fixes in this PR when I follow the steps under on windows, the issue is still reproducible:

1. Start watch on local source(deployed as a component)
2. Create a new file in any of the not-ignored folders

And to my suprise I just replaced maketar in our code with maketar in https://github.com/kubernetes/kubernetes/blame/master/pkg/kubectl/cmd/cp.go#L312-L320 and I didn't see the above issue even on windows for most of the watch scenarios(of local source) that I tested, none of them failed...

**Comment by anmolbabu** [comment]
@tkral Please also have a look at https://github.com/redhat-developer/odo/pull/742#issuecomment-421755073

**Comment by anmolbabu** [comment]
@tkral all comments incoporated with tests as discussed for newly added functions.

@kadel @cdrage @surajnarwade @syamgk @mik-dass Please review

**Comment by dgolovin** [comment]
@anmolbabu I've tested local build with vscode-openshift-extension and #639 is not reproducible anymore.

**Comment by anmolbabu** [comment]
> @anmolbabu I've tested local build with vscode-openshift-extension and #639 is not reproducible anymore.

@dgolovin Thanks for testing

File: pkg/component/watch.go [hunk 10]
```diff
@@ -112,6 +131,11 @@ func WatchAndPush(client *occlient.Client, componentName string, applicationName
 				changeLock.Lock()
 				glog.V(4).Infof("filesystem watch event: %s", event)
 
+				stat, err := os.Lstat(event.Name)
+				if err != nil {
+					glog.V(4).Infof("Failed getting details of the changed file %s", event.Name)
```
[the remark this answers is not in the document]
Comment (anmolbabu) [reply pkg/component/watch.go]: No ideally not to be ignored feeding it to watchError now

File: cmd/watch.go (hunk 7 above)
[the remark this answers is not in the document]
Comment (anmolbabu) [reply cmd/watch.go]: Ack

File: cmd/watch.go [hunk 11]
```diff
@@ -65,12 +70,16 @@ var watchCmd = &cobra.Command{
...
+	watchCmd.Flags().IntVar(&delay, "delay", 1, "Time in seconds between a detection in code push.delay=0 means changes will be pushed as soon as they are detected which can cause performance issues")
```
[the remark this answers is not in the document]
Comment (anmolbabu) [reply cmd/watch.go]: https://github.com/redhat-developer/odo/pull/742#discussion_r218132648

[the remark this answers is not in the document]
Comment (anmolbabu) [reply cmd/watch.go]: Ack

**Comment by anmolbabu** [comment]
> This PR might be a good opportunity to look at a way to do e2e testing for odo watch command

@kadel As we discussed previously, I have raised https://github.com/redhat-developer/odo/issues/770 to track the same

**Comment by anmolbabu** [comment]
@kadel Incorporated your comments please revisit the PR

File: pkg/component/watch.go [hunk 12]
```diff
@@ -120,8 +145,24 @@ func WatchAndPush(client *occlient.Client, componentName string, applicationName
...
+				matched, err := isRegExpMatch(event.Name, ignores)
+				if err != nil {
+					watchError = errors.Wrap(err, "unable to watch changes")
+				}
+				if !alreadyInChangedFiles && !matched {
+					// In windows, every new file created under a sub-directory of the watched directory, raises 2 events:
+					// 1. Write event for the directory under which the file was created
+					// 2. Create event for the file that was created
+					// Ignore 1 to avoid duplicate events.
+					if !(stat.IsDir() && event.Op&fsnotify.Write == fsnotify.Write) {
```
Comment (kadel) [inline pkg/component/watch.go]: how does `event.Op&fsnotify.Write == fsnotify.Write` work?

Comment (anmolbabu) [reply pkg/component/watch.go]: Not sure :)
Just followed the one from https://github.com/redhat-developer/odo/blob/master/pkg/component/watch.go#L129
Did not venture into that detail(in part because of the urgency of the PR)

**Comment by anmolbabu** [comment]
> Ignores is now working for files :-(
> 
> If I try to ignore just single file for example like this:
> `▶ odo -v 4 watch --ignores ".*\.git.*" --ignores ".*myfile"`
> 
> It simply doesn't work, any changes to myfile triggers push

Hmm is this watch on a file or watch on a directory?
If it is file, I think I know the fix but otherwise, if the watch is on folder but a change in ignored file in the folder is causing failure, its a bit weird(given there is double filtering) :(

**Comment by kadel** [comment]
> Hmm is this watch on a file or watch on a directory?

it is on file
when tested with directory it worked

**Comment by anmolbabu** [comment]
Tested on linux for nodejs-ex deployed from local source for scenarios with .git(a folder) and server.js(regular file) ignored just for testing:
* Create a file `simply.js`under watched dir nodejs-ex
* Create a folder `simply_testing` under watched dir
* create a file `simply_testing.json` under above created `simply_testing`
* delete `simply_testing.json` and `simply_testing`
* edit server.js
* edit index.html

File: cmd/watch.go [hunk 13]
```diff
@@ -65,12 +70,16 @@ var watchCmd = &cobra.Command{
...
-		err = component.WatchAndPush(client, componentName, applicationName, watchPath, stdout)
+		err = component.WatchAndPush(client, componentName, applicationName, watchPath, stdout, ignores, delay)
 		checkError(err, "Error while trying to watch %s", watchPath)
 	},
 }
 
 func init() {
+	// ignore git as it can change even if no source file changed
+	// for example some plugins providing git info in PS1 doing that
+	watchCmd.Flags().StringSliceVar(&ignores, "ignores", []string{".*\\.git.*"}, "Files and/or folders to be recursively ignored for watch can be specified as regular expressions with this flag.")
```
Comment (cdrage) [inline cmd/watch.go]: "ignores" isn't grammatically correct for English. The plural is just "ignore".

**Comment by cdrage** [comment]
This isn't working for me with these commands:

```sh
github.com/redhat-developer/odo  pr_742 ✗                                                                                                                                                                                                                             21h17m ◒  ⍉
▶ ./odo watch --ignores ".git","foobar"
Waiting for something to change in /home/wikus/seafile/files/dev/go/src/github.com/redhat-developer/odo/nodejs-ex
```

Or:

```sh
github.com/redhat-developer/odo  pr_742 ✗                                                                                                                                                                                                                             21h18m ◒  ⍉
▶ ./odo watch --ignores .git,foobar    
Waiting for something to change in /home/wikus/seafile/files/dev/go/src/github.com/redhat-developer/odo/nodejs-ex
```

When I create a new file or directory with *any* name, it doesn't trigger.

Steps to replicate:

```sh
git clone https://github.com/openshift/nodejs-ex.git
./odo create nodejs foobar --local nodejs-ex
./odo watch --ignores .git,foobar
# in a separate terminal
touch nodejs-ex/foo
touch nodejs-ex/hi
# does nothing
```

File: cmd/watch.go (hunk 13 above)
Comment (cdrage) [inline cmd/watch.go]: Could be shorter: `Files or folders to be ignored via regular expressions`

File: cmd/watch.go [hunk 14]
```diff
@@ -65,12 +70,16 @@ var watchCmd = &cobra.Command{
...
+	watchCmd.Flags().IntVar(&delay, "delay", 1, "Time in seconds between a detection of code change and push.delay=0 means changes will be pushed as soon as they are detected which can cause performance issues")
```
Comment (cdrage) [inline cmd/watch.go]: `Time in seconds between detection of code change and push` May be better as a shorter description. You also already specify an example, so no need to add `push.delay=0`

File: cmd/watch.go (hunk 13 above)
Comment (anmolbabu) [reply cmd/watch.go]: Ack

Comment (anmolbabu) [reply cmd/watch.go]: Ack

File: cmd/watch.go (hunk 14 above)
Comment (anmolbabu) [reply cmd/watch.go]: @kadel suggested https://github.com/redhat-developer/odo/pull/742#discussion_r220519154

What do you say?

**Comment by mik-dass** [comment]
This PR will work if the editor does not create any temp files e.g VI creates temp buffer files like `.swp`, `.wx` and it crashes or `ignore` fails
```
[mrinaldas@localhost odo]$ ./odo watch nodejs --ignores "tests" --ignores ".\.git." --ignores "server.js" --ignores " .server.js.swp" -v 4
I0928 17:59:07.839936    9103 occlient.go:259] Trying to connect to server 127.0.0.1:8443
I0928 17:59:07.840144    9103 occlient.go:265] Server https://127.0.0.1:8443 is up
I0928 17:59:07.851521    9103 occlient.go:242] isLoggedIn err:  <nil> 
 output: "developer"
I0928 17:59:07.851716    9103 occlient.go:1692] Getting DeploymentConfig: nodejs-app
I0928 17:59:07.860428    9103 component.go:358] Source for component nodejs is file:///home/mrinaldas/nodejs-ex (local)
I0928 17:59:07.860450    9103 watch.go:114] starting WatchAndPush, path: /home/mrinaldas/nodejs-ex, component: nodejs, ignores [tests .\.git. server.js  .server.js.swp]
I0928 17:59:07.860744    9103 watch.go:77] ignoring watch on path /home/mrinaldas/nodejs-ex/.git/branches
I0928 17:59:07.860820    9103 watch.go:77] ignoring watch on path /home/mrinaldas/nodejs-ex/.git/hooks
I0928 17:59:07.860883    9103 watch.go:77] ignoring watch on path /home/mrinaldas/nodejs-ex/.git/info
I0928 17:59:07.860936    9103 watch.go:77] ignoring watch on path /home/mrinaldas/nodejs-ex/.git/logs
I0928 17:59:07.861320    9103 watch.go:77] ignoring watch on path /home/mrinaldas/nodejs-ex/.git/objects
I0928 17:59:07.861451    9103 watch.go:77] ignoring watch on path /home/mrinaldas/nodejs-ex/.git/refs
I0928 17:59:07.862404    9103 watch.go:77] ignoring watch on path /home/mrinaldas/nodejs-ex/tests
I0928 17:59:07.862557    9103 watch.go:97] adding watch on path /home/mrinaldas/nodejs-ex
I0928 17:59:07.862634    9103 watch.go:97] adding watch on path /home/mrinaldas/nodejs-ex/.git
I0928 17:59:07.862702    9103 watch.go:97] adding watch on path /home/mrinaldas/nodejs-ex/helm
I0928 17:59:07.862746    9103 watch.go:97] adding watch on path /home/mrinaldas/nodejs-ex/helm/nodejs
I0928 17:59:07.862783    9103 watch.go:97] adding watch on path /home/mrinaldas/nodejs-ex/helm/nodejs/templates
I0928 17:59:07.862816    9103 watch.go:97] adding watch on path /home/mrinaldas/nodejs-ex/openshift
I0928 17:59:07.862857    9103 watch.go:97] adding watch on path /home/mrinaldas/nodejs-ex/openshift/pipeline
I0928 17:59:07.862895    9103 watch.go:97] adding watch on path /home/mrinaldas/nodejs-ex/openshift/templates
I0928 17:59:07.862937    9103 watch.go:97] adding watch on path /home/mrinaldas/nodejs-ex/views
Waiting for something to change in /home/mrinaldas/nodejs-ex
I0928 17:59:15.027285    9103 watch.go:138] filesystem watch event: "/home/mrinaldas/nodejs-ex/.server.js.swp": CREATE
I0928 17:59:15.027678    9103 watch.go:170] Matching /home/mrinaldas/nodejs-ex/.server.js.swp with [tests .\.git. server.js  .server.js.swp]
.matched true, err: <nil>
I0928 17:59:15.027973    9103 watch.go:138] filesystem watch event: "/home/mrinaldas/nodejs-ex/.server.js.swx": CREATE
E0928 17:59:15.028033    9103 watch.go:143] Failed getting details of the changed file /home/mrinaldas/nodejs-ex/.server.js.swx
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1013010]

goroutine 15 [running]:
github.com/redhat-developer/odo/pkg/component.WatchAndPush.func1(0xc00053e690, 0xc000441f58, 0xc000405e40, 0xc00050cb80, 0xc0004b6800, 0x4, 0x4, 0xc00050cb60, 0xc000441f70)
        /home/mrinaldas/go/src/github.com/redhat-developer/odo/pkg/component/watch.go:150 +0x990
created by github.com/redhat-developer/odo/pkg/component.WatchAndPush
        /home/mrinaldas/go/src/github.com/redhat-developer/odo/pkg/component/watch.go:133 +0x3bf
[mrinaldas@localhost odo]
```
But it works fine on VSCODE

So I guess the user will need to ignore those files manually before running the command.

**Comment by anmolbabu** [comment]
> This PR will work if the editor does not create any temp files e.g VI creates temp buffer files like `.swp`, `.wx` and it crashes or `ignore` fails
> 
> ```
> [mrinaldas@localhost odo]$ ./odo watch nodejs --ignores "tests" --ignores ".\.git." --ignores "server.js" --ignores " .server.js.swp" -v 4
> I0928 17:59:07.839936    9103 occlient.go:259] Trying to connect to server 127.0.0.1:8443
> I0928 17:59:07.840144    9103 occlient.go:265] Server https://127.0.0.1:8443 is up
> I0928 17:59:07.851521    9103 occlient.go:242] isLoggedIn err:  <nil> 
>  output: "developer"
> I0928 17:59:07.851716    9103 occlient.go:1692] Getting DeploymentConfig: nodejs-app
> I0928 17:59:07.860428    9103 component.go:358] Source for component nodejs is file:///home/mrinaldas/nodejs-ex (local)
> I0928 17:59:07.860450    9103 watch.go:114] starting WatchAndPush, path: /home/mrinaldas/nodejs-ex, component: nodejs, ignores [tests .\.git. server.js  .server.js.swp]
> I0928 17:59:07.860744    9103 watch.go:77] ignoring watch on path /home/mrinaldas/nodejs-ex/.git/branches
> I0928 17:59:07.860820    9103 watch.go:77] ignoring watch on path /home/mrinaldas/nodejs-ex/.git/hooks
> I0928 17:59:07.860883    9103 watch.go:77] ignoring watch on path /home/mrinaldas/nodejs-ex/.git/info
> I0928 17:59:07.860936    9103 watch.go:77] ignoring watch on path /home/mrinaldas/nodejs-ex/.git/logs
> I0928 17:59:07.861320    9103 watch.go:77] ignoring watch on path /home/mrinaldas/nodejs-ex/.git/objects
> I0928 17:59:07.861451    9103 watch.go:77] ignoring watch on path /home/mrinaldas/nodejs-ex/.git/refs
> I0928 17:59:07.862404    9103 watch.go:77] ignoring watch on path /home/mrinaldas/nodejs-ex/tests
> I0928 17:59:07.862557    9103 watch.go:97] adding watch on path /home/mrinaldas/nodejs-ex
> I0928 17:59:07.862634    9103 watch.go:97] adding watch on path /home/mrinaldas/nodejs-ex/.git
> I0928 17:59:07.862702    9103 watch.go:97] adding watch on path /home/mrinaldas/nodejs-ex/helm
> I0928 17:59:07.862746    9103 watch.go:97] adding watch on path /home/mrinaldas/nodejs-ex/helm/nodejs
> I0928 17:59:07.862783    9103 watch.go:97] adding watch on path /home/mrinaldas/nodejs-ex/helm/nodejs/templates
> I0928 17:59:07.862816    9103 watch.go:97] adding watch on path /home/mrinaldas/nodejs-ex/openshift
> I0928 17:59:07.862857    9103 watch.go:97] adding watch on path /home/mrinaldas/nodejs-ex/openshift/pipeline
> I0928 17:59:07.862895    9103 watch.go:97] adding watch on path /home/mrinaldas/nodejs-ex/openshift/templates
> I0928 17:59:07.862937    9103 watch.go:97] adding watch on path /home/mrinaldas/nodejs-ex/views
> Waiting for something to change in /home/mrinaldas/nodejs-ex
> I0928 17:59:15.027285    9103 watch.go:138] filesystem watch event: "/home/mrinaldas/nodejs-ex/.server.js.swp": CREATE
> I0928 17:59:15.027678    9103 watch.go:170] Matching /home/mrinaldas/nodejs-ex/.server.js.swp with [tests .\.git. server.js  .server.js.swp]
> .matched true, err: <nil>
> I0928 17:59:15.027973    9103 watch.go:138] filesystem watch event: "/home/mrinaldas/nodejs-ex/.server.js.swx": CREATE
> E0928 17:59:15.028033    9103 watch.go:143] Failed getting details of the changed file /home/mrinaldas/nodejs-ex/.server.js.swx
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1013010]
> 
> goroutine 15 [running]:
> github.com/redhat-developer/odo/pkg/component.WatchAndPush.func1(0xc00053e690, 0xc000441f58, 0xc000405e40, 0xc00050cb80, 0xc0004b6800, 0x4, 0x4, 0xc00050cb60, 0xc000441f70)
>         /home/mrinaldas/go/src/github.com/redhat-developer/odo/pkg/component/watch.go:150 +0x990
> created by github.com/redhat-developer/odo/pkg/component.WatchAndPush
>         /home/mrinaldas/go/src/github.com/redhat-developer/odo/pkg/component/watch.go:133 +0x3bf
> [mrinaldas@localhost odo]
> ```
> But it works fine on VSCODE
> 
> So I guess the user will need to ignore those files manually before running the command.

The crash is because the file is created during the change and quickly deleted soon after closing the file before even the event is handled...

**Comment by mik-dass** [comment]
> The crash is because the file is created during the change and quickly deleted soon after closing the file before even the event is handled...

Yes

File: cmd/watch.go (hunk 14 above)
Comment (cdrage) [reply cmd/watch.go]: I don't mind going with @kadel 's suggestion :+1:

**Comment by mik-dass** [comment]
@cdrage @anmol_b I have the latest (verified by git log) still not working for me on VI but for VSCODE it's working.

**Comment by mik-dass** [comment]
> @mik-dass Logged #793 for tracking the 4913 file issue I hope there is no crash or any other issue apart from the duplicate push can you confirm the same

No crash after the new changes but discovered that it pushes on gedit too. I have pasted the logs in #793 . Anyways this PR now, LGTM

**Comment by cdrage** [comment]
Yeah, we need this in for the release. Let's LGTM this to fix the Windows issue and let's set #793 as high priority.
