### PR TITLE
propagate deletes during `odo watch`

### LINKED ISSUE #988: odo watch doesn't propagate file deletions
When I'm running `odo watch` on a directory and a file gets deleted, `odo watch` should also delete that file from the pod.
Currently, it doesn't do that, instead of that it just tries to push the nonexisting file.

It means that if I deleted a file from my source code, I have to run `odo push` to make sure that remote source code is the same as the local one

### LINKED ISSUE #1099: odo watch pushes files to the wrong directory
a good way to reproduce this is with  https://github.com/openshift/nodejs-ex

```
git clone  https://github.com/openshift/nodejs-ex
odo create nodejs mynode
odo push
odo url create
odo watch
```
now  change something in views/index.html

after watch triggers, refresh you won't see your changes in the webpage

The reason is that if you check `/opt/opt-root/src/` you will see that `index.html` is there instead of `/opt/opt-root/src/views`  where it should be. Basically, it ignores where the file is and always puts it into the document root folder.

`odo push` works correctly

### PR DESCRIPTION
**Pull request by anmolbabu**
Watch fixes + propogate deletes of watched sources
  
This PR does the following:
1. fixes the use case of odo watch pushing observed changes
   from any level nested in source root directory to
   the component source root because of which, the changes
   are not reflected in the component.
2. Enables propogation of delete of watched source files/folders
3. Adds more e2e tests for watch
4. Covers newly added modules via UTs
5. Enhances openjdk sample credits 
Steps to verify this PR:
Test 1:
  a. trigger odo watch on a local source
  b. make change in a file in a nested dir in the source directory
  c. See the change is reflected in the component(perhaps via component url? :) )
Test 2:
Steps in #950
    
fixes #1099, #1054, #988, #1121, #1117
Signed-off-by: anmolbabu <anmolbudugutta@gmail.com>

### CODE REVIEW

**Comment by anmolbabu** [comment]
Verified on Nodejs and openjdk18 runtimes in the most basic use case
@geoand Can you please help me verify complex java use cases with file deletions involving oops

**Comment by anmolbabu** [comment]
ToDo(@anmolbabu )
1. Add more tests

**Comment by anmolbabu** [comment]
ToDo(@anmolbabu ):
1. Tests

**Comment by geoand** [comment]
Are we planning of adding an e2e test for this or is it going to be covered perhaps in some general watch e2e module in the future?

**Comment by anmolbabu** [comment]
> Are we planning of adding an e2e test for this or is it going to be covered perhaps in some general watch e2e module in the future?

I am assuming the latter to be the case
Cc: @amitkrout 
Or may be after @amitkrout 's PR for https://github.com/redhat-developer/odo/issues/1121

**Comment by geoand** [comment]
@anmolbabu sure thing, I will test java as well

**Comment by anmolbabu** [comment]
> @anmolbabu sure thing, I will test java as well

Thanks @geoand

**Comment by geoand** [comment]
@anmolbabu could you please rebase onto the latest master? It will help when looking at the differences in the IDE :P

**Comment by anmolbabu** [comment]
> @anmolbabu could you please rebase onto the latest master? It will help when looking at the differences in the IDE :P

@geoand Its latest master with https://github.com/redhat-developer/odo/pull/1114(so as to avoid single file watch issues during verification of this PR). I assume rebasing this PR once https://github.com/redhat-developer/odo/pull/1114 is merged will automatically remove the first commit from this PR...

**Comment by geoand** [comment]
> > @anmolbabu could you please rebase onto the latest master? It will help when looking at the differences in the IDE :P
> 
> @geoand Its latest master with #1114 as to avoid single file watch issues during verification of this PR). I assume rebasing this PR once #1114 is merged will automatically remove the first commit from this PR...

I see, thanks

**Comment by geoand** [comment]
@anmolbabu Is this labeled as `Work in Progress` because we are waiting for the integration tests?

**Comment by amitkrout** [comment]
@anmolbabu Still i am facing the hard time to write down the test though i find ```GinkGo``` framework bit similar to my previous framework ```godog``` and not that hard to write test i think. After sometime probably from next sprint onward i will be writing/verifying/reviewing test cases for sure. Now even not yet ready with the specifications file for this pr.

If integration test blocks you, i would suggest please go with some basic odo watch test to verify the pr. Later i will go for enhancement of the same integration test if needed. WDYT ? cc_ @geoand

**Comment by geoand** [comment]
> @anmolbabu Still i am facing the hard time to write down the test though i find `GinkGo` framework bit similar to my previous framework `godog` and not that hard to write test i think. After sometime probably from next sprint onward i will be writing/verifying/reviewing test cases for sure. Now even not yet ready with the specifications file for this pr.
> 
> If integration test blocks you, i would suggest please go with some basic odo watch test to verify the pr. Later i will go for enhancement of the same integration test if needed. WDYT ? cc_ @geoand

Whatever you think is best, I was just asking because I saw the label :P

**Comment by anmolbabu** [comment]
> > @anmolbabu Still i am facing the hard time to write down the test though i find `GinkGo` framework bit similar to my previous framework `godog` and not that hard to write test i think. After sometime probably from next sprint onward i will be writing/verifying/reviewing test cases for sure. Now even not yet ready with the specifications file for this pr.
> > If integration test blocks you, i would suggest please go with some basic odo watch test to verify the pr. Later i will go for enhancement of the same integration test if needed. WDYT ? cc_ @geoand
> 
> Whatever you think is best, I was just asking because I saw the label :P

@amitkrout @geoand TBH the pr is not blocked on tests but infact by the bug in https://github.com/redhat-developer/odo/issues/1054 which is attempted to be solved by https://github.com/redhat-developer/odo-supervisord-image/pull/10 ... IHonestly although we can consider this PR ready for review but I tend to feel it would be better to test this PR with even the other PR mentioned above so all runtimes can be tested and we can be sure that it works as in completely works and not partially works or even end up in some new issues later on

**Comment by anmolbabu** [comment]
To Verify locally build supervisord image https://github.com/redhat-developer/odo-supervisord-image/pull/10 in your minishift environment by doing `eval $(minishift docker-env)`
And then create different types of components, p.ush multiple times and perform watch with different kinds of changes to watched source

**Comment by girishramnani** [comment]
@anmolbabu the e2e tests are panicking due to timeout

**Comment by amitkrout** [comment]
@anmolbabu In CI ```Main e2e tests``` fails due to timeout issue and rest test fails starts here ``` ✗  Waiting for pod to start``` or similar steps. 

I am re triggering the ```Main e2e tests``` just to check if same timeout is hit else we should increase timeout to a safer spot.

**Comment by anmolbabu** [comment]
The failure in tests is because the PR expects a new version of odo-supervisord-image with https://github.com/redhat-developer/odo-supervisord-image/pull/10 merged

**Comment by amitkrout** [comment]
Main e2e tests even fails for same ``` ✗  Waiting for pod to start``` causing the timeout issue in the next scenario. This pr needs a desperate merge of redhat-developer/odo-supervisord-image#10 as mentioned above

File: Makefile [hunk 1]
```diff
@@ -133,6 +133,15 @@ else
 	go test -v github.com/redhat-developer/odo/tests/e2e --ginkgo.focus="odoLinkE2e" -ginkgo.succinct
 endif
 
+# Run link e2e tests
+.PHONY: test-watch-e2e
+test-watch-e2e:
+ifdef TIMEOUT
+	go test -v github.com/redhat-developer/odo/tests/e2e --ginkgo.focus="odoWatchE2e" -ginkgo.v -timeout $(TIMEOUT)
```
Comment (anmolbabu) [inline Makefile]: I have it ginkgo.v for the moment for debugging
It'll be replaced with succinct once tests are green

Comment (anmolbabu) [reply Makefile]: Yeah I think that would be nice

**Comment by cdrage** [comment]
@anmolbabu is this WIP? I see that tests are failing and you requesed my review on another PR that you closed, but I see no label.

**Comment by girishramnani** [comment]
The failure is due to the supervisord image PR not being merged yet
https://github.com/redhat-developer/odo-supervisord-image/pull/10

**Comment by anmolbabu** [comment]
> @anmolbabu is this WIP? I see that tests are failing and you requesed my review on another PR that you closed, but I see no label.

@cdrage https://github.com/redhat-developer/odo/pull/1125#issuecomment-449905583

**Comment by mik-dass** [comment]
I was testing with https://github.com/marekjelen/katacoda-odo-frontend and the delete seems to fail
```
[mrinaldas@localhost odo]$ ./odo push
Pushing changes to component: katacoda-odo-php-cjwz
 ✓  Waiting for pod to start
 ✓  Copying files to pod
 ✓  Building component
 ✓  Changes successfully pushed to component: katacoda-odo-php-cjwz
[mrinaldas@localhost odo]$ ./odo watch katacoda-odo-php-cjwz -v 4
I0102 16:05:40.235262    1208 occlient.go:411] Trying to connect to server 127.0.0.1:8443
I0102 16:05:40.235434    1208 occlient.go:419] Server https://127.0.0.1:8443 is up
I0102 16:05:40.242850    1208 occlient.go:340] isLoggedIn err:  <nil> 
 output: "developer"
I0102 16:05:40.243083    1208 context.go:203] Ignoring error as it usually means flag wasn't set: flag accessed but not defined: component
I0102 16:05:40.243266    1208 occlient.go:2543] Getting DeploymentConfig: katacoda-odo-php-cjwz-odo-hvxr
I0102 16:05:40.250069    1208 component.go:587] Source for component katacoda-odo-php-cjwz is file:///home/mrinaldas/katacoda-odo-frontend (local)
I0102 16:05:40.250094    1208 watch.go:157] starting WatchAndPush, path: /home/mrinaldas/katacoda-odo-frontend, component: katacoda-odo-php-cjwz, ignores [.*\.git.*]
I0102 16:05:40.250272    1208 watch.go:105] ignoring watch on path /home/mrinaldas/katacoda-odo-frontend/.git
[mrinaldas@localhost odo]$ ./odo watch katacoda-odo-php-cjwz -v 4
I0102 16:06:36.753859    2155 occlient.go:411] Trying to connect to server 127.0.0.1:8443
I0102 16:06:36.754040    2155 occlient.go:419] Server https://127.0.0.1:8443 is up
I0102 16:06:36.768108    2155 occlient.go:340] isLoggedIn err:  <nil> 
 output: "developer"
I0102 16:06:36.768425    2155 context.go:203] Ignoring error as it usually means flag wasn't set: flag accessed but not defined: component
I0102 16:06:36.768615    2155 occlient.go:2543] Getting DeploymentConfig: katacoda-odo-php-cjwz-odo-hvxr
I0102 16:06:36.777665    2155 component.go:587] Source for component katacoda-odo-php-cjwz is file:///home/mrinaldas/katacoda-odo-frontend (local)
I0102 16:06:36.777686    2155 watch.go:157] starting WatchAndPush, path: /home/mrinaldas/katacoda-odo-frontend, component: katacoda-odo-php-cjwz, ignores [.*\.git.*]
I0102 16:06:36.777854    2155 watch.go:105] ignoring watch on path /home/mrinaldas/katacoda-odo-frontend/.git
I0102 16:06:36.777905    2155 util.go:343] path /home/mrinaldas/katacoda-odo-frontend doesn't exist, skipping it
I0102 16:06:36.777913    2155 watch.go:131] adding watch on path /home/mrinaldas/katacoda-odo-frontend
Waiting for something to change in /home/mrinaldas/katacoda-odo-frontend
I0102 16:06:48.696568    2155 watch.go:190] filesystem watch event: "/home/mrinaldas/katacoda-odo-frontend/blah.json": REMOVE
I0102 16:06:48.696667    2155 watch.go:232] Matching /home/mrinaldas/katacoda-odo-frontend/blah.json with [.*\.git.*]
.matched false, err: <nil>
I0102 16:06:48.696688    2155 watch.go:246] error removing watch for /home/mrinaldas/katacoda-odo-frontend/blah.json: can't remove non-existent inotify watch for: /home/mrinaldas/katacoda-odo-frontend/blah.json
Pushing files...
I0102 16:06:49.778064    2155 watch.go:308] Copying files [] to pod
I0102 16:06:49.778087    2155 component.go:381] PushLocal: componentName: katacoda-odo-php-cjwz, applicationName: odo-hvxr, path: /home/mrinaldas/katacoda-odo-frontend, files: [], delFiles: [blah.json], isForcePush: false
I0102 16:06:49.791803    2155 occlient.go:1612] Waiting for deploymentconfig=katacoda-odo-php-cjwz-odo-hvxr pod
 •  Waiting for pod to start  ...
I0102 16:06:49.796981    2155 occlient.go:1636] Status of katacoda-odo-php-cjwz-odo-hvxr-1-jqnb5 pod is Running
 ✓  Waiting for pod to start
I0102 16:06:49.797009    2155 occlient.go:1640] Pod katacoda-odo-php-cjwz-odo-hvxr-1-jqnb5 is running.
 •  propogating deletion of files blah.json to pod  ...
I0102 16:06:49.797087    2155 occlient.go:3128] s2ipaths marked  for deletion are [/tmp/src/blah.json /opt/app-root/backup/blah.json]
 ✓  propogating deletion of files blah.json to pod
 •  Building component  ...
+ set -eo pipefail
+ '[' '!' -z /opt/app-root/src ']'
+ '[' /tmp '!=' /opt/app-root/src ']'
+ '[' -n /opt/app-root/src-backup ']'
+ '[' '!' -d /opt/app-root/src-backup ']'
+ rsync -r /tmp/src/. /opt/app-root/src-backup/
++ ls -a /tmp/src/
+ for file in '`ls -a ${ODO_S2I_SRC_BIN_PATH}/src/`'
+ '[' . '!=' . ']'
+ for file in '`ls -a ${ODO_S2I_SRC_BIN_PATH}/src/`'
+ '[' .. '!=' . ']'
+ '[' .. '!=' .. ']'
+ for file in '`ls -a ${ODO_S2I_SRC_BIN_PATH}/src/`'
+ '[' .dummy '!=' . ']'
+ '[' .dummy '!=' .. ']'
+ rm -fr /opt/app-root/src/.dummy
+ for file in '`ls -a ${ODO_S2I_SRC_BIN_PATH}/src/`'
+ '[' .git '!=' . ']'
+ '[' .git '!=' .. ']'
+ rm -fr /opt/app-root/src/.git
+ for file in '`ls -a ${ODO_S2I_SRC_BIN_PATH}/src/`'
+ '[' .gitignore '!=' . ']'
+ '[' .gitignore '!=' .. ']'
+ rm -fr /opt/app-root/src/.gitignore
+ for file in '`ls -a ${ODO_S2I_SRC_BIN_PATH}/src/`'
+ '[' LICENSE.md '!=' . ']'
+ '[' LICENSE.md '!=' .. ']'
+ rm -fr /opt/app-root/src/LICENSE.md
+ for file in '`ls -a ${ODO_S2I_SRC_BIN_PATH}/src/`'
+ '[' README.md '!=' . ']'
+ '[' README.md '!=' .. ']'
+ rm -fr /opt/app-root/src/README.md
+ for file in '`ls -a ${ODO_S2I_SRC_BIN_PATH}/src/`'
+ '[' form.php '!=' . ']'
+ '[' form.php '!=' .. ']'
+ rm -fr /opt/app-root/src/form.php
+ for file in '`ls -a ${ODO_S2I_SRC_BIN_PATH}/src/`'
+ '[' index.php '!=' . ']'
+ '[' index.php '!=' .. ']'
+ rm -fr /opt/app-root/src/index.php
+ '[' -f /tmp/.s2i/bin/assemble ']'
+ '[' -n /usr/libexec/s2i ']'
+ rm -rf /opt/app-root/src/.git
+ /usr/libexec/s2i/assemble
---> Installing application source...
=> sourcing 20-copy-config.sh ...
---> 10:36:50     Processing additional arbitrary httpd configuration provided by s2i ...
=> sourcing 00-documentroot.conf ...
=> sourcing 50-mpm-tuning.conf ...
=> sourcing 40-ssl-certs.sh ...
+ '[' '!' -z /opt/app-root/src ']'
+ '[' -n /opt/app-root/src-backup ']'
+ '[' /tmp '!=' /opt/app-root/src ']'
+ rsync -r /opt/app-root/src-backup/. /tmp/src/
+ '[' -n '' ']'
+ /var/lib/supervisord/bin/supervisord ctl stop run
run: stopped
+ /var/lib/supervisord/bin/supervisord ctl start run
run: started
 ✓  Building component
Waiting for something to change in /home/mrinaldas/katacoda-odo-frontend
```

**Comment by anmolbabu** [comment]
> I was testing with https://github.com/marekjelen/katacoda-odo-frontend and the delete seems to fail
> 
> ```
> [mrinaldas@localhost odo]$ ./odo push
> Pushing changes to component: katacoda-odo-php-cjwz
>  ✓  Waiting for pod to start
>  ✓  Copying files to pod
>  ✓  Building component
>  ✓  Changes successfully pushed to component: katacoda-odo-php-cjwz
> [mrinaldas@localhost odo]$ ./odo watch katacoda-odo-php-cjwz -v 4
> I0102 16:05:40.235262    1208 occlient.go:411] Trying to connect to server 127.0.0.1:8443
> I0102 16:05:40.235434    1208 occlient.go:419] Server https://127.0.0.1:8443 is up
> I0102 16:05:40.242850    1208 occlient.go:340] isLoggedIn err:  <nil> 
>  output: "developer"
> I0102 16:05:40.243083    1208 context.go:203] Ignoring error as it usually means flag wasn't set: flag accessed but not defined: component
> I0102 16:05:40.243266    1208 occlient.go:2543] Getting DeploymentConfig: katacoda-odo-php-cjwz-odo-hvxr
> I0102 16:05:40.250069    1208 component.go:587] Source for component katacoda-odo-php-cjwz is file:///home/mrinaldas/katacoda-odo-frontend (local)
> I0102 16:05:40.250094    1208 watch.go:157] starting WatchAndPush, path: /home/mrinaldas/katacoda-odo-frontend, component: katacoda-odo-php-cjwz, ignores [.*\.git.*]
> I0102 16:05:40.250272    1208 watch.go:105] ignoring watch on path /home/mrinaldas/katacoda-odo-frontend/.git
> [mrinaldas@localhost odo]$ ./odo watch katacoda-odo-php-cjwz -v 4
> I0102 16:06:36.753859    2155 occlient.go:411] Trying to connect to server 127.0.0.1:8443
> I0102 16:06:36.754040    2155 occlient.go:419] Server https://127.0.0.1:8443 is up
> I0102 16:06:36.768108    2155 occlient.go:340] isLoggedIn err:  <nil> 
>  output: "developer"
> I0102 16:06:36.768425    2155 context.go:203] Ignoring error as it usually means flag wasn't set: flag accessed but not defined: component
> I0102 16:06:36.768615    2155 occlient.go:2543] Getting DeploymentConfig: katacoda-odo-php-cjwz-odo-hvxr
> I0102 16:06:36.777665    2155 component.go:587] Source for component katacoda-odo-php-cjwz is file:///home/mrinaldas/katacoda-odo-frontend (local)
> I0102 16:06:36.777686    2155 watch.go:157] starting WatchAndPush, path: /home/mrinaldas/katacoda-odo-frontend, component: katacoda-odo-php-cjwz, ignores [.*\.git.*]
> I0102 16:06:36.777854    2155 watch.go:105] ignoring watch on path /home/mrinaldas/katacoda-odo-frontend/.git
> I0102 16:06:36.777905    2155 util.go:343] path /home/mrinaldas/katacoda-odo-frontend doesn't exist, skipping it
> I0102 16:06:36.777913    2155 watch.go:131] adding watch on path /home/mrinaldas/katacoda-odo-frontend
> Waiting for something to change in /home/mrinaldas/katacoda-odo-frontend
> I0102 16:06:48.696568    2155 watch.go:190] filesystem watch event: "/home/mrinaldas/katacoda-odo-frontend/blah.json": REMOVE
> I0102 16:06:48.696667    2155 watch.go:232] Matching /home/mrinaldas/katacoda-odo-frontend/blah.json with [.*\.git.*]
> .matched false, err: <nil>
> I0102 16:06:48.696688    2155 watch.go:246] error removing watch for /home/mrinaldas/katacoda-odo-frontend/blah.json: can't remove non-existent inotify watch for: /home/mrinaldas/katacoda-odo-frontend/blah.json
> Pushing files...
> I0102 16:06:49.778064    2155 watch.go:308] Copying files [] to pod
> I0102 16:06:49.778087    2155 component.go:381] PushLocal: componentName: katacoda-odo-php-cjwz, applicationName: odo-hvxr, path: /home/mrinaldas/katacoda-odo-frontend, files: [], delFiles: [blah.json], isForcePush: false
> I0102 16:06:49.791803    2155 occlient.go:1612] Waiting for deploymentconfig=katacoda-odo-php-cjwz-odo-hvxr pod
>  •  Waiting for pod to start  ...
> I0102 16:06:49.796981    2155 occlient.go:1636] Status of katacoda-odo-php-cjwz-odo-hvxr-1-jqnb5 pod is Running
>  ✓  Waiting for pod to start
> I0102 16:06:49.797009    2155 occlient.go:1640] Pod katacoda-odo-php-cjwz-odo-hvxr-1-jqnb5 is running.
>  •  propogating deletion of files blah.json to pod  ...
> I0102 16:06:49.797087    2155 occlient.go:3128] s2ipaths marked  for deletion are [/tmp/src/blah.json /opt/app-root/backup/blah.json]
>  ✓  propogating deletion of files blah.json to pod
>  •  Building component  ...
> + set -eo pipefail
> + '[' '!' -z /opt/app-root/src ']'
> + '[' /tmp '!=' /opt/app-root/src ']'
> + '[' -n /opt/app-root/src-backup ']'
> + '[' '!' -d /opt/app-root/src-backup ']'
> + rsync -r /tmp/src/. /opt/app-root/src-backup/
> ++ ls -a /tmp/src/
> + for file in '`ls -a ${ODO_S2I_SRC_BIN_PATH}/src/`'
> + '[' . '!=' . ']'
> + for file in '`ls -a ${ODO_S2I_SRC_BIN_PATH}/src/`'
> + '[' .. '!=' . ']'
> + '[' .. '!=' .. ']'
> + for file in '`ls -a ${ODO_S2I_SRC_BIN_PATH}/src/`'
> + '[' .dummy '!=' . ']'
> + '[' .dummy '!=' .. ']'
> + rm -fr /opt/app-root/src/.dummy
> + for file in '`ls -a ${ODO_S2I_SRC_BIN_PATH}/src/`'
> + '[' .git '!=' . ']'
> + '[' .git '!=' .. ']'
> + rm -fr /opt/app-root/src/.git
> + for file in '`ls -a ${ODO_S2I_SRC_BIN_PATH}/src/`'
> + '[' .gitignore '!=' . ']'
> + '[' .gitignore '!=' .. ']'
> + rm -fr /opt/app-root/src/.gitignore
> + for file in '`ls -a ${ODO_S2I_SRC_BIN_PATH}/src/`'
> + '[' LICENSE.md '!=' . ']'
> + '[' LICENSE.md '!=' .. ']'
> + rm -fr /opt/app-root/src/LICENSE.md
> + for file in '`ls -a ${ODO_S2I_SRC_BIN_PATH}/src/`'
> + '[' README.md '!=' . ']'
> + '[' README.md '!=' .. ']'
> + rm -fr /opt/app-root/src/README.md
> + for file in '`ls -a ${ODO_S2I_SRC_BIN_PATH}/src/`'
> + '[' form.php '!=' . ']'
> + '[' form.php '!=' .. ']'
> + rm -fr /opt/app-root/src/form.php
> + for file in '`ls -a ${ODO_S2I_SRC_BIN_PATH}/src/`'
> + '[' index.php '!=' . ']'
> + '[' index.php '!=' .. ']'
> + rm -fr /opt/app-root/src/index.php
> + '[' -f /tmp/.s2i/bin/assemble ']'
> + '[' -n /usr/libexec/s2i ']'
> + rm -rf /opt/app-root/src/.git
> + /usr/libexec/s2i/assemble
> ---> Installing application source...
> => sourcing 20-copy-config.sh ...
> ---> 10:36:50     Processing additional arbitrary httpd configuration provided by s2i ...
> => sourcing 00-documentroot.conf ...
> => sourcing 50-mpm-tuning.conf ...
> => sourcing 40-ssl-certs.sh ...
> + '[' '!' -z /opt/app-root/src ']'
> + '[' -n /opt/app-root/src-backup ']'
> + '[' /tmp '!=' /opt/app-root/src ']'
> + rsync -r /opt/app-root/src-backup/. /tmp/src/
> + '[' -n '' ']'
> + /var/lib/supervisord/bin/supervisord ctl stop run
> run: stopped
> + /var/lib/supervisord/bin/supervisord ctl start run
> run: started
>  ✓  Building component
> Waiting for something to change in /home/mrinaldas/katacoda-odo-frontend
> ```

@mik-dass Done fixed...
Can you re-check once

**Comment by anmolbabu** [comment]
@kadel Incorporated comments please review

**Comment by mik-dass** [comment]
The deletion works now but found another problem with the message
Steps to reproduce
1. Start watch and create a file with some name
2. Delete it and let it build
3. Repeat step 1 and 2 multiple times

The `propogating deletetion of files` messages include names of previously deleted files. It's appending the new names with the older ones.
```
Waiting for something to change in /home/mrinaldas/katacoda-odo-frontend
Pushing files...
 ✓  Waiting for pod to start
 ✓  propogating deletion of files blha.json blah.json blah.json to pod
 ✓  Building component
```

**Comment by geoand** [comment]
I tested this with the java image builder and deletion works for nested files as well.

I also see the same problem with the names that @mik-dass mentioned.

Furthermore the tests seems to be failing (even after I restarted them in Travis)

**Comment by anmolbabu** [comment]
@geoand @mik-dass Now fixed it please revisit the PR

**Comment by anmolbabu** [comment]
But I think the only other problem now that I can think of is:
When watch is used with delay > time for noticebale multiple combinations of creates and/or updates with deletes to same files in which case the order will be unpredictable... To resolve this timestamp of change needs to be maintained along with captured file change and changes need to be propagated file-by-file in the order of associated timestamp which needs a bit more change and I think that I'll pick it up in a different PR 

Cc: @kadel @cdrage @geoand @metacosm @surajnarwade @syamgk @mik-dass @girishramnani @amitkrout  would that be ok?

**Comment by geoand** [comment]
> But I think the only other problem now that I can think of is:
> When watch is used with delay > time for noticebale multiple combinations of creates and/or updates with deletes to same files in which case the order will be unpredictable... To resolve this timestamp of change needs to be maintained along with captured file change and changes need to be propagated file-by-file in the order of associated timestamp which needs a bit more change and I think that I'll pick it up in a different PR

I might be understanding the problem incorrectly, but don't we only want to propagate the last state of the file - regardless of the what events caused it?

**Comment by geoand** [comment]
@anmolbabu I tried the latest version of the PR using [this](https://github.com/redhat-developer/odo/tree/master/tests/e2e/examples/source/openjdk) and it seems like although the delete was being picked up correctly, the removal did not get propagated.

I did: `rm src/main/java/Application.java` but when I look at filesystem on the container I see `rm src/main/java/Application.java` is still there (and the application compiles although it shouldn't).
Am I missing something?

**Comment by anmolbabu** [comment]
> > But I think the only other problem now that I can think of is:
> > When watch is used with delay > time for noticebale multiple combinations of creates and/or updates with deletes to same files in which case the order will be unpredictable... To resolve this timestamp of change needs to be maintained along with captured file change and changes need to be propagated file-by-file in the order of associated timestamp which needs a bit more change and I think that I'll pick it up in a different PR
> 
> I might be understanding the problem incorrectly, but don't we only want to propagate the last state of the file - regardless of the what events caused it?

@geoand Yes that is correct but we try to achieve that by updating the files with diff(creates, updates, deletes) as and when we get events for the same. But, if the changes are not applied in-order then the net-state will be unpredictable and this happens when `--delay` is passed with a higher value

**Comment by geoand** [comment]
> > > But I think the only other problem now that I can think of is:
> > > When watch is used with delay > time for noticebale multiple combinations of creates and/or updates with deletes to same files in which case the order will be unpredictable... To resolve this timestamp of change needs to be maintained along with captured file change and changes need to be propagated file-by-file in the order of associated timestamp which needs a bit more change and I think that I'll pick it up in a different PR
> > 
> > 
> > I might be understanding the problem incorrectly, but don't we only want to propagate the last state of the file - regardless of the what events caused it?
> 
> @geoand Yes that is correct but we try to achieve that by updating the files with diff(creates, updates, deletes) as and when we get events for the same(vs equivalent of `odo push`). But, if the changes are not applied in-order then the net-state will be unpredictable and this happens when `--delay` is passed with a higher value

Thanks for the explanation. 
I admit I haven't looked into watch much, but it seems a little odd to me that we try to recreate the state from events instead of just using the latest state at the time when the code needs to be "pushed".
Of course you are correct that in case of state recreation from events, the events need to be applied in order

**Comment by anmolbabu** [comment]
> @anmolbabu This PR is supposed to fix #1099 as well, correct?

Yes @geoand

**Comment by geoand** [comment]
> > @anmolbabu This PR is supposed to fix #1099 as well, correct?
> 
> Yes @geoand



> > @anmolbabu This PR is supposed to fix #1099 as well, correct?
> 
> Yes @geoand

Cool, then maybe the title and description should be updated as well?

**Comment by geoand** [comment]
> @anmolbabu I tried the latest version of the PR using [this](https://github.com/redhat-developer/odo/tree/master/tests/e2e/examples/source/openjdk) and it seems like although the delete was being picked up correctly, the removal did not get propagated.
> 
> I did: `rm src/main/java/Application.java` but when I look at filesystem on the container I see `/tmp/src/src/main/java/Application.java` is still there (and the application compiles although it shouldn't).
> Am I missing something?

To continue with this, when I perform a simple update (instead of a delete) the very same file, the update is correctly propagated and reflected in the deployed service.
Delete however doesn't seem to be correctly propagated

**Comment by anmolbabu** [comment]
> > @anmolbabu I tried the latest version of the PR using [this](https://github.com/redhat-developer/odo/tree/master/tests/e2e/examples/source/openjdk) and it seems like although the delete was being picked up correctly, the removal did not get propagated.
> > I did: `rm src/main/java/Application.java` but when I look at filesystem on the container I see `/tmp/src/src/main/java/Application.java` is still there (and the application compiles although it shouldn't).
> > Am I missing something?
> 
> To continue with this, when I perform a simple update (instead of a delete) the very same file, the update is correctly propagated and reflected in the deployed service.
> Delete however doesn't seem to be correctly propagated

Yeah I am looking at it but doesn't seem to be the case with other runtimes :(
Anyway looking closer at it now

**Comment by anmolbabu** [comment]
> > > @anmolbabu I tried the latest version of the PR using [this](https://github.com/redhat-developer/odo/tree/master/tests/e2e/examples/source/openjdk) and it seems like although the delete was being picked up correctly, the removal did not get propagated.
> > > I did: `rm src/main/java/Application.java` but when I look at filesystem on the container I see `/tmp/src/src/main/java/Application.java` is still there (and the application compiles although it shouldn't).
> > > Am I missing something?
> > 
> > 
> > To continue with this, when I perform a simple update (instead of a delete) the very same file, the update is correctly propagated and reflected in the deployed service.
> > Delete however doesn't seem to be correctly propagated
> 
> Yeah I am looking at it but doesn't seem to be the case with other runtimes :(
> Anyway looking closer at it now

I am getting increasingly pissed off :( by these things now...
Will give it a retry may be tomorrow or on monday

**Comment by geoand** [comment]
Let me know if you need any help

File: pkg/component/component.go [hunk 2]
```diff
@@ -372,17 +421,35 @@ func PushLocal(client *occlient.Client, componentName string, applicationName st
 	}
 	targetPath := fmt.Sprintf("%s/src", s2iSrcPath)
 
+	// If there are files identified as deleted, propogate them to the component pod
+	if len(delFiles) > 0 {
+		s := log.Spinner(fmt.Sprintf("propogating deletion of files %s to pod", strings.Join(delFiles, " ")))
```
[the remark this answers is not in the document]
Comment (anmolbabu) [reply pkg/component/component.go]: Ack

File: pkg/component/component.go [hunk 3]
```diff
@@ -372,17 +421,35 @@ func PushLocal(client *occlient.Client, componentName string, applicationName st
...
-		s.End(false)
-		return errors.Wrap(err, "unable push files to pod")
+	if !isForcePush {
+		if len(files) == 0 && len(delFiles) == 0 {
+			return fmt.Errorf("pass files modifications/deletions to sync to component pod or force push")
+		}
+	}
+
+	if isForcePush || len(files) > 0 {
+		s := log.Spinner("Copying files to pod")
```
[the remark this answers is not in the document]
Comment (anmolbabu) [reply pkg/component/component.go]: Ack

File: pkg/occlient/occlient.go [hunk 4]
```diff
@@ -1278,7 +1327,7 @@ func (c *Client) UpdateDCToGit(commonObjectMeta metav1.ObjectMeta, imageName str
 }
 
 // UpdateDCToSupervisor updates the current DeploymentConfig to a SupervisorD configuration.
-func (c *Client) UpdateDCToSupervisor(commonObjectMeta metav1.ObjectMeta, componentImageType string) error {
+func (c *Client) UpdateDCToSupervisor(commonObjectMeta metav1.ObjectMeta, componentImageType string, isToLocal bool) error {
```
[the remark this answers is not in the document]
Comment (anmolbabu) [reply pkg/occlient/occlient.go]: Ack

File: pkg/occlient/occlient.go [hunk 5]
```diff
@@ -3061,3 +3113,30 @@ func (c *Client) GetEnvVarsFromDC(dcName string) ([]corev1.EnvVar, error) {
 
 	return dc.Spec.Template.Spec.Containers[0].Env, nil
 }
+
+// PropogateDeletes deletes the watch detecte deleted files from remote component pod
```
[the remark this answers is not in the document]
Comment (anmolbabu) [reply pkg/occlient/occlient.go]: Ack

File: pkg/occlient/occlient.go [hunk 6]
```diff
@@ -3061,3 +3113,30 @@ func (c *Client) GetEnvVarsFromDC(dcName string) ([]corev1.EnvVar, error) {
...
+// Parameters:
+//	targetPodName: Name of component pod
+//	delSrcRelPaths: Paths to be deleted on the remote pod
```
[the remark this answers is not in the document]
Comment (anmolbabu) [reply pkg/occlient/occlient.go]: Ack

File: pkg/component/component.go [hunk 7]
```diff
@@ -372,17 +421,36 @@ func PushLocal(client *occlient.Client, componentName string, applicationName st
 	}
 	targetPath := fmt.Sprintf("%s/src", s2iSrcPath)
 
+	// If there are files identified as deleted, propogate them to the component pod
+	if len(delFiles) > 0 {
+		s := log.Spinner("deleting files from component")
```
Comment (kadel) [inline pkg/component/component.go]: I don't think that this is a message that user should see. 
It is expected that when you delete something it will be deleted ;-)

File: pkg/occlient/occlient.go [hunk 8]
```diff
@@ -3063,3 +3121,30 @@ func (c *Client) GetEnvVarsFromDC(dcName string) ([]corev1.EnvVar, error) {
 
 	return dc.Spec.Template.Spec.Containers[0].Env, nil
 }
+
+// PropogateDeletes deletes the watch detected deleted files from remote component pod from each of the paths in passed s2iPaths
+// Parameters:
+//	targetPodName: Name of component pod
+//	delSrcRelPaths: Paths to be deleted on the remote pod relative to component source base path ex: Compoent src: /abc/src, file deleted: abc/src/foo.lang => relative path: foo.lang
+//	s2iPaths: Slice of all s2i paths -- deployment dir, destination dir, working dir, etc..
+func (c *Client) PropogateDeletes(targetPodName string, delSrcRelPaths []string, s2iPaths []string) error {
```
Comment (kadel) [inline pkg/occlient/occlient.go]: Shouldn't it "PropagateDeletes"?

File: pkg/component/component.go [hunk 9]
```diff
@@ -372,17 +421,36 @@ func PushLocal(client *occlient.Client, componentName string, applicationName st
...
+		defer s.End(false)
+		glog.V(4).Infof("propogating deletion of files %s to pod", strings.Join(delFiles, " "))
+		err := client.PropogateDeletes(pod.Name, delFiles, getS2IPaths(pod.Spec.Containers[0].Env))
```
Comment (kadel) [inline pkg/component/component.go]: It would be good to have explained somewhere why we are deleting files from multiple directories (s2ipaths)

File: pkg/occlient/occlient.go [hunk 10]
```diff
@@ -131,6 +138,12 @@ const (
 	// DefaultS2ISrcOrBinPath is the default path where S2I expects source/binary artifacts in absence of $S2ISrcOrBinLabel in builder image
 	// Ref: https://github.com/openshift/source-to-image/blob/master/docs/builder_image.md#required-image-contents
 	DefaultS2ISrcOrBinPath = "/tmp"
+
+	// DefaultS2ISrcBackupDir is the default path where odo backs up the component source
```
Comment (kadel) [inline pkg/occlient/occlient.go]: add comment why we are creating this backup

File: pkg/occlient/occlient.go [hunk 11]
```diff
@@ -910,6 +928,23 @@ func uniqueAppendOrOverwriteEnvVars(existingEnvs []corev1.EnvVar, envVars ...cor
 	return retVal
 }
 
+// deleteNonRequiredEnvVars deletes the passed env var from the list of passed env vars
+// Parameters:
+//	existingEnvs: Slice of existing env vars
+//	envTobeDeleted: The name of env var to be deleted
+// Returns:
+//	slice of env vars with delete reflected
+func deleteNonRequiredEnvVars(existingEnvs []corev1.EnvVar, envTobeDeleted string) []corev1.EnvVar {
```
Comment (kadel) [inline pkg/occlient/occlient.go]: I found this function name pretty confusing. 
It just removes one item from `EnvVar` slice, but name uses the plural "Vars", also why it is "NonRequired" when there is an argument that clearly determines what should be deleted.

Another problem is that if someone calls this function and assigns its return value to different variable than what is used as the first argument it will lead to nasty bugs :-(

```go
newEnvs := deleteNonRequiredEnvVars(originEnvs, deleteThis)
```
`newEnvs`  will have corrected output, but `originEnvs` will be also modified, and it will be somehting that you would't expect.

File: pkg/component/component.go (hunk 7 above)
Comment (anmolbabu) [reply pkg/component/component.go]: Ack

File: pkg/occlient/occlient.go (hunk 8 above)
Comment (anmolbabu) [reply pkg/occlient/occlient.go]: aah yeah will fix it :)

File: pkg/occlient/occlient.go (hunk 11 above)
Comment (anmolbabu) [reply pkg/occlient/occlient.go]: > I found this function name pretty confusing.
> It just removes one item from `EnvVar` slice, but name uses the plural "Vars", also why it is "NonRequired" when there is an argument that clearly determines what should be deleted.
> 
> Another problem is that if someone calls this function and assigns its return value to different variable than what is used as the first argument it will lead to nasty bugs :-(
> 
> ```go
> newEnvs := deleteNonRequiredEnvVars(originEnvs, deleteThis)
> ```
>

Ack 

> `newEnvs` will have corrected output, but `originEnvs` will be also modified, and it will be somehting that you would't expect.

No, not since my previous-to-previous commit anyway I amended a UT also to test this now

**Comment by anmolbabu** [comment]
@kadel I have incorporated your comments please, have a look

**Comment by anmolbabu** [comment]
@kadel Can you please revisit the PR I have incorporated your comments

File: Makefile (hunk 1 above)
Comment (amitkrout) [reply Makefile]: I was not confident about the use of tag ```-ginkgo.v``` in test debugging. Now onward i will start using the same flag as my test debugging solution.

@anmolbabu Once it solves your purpose then do not forget to replace with ```-ginkgo.succinct``` before merge ;)

**Comment by anmolbabu** [comment]
> Good to see that the overall coverage increases, however the impacted file `pkg/component/watch.go` coverage decreases [#1125 (comment)](https://github.com/redhat-developer/odo/pull/1125#issuecomment-446489440). @anmolbabu Is it somehow possible to increase the coverage of that file `pkg/component/watch.go`?

@amitkrout I guess I have covered every newly added functions with UTs and I have also increased number of e2e tests around watch. So, I guess we can take up a followup issue for covering the other already existing funcs? the PR is already big

**Comment by amitkrout** [comment]
> So, I guess we can take up a followup issue for covering the other already existing funcs? the PR is already big

+1, no worries.

File: pkg/occlient/occlient.go (hunk 11 above)
Comment (kadel) [reply pkg/occlient/occlient.go]: no, this is still an issue with this implementation

Comment (anmolbabu) [reply pkg/occlient/occlient.go]: Aah my bad :( 
Now fixed it as tried also in https://play.golang.org/p/LwcxpaSbqkv

File: pkg/component/component.go [hunk 12]
```diff
@@ -372,17 +421,40 @@ func PushLocal(client *occlient.Client, componentName string, applicationName st
 	}
 	targetPath := fmt.Sprintf("%s/src", s2iSrcPath)
 
+	// If there are files identified as deleted, propogate them to the component pod
+	if len(delFiles) > 0 {
+		glog.V(4).Infof("propogating deletion of files %s to pod", strings.Join(delFiles, " "))
+		/*
+			Delete files observed by watch to have been deleted from each of s2i directories like:
+				deployment dir: In interpreted runtimes like python, source is copied over to deployment dir so delete needs to happen here as well
```
[the remark this answers is not in the document]
Comment (anmolbabu) [reply pkg/component/component.go]: Its deleting source files so if its java, a delete is attempted but that doesn't delete anything

File: pkg/component/component.go [hunk 13]
```diff
@@ -372,17 +421,40 @@ func PushLocal(client *occlient.Client, componentName string, applicationName st
 	}
 	targetPath := fmt.Sprintf("%s/src", s2iSrcPath)
 
+	// If there are files identified as deleted, propogate them to the component pod
```
[the remark this answers is not in the document]
Comment (anmolbabu) [reply pkg/component/component.go]: Ack

File: pkg/component/component.go [hunk 14]
```diff
@@ -372,17 +421,40 @@ func PushLocal(client *occlient.Client, componentName string, applicationName st
...
+			Delete files observed by watch to have been deleted from each of s2i directories like:
+				deployment dir: In interpreted runtimes like python, source is copied over to deployment dir so delete needs to happen here as well
+				destination dir: This is the directory where s2i expects source to be copied for it be built and deployed
+				working dir: Directory where, sources are copied over from deployment dir from where the s2i builds and deploys source.
+							 Deletes need to happen here as well otherwise, even if the latest source is copied over, the stale source files remain
+				source backup dir: Directory used for backing up source across multiple iterations of push and watch in component container
+		*/
+		err := client.PropagateDeletes(pod.Name, delFiles, getS2IPaths(pod.Spec.Containers[0].Env))
+		if err != nil {
+			return errors.Wrapf(err, "unable to propogate file deletions %+v", delFiles)
```
[the remark this answers is not in the document]
Comment (anmolbabu) [reply pkg/component/component.go]: Ack

File: pkg/component/watch.go [hunk 15]
```diff
@@ -242,6 +246,14 @@ func WatchAndPush(client *occlient.Client, out io.Writer, parameters WatchParame
 					if e := watcher.Remove(event.Name); e != nil {
 						glog.V(4).Infof("error removing watch for %s: %v", event.Name, e)
 					}
+					// append the file to list of deleted files
+					if !alreadyInChangedFiles && !matched {
+						relPath, err := filepath.Rel(parameters.Path, event.Name)
+						if err != nil {
+							watchError = errors.Wrapf(err, "failed to propogate delete of file %s as its relative to %s couldn't be found", event.Name, parameters.Path)
```
[the remark this answers is not in the document]
Comment (anmolbabu) [reply pkg/component/watch.go]: Ack

File: pkg/occlient/occlient.go [hunk 16]
```diff
@@ -3063,3 +3139,30 @@ func (c *Client) GetEnvVarsFromDC(dcName string) ([]corev1.EnvVar, error) {
...
+// PropagateDeletes deletes the watch detected deleted files from remote component pod from each of the paths in passed s2iPaths
+// Parameters:
+//	targetPodName: Name of component pod
+//	delSrcRelPaths: Paths to be deleted on the remote pod relative to component source base path ex: Compoent src: /abc/src, file deleted: abc/src/foo.lang => relative path: foo.lang
+//	s2iPaths: Slice of all s2i paths -- deployment dir, destination dir, working dir, etc..
+func (c *Client) PropagateDeletes(targetPodName string, delSrcRelPaths []string, s2iPaths []string) error {
+	reader, writer := io.Pipe()
+	var rmPaths []string
+	if len(s2iPaths) == 0 || len(delSrcRelPaths) == 0 {
+		return fmt.Errorf("Failed to propogate deletions: s2iPaths: %+v and delSrcRelPaths: %+v", s2iPaths, delSrcRelPaths)
```
[the remark this answers is not in the document]
Comment (anmolbabu) [reply pkg/occlient/occlient.go]: Ack

**Comment by mik-dass** [comment]
It seems that it's not propagating the deletion of files with the latest changes
Steps to reproduce
1. Start watch
2. create a file (it gets pushed)
3. delete the file (push gets triggered) but the file remains inside the pod
```
[mrinaldas@localhost odo]$ ./odo watch -v 4
I0117 17:18:16.911927   30447 occlient.go:420] Trying to connect to server 127.0.0.1:8443
I0117 17:18:16.914913   30447 occlient.go:427] Server https://127.0.0.1:8443 is up
I0117 17:18:16.925996   30447 occlient.go:350] isLoggedIn err:  <nil> 
 output: "developer"
I0117 17:18:16.926942   30447 context.go:203] Ignoring error as it usually means flag wasn't set: flag accessed but not defined: component
I0117 17:18:16.927168   30447 watch.go:48] No component name passed, assuming current component
I0117 17:18:16.927362   30447 occlient.go:2576] Getting DeploymentConfig: katacoda-odo-php-wxaq-odo-apob
I0117 17:18:16.933761   30447 component.go:615] Source for component katacoda-odo-php-wxaq is file:///home/mrinaldas/katacoda-odo-frontend (local)
I0117 17:18:16.933813   30447 watch.go:163] starting WatchAndPush, path: /home/mrinaldas/katacoda-odo-frontend, component: katacoda-odo-php-wxaq, ignores [.git .idea *.iml]
I0117 17:18:16.933964   30447 watch.go:59] ignoring path /home/mrinaldas/katacoda-odo-frontend/.git because of glob rule .git
I0117 17:18:16.933975   30447 watch.go:117] ignoring watch on path /home/mrinaldas/katacoda-odo-frontend/.git
I0117 17:18:16.934027   30447 watch.go:137] adding watch on path /home/mrinaldas/katacoda-odo-frontend
Waiting for something to change in /home/mrinaldas/katacoda-odo-frontend
I0117 17:18:30.921196   30447 watch.go:196] filesystem watch event: "/home/mrinaldas/katacoda-odo-frontend/blah.json": RENAME
I0117 17:18:30.921346   30447 watch.go:238] Matching /home/mrinaldas/katacoda-odo-frontend/blah.json with [.git .idea *.iml]
.matched false, err: <nil>
File /home/mrinaldas/katacoda-odo-frontend/blah.json changed
Pushing files...
I0117 17:18:31.934381   30447 watch.go:317] Copying files [/home/mrinaldas/katacoda-odo-frontend/blah.json] to pod
I0117 17:18:31.934450   30447 component.go:400] PushLocal: componentName: katacoda-odo-php-wxaq, applicationName: odo-apob, path: /home/mrinaldas/katacoda-odo-frontend, files: [/home/mrinaldas/katacoda-odo-frontend/blah.json], delFiles: [], isForcePush: false
I0117 17:18:31.973701   30447 occlient.go:1644] Waiting for deploymentconfig=katacoda-odo-php-wxaq-odo-apob pod
 •  Waiting for pod to start  ...
I0117 17:18:31.993590   30447 occlient.go:1668] Status of katacoda-odo-php-wxaq-odo-apob-1-s9jwz pod is Running
 ✓  Waiting for pod to start
I0117 17:18:31.993712   30447 occlient.go:1672] Pod katacoda-odo-php-wxaq-odo-apob-1-s9jwz is running.
I0117 17:18:31.993962   30447 component.go:453] Copying files /home/mrinaldas/katacoda-odo-frontend/blah.json to pod
I0117 17:18:31.994603   30447 occlient.go:2700] makeTar arguements: srcPath: /home/mrinaldas/katacoda-odo-frontend, destPath: /tmp/src/katacoda-odo-frontend, files: [/home/mrinaldas/katacoda-odo-frontend/blah.json]
 •  Building component  ...
```
Seems like the `delFiles: []` is empty

**Comment by mik-dass** [comment]
> It seems that it's not propagating the deletion of files with the latest changes

Maybe I am not building the supervisorD image properly. Let me check once again

File: pkg/component/component.go (hunk 12 above)
[the remark this answers is not in the document]
Comment (kadel) [reply pkg/component/component.go]: ack

File: pkg/component/component.go [hunk 17]
```diff
@@ -431,10 +431,13 @@ func PushLocal(client *occlient.Client, componentName string, applicationName st
 				working dir: Directory where, sources are copied over from deployment dir from where the s2i builds and deploys source.
 							 Deletes need to happen here as well otherwise, even if the latest source is copied over, the stale source files remain
 				source backup dir: Directory used for backing up source across multiple iterations of push and watch in component container
+								   In case of python, s2i image moves sources from destination dir to workingdir which means sources are deleted from destination dir
+								   So, during the subsequent watch pushing new diff to component pod, the source as a whole doesn't exist at destination dir and hence needs
```
Comment (kadel) [inline pkg/component/component.go]: 👍

**Comment by mik-dass** [comment]
> Maybe I am not building the supervisorD image properly. Let me check once again

Seems like I messed up somewhat while building the supervisorD image. Rebuilt and deletion works fine now. Let me test the other scenarios

**Comment by surajnarwade** [comment]
Worked for me, built https://github.com/redhat-developer/odo-supervisord-image/pull/10 and tried

**Comment by cdrage** [comment]
@anmolbabu Looks like we're getting segfaults with this PR, could you check the tests?

**Comment by anmolbabu** [comment]
> @anmolbabu Looks like we're getting segfaults with this PR, could you check the tests?

I see those errors being due to non-availability of 0.0.6 supervisord-image which fails push and hence everything else... @cdrage

**Comment by anmolbabu** [comment]
@kadel @cdrage All comments incoporated Please review

**Comment by anmolbabu** [comment]
> @anmolbabu Looks like we're getting segfaults with this PR, could you check the tests?

@cdrage yeah fixed appveyor tests but failure in e2e is expected until https://github.com/redhat-developer/odo-supervisord-image/pull/10 is not merged and released

File: pkg/component/component.go [hunk 18]
```diff
@@ -372,17 +421,43 @@ func PushLocal(client *occlient.Client, componentName string, applicationName st
...
-		s.End(false)
-		return errors.Wrap(err, "unable push files to pod")
+	if !isForcePush {
+		if len(files) == 0 && len(delFiles) == 0 {
+			return fmt.Errorf("pass files modifications/deletions to sync to component pod or force push")
+		}
+	}
+
+	if isForcePush || len(files) > 0 {
+		glog.V(4).Infof("Copying files %s to pod", strings.Join(files, " "))
```
Comment (kadel) [inline pkg/component/component.go]: why was this degraded to debug message?
The user should see this message. The only issue with it is that it should say "component" instead of "pod"

Comment (anmolbabu) [reply pkg/component/component.go]: Shall I make it as Copying changes to component ? because it now includes even delete?

Comment (jorgemoralespou) [reply pkg/component/component.go]: Or you can say, "Pushing files/changes to component"

Comment (kadel) [reply pkg/component/component.go]: I think that copying is fine.

Comment (anmolbabu) [reply pkg/component/component.go]: Ack I thought it shouldn't be there...
Restoring it back

File: tests/e2e/e2e.go [hunk 19]
```diff
@@ -26,16 +26,41 @@ func runCmd(cmdS string) string {
...
+			session, _ := gexec.Start(cmd, GinkgoWriter, GinkgoWriter)
+
+			// wait for the command execution to complete
+			<-session.Exited
+			if session.ExitCode() == statusCode {
+				return true
+			}
+		}
+	}
+	return false
```
Comment (golangcibot) [inline tests/e2e/e2e.go]: unreachable code (from `govet`)

File: tests/e2e/e2e.go [hunk 20]
```diff
@@ -26,16 +26,41 @@ func runCmd(cmdS string) string {
 	return string(session.Out.Contents())
 }
 
+func waitForCmdFail(cmdS string, timeout int, statusCode int) bool {
+	fmt.Fprintf(GinkgoWriter, "Running command: %s\n", cmdS)
+	pingTimeout := time.After(time.Duration(timeout) * time.Minute)
+	tick := time.Tick(time.Second)
```
Comment (golangcibot) [inline tests/e2e/e2e.go]: using time.Tick leaks the underlying ticker, consider using it only in endless functions, tests and the main package, and use time.NewTicker here (from `staticcheck`)

File: tests/e2e/e2e.go [hunk 21]
```diff
@@ -26,16 +26,40 @@ func runCmd(cmdS string) string {
 	return string(session.Out.Contents())
 }
 
+func waitForCmdFail(cmdS string, timeout int, statusCode int) bool {
```
Comment (golangcibot) [inline tests/e2e/e2e.go]: `waitForCmdFail` is unused (from `deadcode`)

File: pkg/component/watch.go [hunk 22]
```diff
@@ -255,7 +256,7 @@ func WatchAndPush(client *occlient.Client, out io.Writer, parameters WatchParame
 						glog.V(4).Infof("error removing watch for %s: %v", event.Name, e)
 					}
 					// append the file to list of deleted files
-					if !alreadyInChangedFiles && !matched {
+					if !alreadyInChangedFiles && !matched && event.Name != "" {
```
Comment (kadel) [inline pkg/component/watch.go]: when it is that `even.Name` can be empty?

File: tests/e2e/watch_test.go [hunk 23]
```diff
@@ -0,0 +1,470 @@
...
+			Expect(getMemoryLimit).To(ContainSubstring("700Mi"))
+			getMemoryRequest := runCmd("oc get dc openjdk-watch-binary-" +
+				appTestName +
+				" -o go-template='{{range .spec.template.spec.containers}}{{.resources.requests.memory}}{{end}}'",
+			)
+			Expect(getMemoryRequest).To(ContainSubstring("400Mi"))
+		})
+		It("watch wildfly component created from binary", func() {
+			runCmd("git clone " + wildflyURI + " " + tmpDir + "/binary/katacoda-odo-backend")
+			runCmd("mvn package -f " + tmpDir + "/binary/katacoda-odo-backend")
```
Comment (kadel) [inline tests/e2e/watch_test.go]: there already is a war file in our tests suite examples (`tests/e2e/examples/binary/java/wildfly/ROOT.war`), would it make sense to use that, to speed up tests and skip building it every time?

Comment (geoand) [reply tests/e2e/watch_test.go]: I think the point of the test here to be as real world as possible - so I propose we keep it.
On the other hand, if this application builds too slowly, we can definitely come up with a different one that will be faster

Comment (anmolbabu) [reply tests/e2e/watch_test.go]: I did it like this for 2 reasons:
1. As @geoand mentioned, the example I wanted it to be as close to real world example as possible
2. If I re-use the downloaded built binary, the next time I build it, I would have to copy it to that location right?

Comment (kadel) [reply tests/e2e/watch_test.go]: ah, now I read the rest of the code, I see that you are using this source to make modification and verify that watch on binary works. It wouldn't make sense to use pre-build binary for this :-)

File: pkg/component/watch.go (hunk 22 above)
Comment (kadel) [reply pkg/component/watch.go]: can mention this in the comment, so in future, we know when Name can be empty

Comment (anmolbabu) [reply pkg/component/watch.go]: Sure

Comment (anmolbabu) [reply pkg/component/watch.go]: Done

**Comment by geoand** [comment]
Travis seems rather slow today...

**Comment by anmolbabu** [comment]
> Travis seems rather slow today...

Yeah :(

**Comment by anmolbabu** [comment]
YAY!!! All green Travis + 4 acks on PR hence merging the PR

**Comment by geoand** [comment]
Awesome job @anmolbabu!
