### PR TITLE
Fix odo describe panic without the context directory

### LINKED ISSUE #5245: odo component describe without context fails
/kind bug

## What versions of software are you using?

**Operating System:**
RHEL 8

**Output of `odo version`:**
odo v2.4.2 (88e89104e)

Server: https://api.sandbox.xyz.openshiftapps.com:6443
Kubernetes: v1.22.0-rc.0+ef241fd

## How did you run odo exactly?
created nodejs example component using IntelliJ plugin.
run odo describe command in commandline in home folder ( no context )
`odo component describe --project stephane-bouchet-dev --app app nodejs`

## Actual behavior
output failed with:
```
 ⚠  URLs couldn't not be retrieved: unable to list routes: the component name, the app name or both are empty
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x88 pc=0x263c7a5]

goroutine 1 [running]:
github.com/openshift/odo/pkg/envinfo.(*EnvInfo).ListStorage(0xc000931d70, 0x0, 0x0, 0x0, 0x0, 0x0)
        /builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/envinfo/storage.go:149 +0xa5
github.com/openshift/odo/pkg/component.(*ComponentFullDescription).loadStoragesFromClientAndLocalConfig(0xc000358b00, 0xc00086e510, 0x3603638, 0xc000931d40, 0x7fff5198e78d, 0x6, 0x7fff5198e789, 0x3, 0xc0003d06c0, 0x0, ...)
        /builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/component/component_full_description.go:73 +0x103
github.com/openshift/odo/pkg/component.NewComponentFullDescriptionFromClientAndLocalConfigProvider(0xc00086e510, 0xc000931d40, 0x7fff5198e78d, 0x6, 0x7fff5198e789, 0x3, 0x7fff5198e76e, 0x14, 0xc00005c0c4, 0x38, ...)
        /builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/component/component_full_description.go:199 +0x905
github.com/openshift/odo/pkg/odo/cli/component.(*DescribeOptions).Run(0xc00000e1b0, 0xc0000d8780, 0x0, 0x0)
        /builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/cli/component/describe.go:68 +0x9b
github.com/openshift/odo/pkg/odo/genericclioptions.GenericRun(0x35c0410, 0xc00000e1b0, 0xc0000d8780, 0xc0000bcff0, 0x1, 0x5)
        /builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/genericclioptions/runnable.go:97 +0x479
github.com/openshift/odo/pkg/odo/cli/component.NewCmdDescribe.func1(0xc0000d8780, 0xc0000bcff0, 0x1, 0x5)
        /builddir/build/BUILD/gocode/src/github.com/openshift/odo/pkg/odo/cli/component/describe.go:96 +0x5e
github.com/spf13/cobra.(*Command).execute(0xc0000d8780, 0xc0000bcfa0, 0x5, 0x5, 0xc0000d8780, 0xc0000bcfa0)
        /builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:856 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc000985680, 0xc00005e110, 0x2ec1ec0, 0x49a2488)
        /builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:897
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /builddir/build/BUILD/gocode/src/github.com/openshift/odo/vendor/github.com/spf13/cobra/command.go:890
main.main()
        /builddir/build/BUILD/gocode/src/github.com/openshift/odo/cmd/odo/odo.go:70 +0x426
```

## Expected behavior
should be possible to have the correct description like
```
Component Name: nodejs
Type: nodejs
Environment Variables:
 · PROJECTS_ROOT=/project
 · PROJECT_SOURCE=/project
 · DEBUG_PORT=5858
Storage:
 · m1 of size 1Gi mounted to /tmp
URLs:
 · http://http-3000-app-stephane-bouchet-dev.apps.sandbox.x8i5.p1.openshiftapps.com exposed via 3000

```

### PR DESCRIPTION
**Pull request by valaparthvi**
**What type of PR is this:**
/kind bug

**What does this PR do / why we need it:**
This PR fixes the panic caused when running odo describe without the context directory.
**Which issue(s) this PR fixes:**

Fixes #5245

**PR acceptance criteria:**

- [ ] Unit test 

- [x] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**
```sh
odo create nodejs mynode --app myapp --project myproject
odo push
<cd outside the context directory>
odo describe mynode --app myapp --project myproject
```

### CODE REVIEW

File: pkg/component/component_full_description.go [hunk 1]
```diff
@@ -78,7 +79,7 @@ func (cfd *ComponentFullDescription) loadStoragesFromClientAndLocalConfig(client
 
 // fillEmptyFields fills any fields that are empty in the ComponentFullDescription
 func (cfd *ComponentFullDescription) fillEmptyFields(componentDesc Component, componentName string, applicationName string, projectName string) {
-	//fix missing names in case it in not in description
+	// fix missing names in case it in not in description
```
Comment (dharmit) [inline pkg/component/component_full_description.go:82]:
```suggestion
	// fix missing names in case it is in not in description
```

File: pkg/component/component_full_description.go [hunk 2]
```diff
@@ -185,10 +194,21 @@ func NewComponentFullDescriptionFromClientAndLocalConfigProvider(client kclient.
 	}
 	cfd.Spec.URL = urls
 
-	err = cfd.loadStoragesFromClientAndLocalConfig(client, configProvider, componentName, applicationName, &componentDesc)
+	// Obtain Storage information
+	var storages storage.StorageList
+	storageClient := storage.NewClient(storage.ClientOptions{
+		Client:              client,
+		LocalConfigProvider: envInfo,
```
Comment (dharmit) [inline pkg/component/component_full_description.go:201]: Something's wrong here. `LocalConfigProvider` was created for `.odo/config.yaml`. For `envInfo`, we should be using `EnvSpecificInfo` or something like that. Has that changed recently?

Comment (valaparthvi) [reply pkg/component/component_full_description.go:201]: LocalConfigProvider is the interface, EnvSpecificInfo implements this interface. We did not change this name thinking that it made sense if we wanted to write a different implementation.

**Comment by valaparthvi** [comment]
@dharmit can you re-lgtm?
