### PR TITLE
Fix issue preventing app from being restarted if `/proc/[pid]/task/[tid]/children` is missing in container (case of Minikube with VirtualBox or KVM drivers)

### LINKED ISSUE #6263: `odo dev`: Application not restarted on Minikube (with VirtualBox or KVM drivers)
/kind bug
/area dev

## TL;DR
We are currently relying on the `/proc/[pid]/task/[tid]/children` file to determine the children processes of the application process running in the dev session container, so as to kill them accordingly.
While this file provides a very fast (and best-effort) way to determine the children of a given parent process, we need to also handle the case where it might be missing (if the host kernel is not configured with `CONFIG_PROC_CHILDREN`).

- [ ] ~As done currently, try to list children from the `/proc/[pid]/task/[tid]/children` file~
- [ ] ~If this file is missing for any reason,~ construct the parent-child process tree by reading all `/proc/[pid]/stat` files; the root is the parent PID we are interested in.
- [ ] In all cases, the tree should be traversed in such a way that children are stopped first before parent processes.

## What versions of software are you using?

**Operating System:**
Fedora 37

**Output of `odo version`:**
`odo v3.2.0` (67272fd81)

## How did you run odo exactly?

- Start a Minikube with VirtualBox or KVM2 driver

```
minikube start --driver=kvm2
```

- Bootstrap a new Node.JS app

```
odo init --name test-nodejs --devfile nodejs --starter nodejs-starter
```

- Start a Dev session

```
odo dev -v 2
```

- In a separate terminal, once the Dev session is up and running, make sure the application is reachable, e.g:

```
$ curl -i http://localhost:40001

HTTP/1.1 200 OK
X-Powered-By: Express
Content-Type: text/html; charset=utf-8
Content-Length: 39
ETag: W/"27-Jw3xdDamjf5jthPp3a/zd95HG0Y"
Date: Wed, 16 Nov 2022 16:19:10 GMT
Connection: keep-alive
Keep-Alive: timeout=5

Hello from Node.js Starter Application!                                                                 
```

- While the Dev session is still running, make changes to any local source files and save, e.g.: `server.js`
```
sed -i "s/Hello from Node.js Starter Application/Hello from updated Node.js Starter Application/" server.js
```

- Try to access the application again once the Dev session is ready, e.g.:
```
$ curl -i http://localhost:40001

HTTP/1.1 200 OK
X-Powered-By: Express
Content-Type: text/html; charset=utf-8
Content-Length: 39
ETag: W/"27-Jw3xdDamjf5jthPp3a/zd95HG0Y"
Date: Wed, 16 Nov 2022 16:33:26 GMT
Connection: keep-alive
Keep-Alive: timeout=5

Hello from Node.js Starter Application!                                                                                                                                                                            
```


## Actual behavior

The application is still returning the old response, meaning that it was not restarted in the container:
```
$ curl -i http://localhost:40001

HTTP/1.1 200 OK
X-Powered-By: Express
Content-Type: text/html; charset=utf-8
Content-Length: 39
ETag: W/"27-Jw3xdDamjf5jthPp3a/zd95HG0Y"
Date: Wed, 16 Nov 2022 16:33:26 GMT
Connection: keep-alive
Keep-Alive: timeout=5

Hello from Node.js Starter Application!%                                                                                                                                                                            
```

## Expected behavior
The application is restarted correctly and reflects the local changes.
```
$ curl -i http://localhost:40001

HTTP/1.1 200 OK
X-Powered-By: Express
Content-Type: text/html; charset=utf-8
Content-Length: 39
ETag: W/"27-Jw3xdDamjf5jthPp3a/zd95HG0Y"
Date: Wed, 16 Nov 2022 16:33:26 GMT
Connection: keep-alive
Keep-Alive: timeout=5

Hello from updated Node.js Starter Application!                                                                                                                                                                            
```

## Any logs, error output, etc?


We can see that `odo dev` will report an error because it was not able to stop the running application process and run the application again. As a consequence, the running application will not reflect the current local changes.

<details>
<summary>odo dev: logs</summary>

```
 ⚠  Devfile command "run" exited with an error status in 20 second(s)                                                                                                                                               
 ⚠  Last 100 lines of log:                                                                                                                                                                                          
npm WARN old lockfile                                                                                                                                                                                               
npm WARN old lockfile The package-lock.json file was created with an old version of npm,                                                                                                                            
npm WARN old lockfile so supplemental metadata must be fetched from the registry.                                                                                                                                   
npm WARN old lockfile                                                                                                                                                                                               
npm WARN old lockfile This is a one-time fix-up, please be patient...                                                                                                                                               
npm WARN old lockfile                                                                                                                                                                                               
                                                                                                                                                                                                                    
added 64 packages, and audited 65 packages in 6s                                                                                                                                                                    
                                                                                                                                                                                                                    
found 0 vulnerabilities                              
npm notice                                           
npm notice New major version of npm available! 8.15.0 -> 9.1.1
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.1.1>
npm notice Run `npm install -g npm@9.1.1` to update!
npm notice                                           

> nodejs-starter@1.0.0 start
> node server.js                                     

App started on PORT 3000                             
(node:62) [DEP0152] DeprecationWarning: Custom PerformanceEntry accessors are deprecated. Please use the detail property.
(Use `node --trace-deprecation ...` to show where the warning was created)
{"level":30,"time":1668615550299,"pid":62,"hostname":"test-nodejs-app-897f87994-7pc9d","req":{"id":1,"method":"GET","url":"/","headers":{"host":"localhost:40001","user-agent":"curl/7.85.0","accept":"*/*"},"remote
Address":"::ffff:127.0.0.1","remotePort":54032},"message":"Hello from Node.js Starter Application!"}
{"level":30,"time":1668615550305,"pid":62,"hostname":"test-nodejs-app-897f87994-7pc9d","req":{"id":1,"method":"GET","url":"/","headers":{"host":"localhost:40001","user-agent":"curl/7.85.0","accept":"*/*"},"remote
Address":"::ffff:127.0.0.1","remotePort":54032},"res":{"statusCode":200,"headers":{"x-powered-by":"Express","content-type":"text/html; charset=utf-8","content-length":"39","etag":"W/\"27-Jw3xdDamjf5jthPp3a/zd95HG
0Y\""}},"responseTime":6,"msg":"request completed"}

up to date, audited 65 packages in 607ms

found 0 vulnerabilities                              

> nodejs-starter@1.0.0 start
> node server.js                                     

node:events:491                                      
      throw er; // Unhandled 'error' event
      ^                                              

Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1432:16)
    at listenInCluster (node:net:1480:12)
    at Server.listen (node:net:1568:7)
    at Object.<anonymous> (/projects/server.js:64:8)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1459:8)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'EADDRINUSE',                                
  errno: -98,                                        
  syscall: 'listen',                                 
  address: '::',                                     
  port: 3000                                         
}                                                    
```

</details>


We can also see in the logs that `odo` could not find the children processes for the run command process:
```
I1116 17:20:57.159155  197263 execute_run.go:57] restart required for command run
I1116 17:20:57.159171  197263 exec.go:39] Executing command [/bin/sh -c cat /opt/odo/.odo_cmd_run.pid || true] for pod: test-nodejs-app-897f87994-7pc9d in container: runtime
44                                                   
I1116 17:20:57.215992  197263 exec.go:39] Executing command [/bin/sh -c cat /proc/44/task/44/children || true] for pod: test-nodejs-app-897f87994-7pc9d in container: runtime
cat: /proc/44/task/44/children: No such file or directory
I1116 17:20:57.278576  197263 exec.go:39] Executing command [/bin/sh -c kill 44 || true] for pod: test-nodejs-app-897f87994-7pc9d in container: runtime
```

As reported in https://github.com/kubernetes/minikube/issues/14351, this is due to the Minikube VM kernel not configured with the `CONFIG_PROC_CHILDREN` config, which governs the presence of the `/proc/[pid]/task/[tid]/children` file:
```
$ minikube ssh
$ zgrep CONFIG_PROC_CHILDREN /proc/config.gz                             
# CONFIG_PROC_CHILDREN is not set
```

### PR DESCRIPTION
**Pull request by rm3l**
**What type of PR is this:**
/kind bug
/area dev

**What does this PR do / why we need it:**

**Which issue(s) this PR fixes:**
As depicted in #6263, this issue might happen if the host kernel is not configured with the `CONFIG_PROC_CHILDREN` config, which is currently the case with some platforms (like Minikube and its VirtualBox or KVM2 drivers).
So this PR changes the way we determine a process children, by reading all `/proc/*/stat` files instead, so we can reliably stop them.

Fixes #6263 

Co-authored-by: @valaparthvi 
Co-authored-by: @feloy 

**PR acceptance criteria:**

- [x] Unit test 

- [ ] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**

### CODE REVIEW

File: pkg/remotecmd/kubeexec.go [hunk 1]
```diff
@@ -318,40 +318,82 @@ func (k *kubeExecProcessHandler) getProcessInfoFromPid(
...
-			children = append(children, childChildren...)
-			children = append(children, c)
+	return k.getProcessChildrenRec(allProcesses, pid)
+}
+
+// getProcessChildrenRec return an ordered list of children PIDs of the given pid,
+// using a recursive post-order traversal algorithm so that the returned list can start with the deepest children processes.
+// The allProcesses map is the parent-children process hierarchy of all processes, where the key is a parent PID,
+// and the value is a list of all its direct children. See the getAllProcesses method.
+func (k *kubeExecProcessHandler) getProcessChildrenRec(allProcesses map[int][]int, pid int) ([]int, error) {
```
Comment (valaparthvi) [inline pkg/remotecmd/kubeexec.go:385]: nit:
I was wondering if this can be defined as an internal function within `k.getProcessChildren`.

Comment (rm3l) [reply pkg/remotecmd/kubeexec.go:385]: Since this is a recursive function, I am not sure if it would be possible to declare it within `k.getProcessChildren`. Well, I need to check, but maybe by separating the variable declaration and assignment.

Comment (rm3l) [reply pkg/remotecmd/kubeexec.go:385]: Okay, indeed, as I suspected, it won't compile if I declare it right in `k.getProcessChildren`:

```go
func (k *kubeExecProcessHandler) getProcessChildren(pid int, podName string, containerName string) ([]int, error) {
	//...
	getProcessChildrenRec := func(allProcesses map[int][]int, pid int) []int {
		// ...
		// This won't compile
		var allChildren []int
		for _, child := range allProcesses[pid] {
			allChildren = append(allChildren, getProcessChildrenRec(allProcesses, child)...)
		}
		// ...
	}
	return getProcessChildrenRec(allProcesses, pid), nil
}
```

But separating declaration and assignment works, but seems a bit redundant to me:

```go
func (k *kubeExecProcessHandler) getProcessChildren(pid int, podName string, containerName string) ([]int, error) {
	//...
	var getProcessChildrenRec func(allProcesses map[int][]int, pid int) []int
	getProcessChildrenRec := func(allProcesses map[int][]int, pid int) []int {
		// ...
		var allChildren []int
		for _, child := range allProcesses[pid] {
			allChildren = append(allChildren, getProcessChildrenRec(allProcesses, child)...)
		}
		// ...
	}
	return getProcessChildrenRec(allProcesses, pid), nil
}
```

I'll keep it as it is, but will change it as a function (as it does not need the receiver).

Comment (rm3l) [reply pkg/remotecmd/kubeexec.go:385]: Actually, it could be acceptable by simplifying the closure parameters. Let's make the change then :-)

Comment (rm3l) [reply pkg/remotecmd/kubeexec.go]: Updated in [`c234978` (#6690)](https://github.com/redhat-developer/odo/pull/6690/commits/c234978fb19f5cee3be1c4c9577432d31e723517)

**Review by valaparthvi — CHANGES_REQUESTED** [review]

File: pkg/remotecmd/kubeexec.go [hunk 2]
```diff
@@ -318,40 +318,76 @@ func (k *kubeExecProcessHandler) getProcessInfoFromPid(
 	return process, nil
 }
 
+// getAllProcesses returns a map of all the processes and their direct children:
+// i) the key is the process PID;
+// ii) and the value is a list of all its direct children.
```
[the remark this answers is not in the document]
Comment (rm3l) [reply pkg/remotecmd/kubeexec.go:323]: At this point, the order is not guaranteed and is not that important, since `getAllProcesses` just reads the data from `/proc/*/stat`.

File: pkg/remotecmd/kubeexec.go [hunk 3]
```diff
@@ -318,40 +318,76 @@ func (k *kubeExecProcessHandler) getProcessInfoFromPid(
...
+// It does so by reading all /proc/<pid>/stat files. More details on https://man7.org/linux/man-pages/man5/proc.5.html.
+func (k *kubeExecProcessHandler) getAllProcesses(podName string, containerName string) (map[int][]int, error) {
+	stdout, stderr, err := k.execClient.ExecuteCommand([]string{ShellExecutable, "-c", "cat /proc/*/stat || true"},
```
[the remark this answers is not in the document]
Comment (rm3l) [reply pkg/remotecmd/kubeexec.go:326]: > Why did you remove err propagation 2>/dev/null? Is it because it will be returned separately via `stderr`?
>
Yes, I removed `2 > /dev/null` to not lose any useful information that might end up in `stderr`;  I thought it could be helpful to display both `stderr` and `stdout` if `err != nil`.

>  Also, I am still confused by what `|| true` does.
>
`cmd1 || cmd2` means, if `cmd1` fails with non-zero exit code, execute `cmd2` and return the exit code of `cmd2`, otherwise return 0 (exit code of `cmd1`). So ` cmd || true` is a way to always return 0 as the exit code (so making `cmd` look as if it succeeded), regardless of the actual exit code of `cmd`.
In our case, if we don't return 0, the `exec` call we are doing will interpret this as an error; this could be the case since not all `/proc/*` folders have a `stat` file. For example:

```shell
$ kubectl exec -it pid-nodejs-app-55cbc55b5-sb42p -- /bin/sh -c 'cat /proc/*/stat > /dev/null'
cat: /proc/net/stat: Is a directory
command terminated with exit code 1

$ echo $?
1
```

File: pkg/remotecmd/kubeexec.go [hunk 4]
```diff
@@ -318,40 +318,76 @@ func (k *kubeExecProcessHandler) getProcessInfoFromPid(
...
+		// See https://unix.stackexchange.com/questions/558239/way-to-unambiguously-parse-proc-pid-stat-given-arbitrary-contents-of-name-fi
+		i := strings.LastIndex(line, ")")
+		if i < 0 {
+			continue
+		}
+
+		// At this point, "i" is the index of the last ")" character, and we have an additional space before the process state character, hence the "i+2".
+		// For example:
+		// 87 (main) S 0 81 81 0 -1 ...
+		var state byte
```
[the remark this answers is not in the document]
Comment (rm3l) [reply pkg/remotecmd/kubeexec.go:352]: Yes, only for scanning `ppid`, as it does not seem possible to ignore the first field, e.g.: https://stackoverflow.com/questions/15825007/how-to-ignore-fields-with-sscanf-is-rejected

File: pkg/remotecmd/kubeexec.go [hunk 5]
```diff
@@ -318,40 +318,76 @@ func (k *kubeExecProcessHandler) getProcessInfoFromPid(
 	return process, nil
 }
 
+// getAllProcesses returns a map of all the processes and their direct children:
+// i) the key is the process PID;
+// ii) and the value is a list of all its direct children.
+// It does so by reading all /proc/<pid>/stat files. More details on https://man7.org/linux/man-pages/man5/proc.5.html.
+func (k *kubeExecProcessHandler) getAllProcesses(podName string, containerName string) (map[int][]int, error) {
```
[the remark this answers is not in the document]
Comment (rm3l) [reply pkg/remotecmd/kubeexec.go:353]: Done in [`f27c67a` (#6690)](https://github.com/redhat-developer/odo/pull/6690/commits/f27c67a5da5668c35ea64354296923ac876374da)

File: pkg/remotecmd/kubeexec.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (valaparthvi) [reply pkg/remotecmd/kubeexec.go:354]: Thank you for explaining that :)

File: pkg/remotecmd/kubeexec.go [hunk 6]
```diff
@@ -319,39 +319,75 @@ func (k *kubeExecProcessHandler) getProcessInfoFromPid(
...
+		// See https://unix.stackexchange.com/questions/558239/way-to-unambiguously-parse-proc-pid-stat-given-arbitrary-contents-of-name-fi
+		i := strings.LastIndex(line, ")")
+		if i < 0 {
+			continue
 		}
+
+		// At this point, "i" is the index of the last ")" character, and we have an additional space before the process state character, hence the "i+2".
+		// For example:
+		// 87 (main) S 0 81 81 0 -1 ...
+		var state byte
```
Comment (valaparthvi) [inline pkg/remotecmd/kubeexec.go:380]: nit:
```suggestion
        // This is required to scan the ppid correctly.
		var state byte
```

**Review by valaparthvi — CHANGES_REQUESTED** [review]

**Comment by rm3l** [comment]
```
  [FAILED] Expected
      <*url.Error | 0xc00044aea0>: {
          Op: "Post",
          URL: "http://127.0.0.1:54165/api/newuser",
          Err: <*errors.errorString | 0xc00008a130>{s: "EOF"},
      }
  to be nil
  In [It] at: C:/Users/Administrator.ANSIBLE-TEST-VS/3579/tests/e2escenarios/e2e_test.go:306 @ 04/03/23 02:14:35.765

  There were additional failures detected.  To view them in detail run ginkgo -vv
------------------------------

Summarizing 1 Failure:
  [FAIL] E2E Test starting with non-empty Directory add Binding [It] should verify developer workflow of using binding as env in innerloop
  C:/Users/Administrator.ANSIBLE-TEST-VS/3579/tests/e2escenarios/e2e_test.go:306

Ran 7 of 7 Specs in 208.074 seconds
FAIL! -- 6 Passed | 1 Failed | 0 Pending | 0 Skipped
```

Flaky E2E test (#6582)

/override windows-integration-test/Windows-test

**Comment by rm3l** [comment]
```
  [odo] I0403 08:34:07.924897    4424 delete.go:94] failed to delete resource "my-nodejs-app-cluster-sample-ocp" (binding.operators.coreos.com.v1alpha1.servicebindings): timeout while waiting for "my-nodejs-app-cluster-sample-ocp" resource to be deleted
  << Timeline

  [FAILED] Timed out after 180.000s.
  Expected process to exit.  It did not.
  In [AfterEach] at: /go/odo_1/tests/helper/helper_dev.go:200 @ 04/03/23 08:34:32.161

Summarizing 1 Failure:
  [FAIL] odo dev command tests when Starting a PostgreSQL service when creating local files and dir and running odo dev - with metadata.name [AfterEach] when deleting local files and dir and waiting for sync should not list deleted dir and file in container
  /go/odo_1/tests/helper/helper_dev.go:200

Ran 431 of 788 Specs in 1284.598 seconds
FAIL! -- 430 Passed | 1 Failed | 0 Pending | 357 Skipped

```

Previous run of the same test passed.

/override OpenShift-Integration-tests/OpenShift-Integration-tests

**Comment by rm3l** [comment]
```
  [odo] I0403 08:34:07.924897    4424 delete.go:94] failed to delete resource "my-nodejs-app-cluster-sample-ocp" (binding.operators.coreos.com.v1alpha1.servicebindings): timeout while waiting for "my-nodejs-app-cluster-sample-ocp" resource to be deleted
...
Summarizing 1 Failure:
  [FAIL] odo dev command tests when Starting a PostgreSQL service [BeforeEach] when creating local files and dir and running odo dev - without metadata.name when deleting local files and dir and waiting for sync should not list deleted dir and file in container
  C:/Users/Administrator.ANSIBLE-TEST-VS/3580/tests/helper/helper_generic.go:58

Ran 424 of 788 Specs in 1064.047 seconds
FAIL! -- 423 Passed | 1 Failed | 0 Pending | 364 Skipped
```

Flaky test - previous run of the same test passed.

/override windows-integration-test/Windows-test
