### PR TITLE
Fixing #1017: Intercepting login message and customising the message message

### LINKED ISSUE #1017: odo login returns incorrect help message when user has no projects
[kind/bug]

## What versions of software are you using?
- Operating System: macos 10.14
- Output of `odo version`:
odo v0.0.15 (29a07286)

Server: [REMOVED]
OpenShift: v3.11.16
Kubernetes: v1.11.0+d4cacc0

## How did you run odo exactly?
odo login -u user1 -p [REMOVED]

## Actual behavior
odo new-project is not a valid command

```
Login successful.

You don't have any projects. You can try to create a new project, by running

    odo new-project <projectname>

```
## Expected behavior

```
Login successful.

You don't have any projects. You can try to create a new project, by running

    odo project create <projectname>
```

### PR DESCRIPTION
**Pull request by mohammedzee1000**
## What is the purpose of this change? What does it change?
See title 
- Adding buffer to replace os.Stdout and intercept output of login
- Customizing a message from odo based on what was intercepted, so if new-project
is present in original message, appropriate addition is done to odo message
- Printing custom message for login success case.

## Was the change discussed in an issue?
fixes #1017 

## How to test changes?

Run `odo login -u user` with or without any active projects

Signed-off-by: Mohammed Zeeshan Ahmed <mohammed.zee1000@gmail.com>

### CODE REVIEW

File: pkg/auth/login.go [hunk 1]
```diff
@@ -48,6 +51,13 @@ func Login(server, username, password, token, caAuth string, skipTLS bool) error
 	if err != nil {
 		return err
 	}
-
+	// Process the messages returned by openshift login code and print our message
+	originalOutMsg := loginOutBuffer.Bytes()
+	var extraOut string
+	// If new-project is present in original message, then ask user to do the same in our message
+	if bytes.Contains(originalOutMsg, []byte("new-project")) {
+		extraOut = " No project? create one\n\todo project create <projectname>"
```
Comment (metacosm) [inline pkg/auth/login.go]: I would put this on a different line (just prepend `\n` to `extraOut` should do the trick)…

Comment (mohammedzee1000) [reply pkg/auth/login.go]: Any case i have found a way to work around by separating `extraOut` completely. Its closer now to Openshift messaging without being the same thing

```
./odo login -u developer
 ✓  Logged in to "https://192.168.42.114:8443" as "developer"

You don't have any projects. You can try to create a new project, by running

	odo project create <projectname>


```

**Comment by mik-dass** [comment]
For me the login message is not working as expected
```
[mrinaldas@localhost odo]$ ./odo login
Authentication required for https://127.0.0.1:8443 (openshift)
Username: developer
Password: 
 ✓  Logged in to "https://127.0.0.1:8443" as ""
```

**Comment by mohammedzee1000** [comment]
@anmolbabu @girishramnani PTAL

File: pkg/auth/login.go [hunk 2]
```diff
@@ -48,6 +52,16 @@ func Login(server, username, password, token, caAuth string, skipTLS bool) error
 	if err != nil {
 		return err
 	}
-
+	// Process the messages returned by openshift login code and print our message
+	originalOutMsg := loginOutBuffer.Bytes()
+	var extraOut string
+	// If new-project is present in original message, then ask user to do the same in our message
+	if bytes.Contains(originalOutMsg, []byte("new-project")) {
+		extraOut = "\nYou don't have any projects. You can try to create a new project, by running\n\n\todo project create <projectname>\n"
```
Comment (mik-dass) [inline pkg/auth/login.go]: Can we change it to `<project-name>` for better formatting?

**Comment by mohammedzee1000** [comment]
> For me the login message is not working as expected
> 
> ```
> [mrinaldas@localhost odo]$ odo login
> Authentication required for https://127.0.0.1:8443 (openshift)
> Username: developer
> Password: 
>  ✓  Logged in to "https://127.0.0.1:8443" as ""
> 
> You don't have any projects. You can try to create a new project, by running
> 
>         odo project create <projectname>
> ```
> I guess it should be `as "developer"`

No, that is definitely weird, thanks for pointing it out, maybe i should source username from different source

**Comment by mohammedzee1000** [comment]
I am beginning to think its better to go for string replacement as a.Username is empty in both cases, and the username is extracted through other means which will mean me needing to alter vendor packages

**Comment by mohammedzee1000** [comment]
Both cases should now be covered, along with previous ones:

```
$ ./odo login -t=<redacted>
 ✓  Logged into "https://192.168.42.114:8443" as "developer" using the token provided.

You don't have any projects. You can try to create a new project, by running

    odo project create <project-name>

$  ./odo login 
Authentication required for https://192.168.42.114:8443 (openshift)
Username: developer
Password: 
 ✓  Login successful.

You don't have any projects. You can try to create a new project, by running

    odo project create <project-name>

$ ./odo login -t=nnN6X1EaHDTmwAuoLjDgVXYrG0psKWWpXsEuMiJL4QI
 ✓  Logged into "https://192.168.42.114:8443" as "developer" using the token provided.

You have one project on this server: "test"

Using project "test".


```

File: pkg/auth/login.go (hunk 2 above)
Comment (mik-dass) [reply pkg/auth/login.go]: :+1:

**Comment by mohammedzee1000** [comment]
None of the code owners have reviewed but I have 2 lgtm @kadel should I merge?

**Comment by mohammedzee1000** [comment]
@amitkrout more expected outputs

```
# Login with one project
## with username
$ ./odo login -u developer
 ✓  Logged into "https://192.168.42.114:8443" as "developer" using existing credentials.

You have one project on this server: "test"

Using project "test".

## with token

$  ./odo login -t=<redacted>
 ✓  Logged into "https://192.168.42.114:8443" as "developer" using the token provided.

You have one project on this server: "test"

Using project "test".

## without any params (interactive)

$ ./odo login 
Authentication required for https://192.168.42.114:8443 (openshift)
Username: developer
Password: 
 ✓  Login successful.

You have one project on this server: "test"

Using project "test".



# Login with multiple projects (2 or more)

## with username

$  ./odo login -u developer
 ✓  Logged into "https://192.168.42.114:8443" as "developer" using existing credentials.

You have access to the following projects and can switch between them with 'odo project <project-name>':

  * test
    test1

Using project "test".

## with token

$ ./odo login -t=<redacted>
 ✓  Logged into "https://192.168.42.114:8443" as "developer" using the token provided.

You have access to the following projects and can switch between them with 'odo project <project-name>':

  * test
    test1

Using project "test".


## without params (interactive)

$  ./odo login
Authentication required for https://192.168.42.114:8443 (openshift)
Username: developer
Password: 
 ✓  Login successful.

You have access to the following projects and can switch between them with 'odo project <project-name>':

  * test
    test1

Using project "test".

```

**Comment by mohammedzee1000** [comment]
> Need your attention - [#1251 (comment)](https://github.com/redhat-developer/odo/pull/1251#issuecomment-458572187)

Is it possible to rerun the codecov?

**Comment by metacosm** [comment]
> Need your attention - [#1251 (comment)](https://github.com/redhat-developer/odo/pull/1251#issuecomment-458572187)

The code coverage change is in a file that's not even modified by this PR! We shouldn't be so focused on code coverage when the metrics seem to be flaky at best…

**Comment by mohammedzee1000** [comment]
> > Need your attention - [#1251 (comment)](https://github.com/redhat-developer/odo/pull/1251#issuecomment-458572187)
> 
> The code coverage change is in a file that's not even modified by this PR! We shouldn't be so focused on code coverage when the metrics seem to be flaky at best…

I kind of wondered same thing. Anycase @anmolbabu @girishramnani ptal

**Comment by amitkrout** [comment]
> The code coverage change is in a file that's not even modified by this PR! We shouldn't be so focused on code coverage when the metrics seem to be flaky at best…

@metacosm you are right, TBH I did not realize that the coverage included the package ```pkg/component/watch.go```. Even i have less knowledge of why in most of pr coverage includes same package ```pkg/component/watch.go``` though its not the part of the pr changes. @mohammedzee1000 Anyway can we write some UTs just to verify what code has been changed for odo login. 

Moreover, this patch incline more towards user facing interaction. @mohammedzee1000 So can you write some integration test. Create a separate separate odo login test file to validate it. Does it make sense ?

**Comment by anmolbabu** [comment]
Verified this PR "All is Well" based on my testing

I'll wait for @amitkrout ack on the PR as I sort of agree that its time to add e2e for the login
But I'll leave it to you guys to take the final call

@amitkrout feel free to merge this PR once you ack it

**Comment by mohammedzee1000** [comment]
@amitkrout Added some tests @girishramnani did the breakup
Also, rebased on master

File: tests/e2e/login_test.go [hunk 3]
```diff
@@ -0,0 +1,91 @@
...
+			})
+		})
+		Context("Run login tests", func() {
+			AfterEach(func() {
+				t := runCmd("oc projects -q")
+				projects := strings.Split(t, "\n")
+				for _, p := range projects {
+					if len(p) > 0 {
+						runCmd(fmt.Sprintf("%s %s", baseOdoProjectDelete, p))
+						time.Sleep(240)
```
[the remark this answers is not in the document]
Comment (mohammedzee1000) [reply tests/e2e/login_test.go]: It's not retry,  it's cleanup

[the remark this answers is not in the document]
Comment (amitkrout) [reply tests/e2e/login_test.go]: Fair enough, That is why i asked if we implement a logic that waits till the namespace is deleted completely.

**Comment by mohammedzee1000** [comment]
> Also add atleast one negative login scenario

Failure cases are difficult to simulate in minishift though as any username or password works.  Will try token

File: tests/e2e/login_test.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (mohammedzee1000) [reply tests/e2e/login_test.go]: > Fair enough, That is why i asked if we implement a logic that waits till the namespace is deleted completely.

I will see if I can minimize delay further though

**Comment by amitkrout** [comment]
> Failure cases are difficult to simulate in minishift though as any username or password works. Will try token

@mohammedzee1000 Try username other than ```developer```

**Comment by mohammedzee1000** [comment]
> > Failure cases are difficult to simulate in minishift though as any username or password works. Will try token
> 
> @mohammedzee1000 Try username other than `developer`

That won't work minishift configures OpenShift with to accept literally anything for username or password

**Comment by amitkrout** [comment]
> That won't work minishift configures OpenShift with to accept literally anything for username or password

Right
```
$ oc login -u developer123 -p anything
Login successful.

You don't have any projects. You can try to create a new project, by running

    oc new-project <projectname>
```
In minishift we have addons ```addon-htpasswd-identity-provider``` which fix the issue but atm this is none of our business. So try with the comment https://github.com/redhat-developer/odo/pull/1251#issuecomment-459374792 you suggested.

**Comment by mohammedzee1000** [comment]
@amitkrout addressed all your concerns PTAL

File: tests/e2e/login_test.go [hunk 4]
```diff
@@ -0,0 +1,97 @@
...
+		})
+
+		Context("Run login tests", func() {
+			AfterEach(func() {
+				t := runCmd("oc projects -q")
+				projects := strings.Split(t, "\n")
+				for _, p := range projects {
+					if len(p) > 0 {
+						runCmd(fmt.Sprintf("%s %s", baseOdoProjectDelete, p))
+						time.Sleep(100)
```
Comment (golangcibot) [inline tests/e2e/login_test.go]: sleeping for 100 nanoseconds is probably a bug. Be explicit if it isn't: time.Sleep(100 * time.Nanosecond) (from `staticcheck`)

Comment (mohammedzee1000) [reply tests/e2e/login_test.go]: Making explicit

File: tests/e2e/login_test.go [hunk 5]
```diff
@@ -0,0 +1,97 @@
...
+		})
+
+		Context("Run login tests", func() {
+			AfterEach(func() {
+				t := runCmd("oc projects -q")
+				projects := strings.Split(t, "\n")
+				for _, p := range projects {
+					if len(p) > 0 {
+						runCmd(fmt.Sprintf("%s %s", baseOdoProjectDelete, p))
+						time.Sleep(100 * time.Millisecond)
```
Comment (anmolbabu) [inline tests/e2e/login_test.go]: Please do not use hard-coded waits may be you can try something similar to https://github.com/redhat-developer/odo/blob/master/tests/e2e/e2e.go#L51

**Comment by mohammedzee1000** [comment]
@amitkrout its the deletion thing in after each which cleans up after each It, ensuring fresh env for next It, increasing delay lets see. Worse case i might need to implement waitfor type of logic that waits until project is no longer listed. The time i gave initially worked fine locally

**Comment by amitkrout** [comment]
> Worse case i might need to implement waitfor type of logic that waits until project is no longer listed

This will be a permanent and efficient solution i guess :)

**Comment by mohammedzee1000** [comment]
> > Worse case i might need to implement waitfor type of logic that waits until project is no longer listed
> 
> This will be a permanent and efficient solution IMO :)

I guess it's already there

**Comment by mohammedzee1000** [comment]
@amitkrout we should be good now?

File: tests/e2e/login_test.go [hunk 6]
```diff
@@ -0,0 +1,98 @@
...
+				Expect(session).To(ContainSubstring("Login successful"))
+				Expect(session).To(ContainSubstring(odoTestProject1))
+				session = runCmd(ocWhoamiCommand)
+				Expect(session).To(ContainSubstring(loginTestUser))
+			})
+
+			It("Should fail login on invalid token with appropriate message", func() {
+				session = runFailCmd(testUserLoginFailCommandWithToken, 1)
+				Expect(session).To(ContainSubstring("The token provided is invalid or expired"))
+				runCmd(testUserLoginCommand)
```
Comment (amitkrout) [inline tests/e2e/login_test.go]: What is the need of ```runCmd``` even after validating the error string. Don't think this is unnecessary for this scenario ?

Comment (mohammedzee1000) [reply tests/e2e/login_test.go]: @amitkrout before entering this user is developer.  It attempts to login with invalid token,  so user is still developer. 

The clean up logic in AfterEach is supposed to run against testdeveloper user,  but will run against developer and may result in unexpected state for any further or future testing

Comment (amitkrout) [reply tests/e2e/login_test.go]: @mohammedzee1000 Thanks for the details
