### PR TITLE
[UX] Fix default value of ImageRegistry in odo preference view output

### LINKED ISSUE #6947: [UX] Fix default value of `ImageRegistry` in `odo preference view` output
/kind bug
/area UX

## What versions of software are you using?

**Operating System:**
Fedora 38

**Output of `odo version`:**
```
$ odo version        
odo v3.12.0 (4479c24df)

Server: https://0.0.0.0:36443
Kubernetes: v1.27.2+k3s1
Podman Client: 4.5.1
```

## How did you run odo exactly?
```shell
# Just to check the default values
GLOBALODOCONFIG=/dev/null odo preference view 
```

## Actual behavior
```
$ GLOBALODOCONFIG=/dev/null odo preference view                        
Preference parameters:
 PARAMETER           VALUE      
 ConsentTelemetry               
 Ephemeral                      
 ImageRegistry        (default) 
 PushTimeout                    
 RegistryCacheTime              
 Timeout                        
 UpdateNotification             

Devfile registries:
 NAME                    URL                          SECURE 
 DefaultDevfileRegistry  https://registry.devfile.io  No        
```

## Expected behavior
The following line from the output is a bit misleading: ` ImageRegistry        (default)      `. We could just display an empty value, just like the other parameters are handled.

```
Preference parameters:
 PARAMETER           VALUE      
 ConsentTelemetry               
 Ephemeral                      
 ImageRegistry       
 PushTimeout                    
 RegistryCacheTime              
 Timeout                        
 UpdateNotification             

Devfile registries:
 NAME                    URL                          SECURE 
 DefaultDevfileRegistry  https://registry.devfile.io  No     
```

### PR DESCRIPTION
**Pull request by valaparthvi**
**What type of PR is this:**
/kind bug

**What does this PR do / why we need it:**

**Which issue(s) this PR fixes:**

Fixes #6947

**PR acceptance criteria:**

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**

### CODE REVIEW

File: pkg/preference/machine_output.go [hunk 1]
```diff
@@ -60,7 +60,7 @@ func toPreferenceItems(prefInfo preferenceInfo) []api.PreferenceItem {
 		{
 			Name:        ImageRegistrySetting,
 			Value:       settings.ImageRegistry,
-			Default:     "",
+			Default:     DefaultDevfileRegistryURL,
```
Comment (rm3l) [inline pkg/preference/machine_output.go:63]: Default value is intentionally the empty string, which disables the "image name as selector" feature (introduced in #6677).

```suggestion
			Default:     "",
```

**Review by rm3l — CHANGES_REQUESTED** [review]

File: pkg/preference/machine_output.go (hunk 1 above)
Comment (valaparthvi) [reply pkg/preference/machine_output.go:63]: My bad, you're right :face_exhaling:

**Review by rm3l — APPROVED** [review]
Thanks, Parthvi!
