### PR TITLE
Fix watch command

### LINKED ISSUE #796: odo watch detects 1 change and subsequently fails to detect more changes
odo watch on a component created from local source, detects 1 change and does not detect subsequent changes

Steps to Reproduce:
1. On Linux, when a file is edited/created using vim editor or even gedit editor and then perform update to any file in watched source
2. Consistently on windows for any file change, subsequent changes are not detected

Reason:
Break  in select as in https://github.com/redhat-developer/odo/blob/master/pkg/component/watch.go#L157, https://github.com/redhat-developer/odo/blob/master/pkg/component/watch.go#L149

### PR DESCRIPTION
**Pull request by anmolbabu**
A break from select case with signal handling causes complete
exit from receiving that particular signal. So avoid break from
select case with signal handling.

fixes #796
Signed-off-by: anmolbabu <anmolbudugutta@gmail.com>

### CODE REVIEW

**Comment by anmolbabu** [comment]
Verified on windows and linux

File: pkg/component/watch.go [hunk 1]
```diff
@@ -134,27 +134,29 @@ func WatchAndPush(client *occlient.Client, componentName string, applicationName
...
+				isIgnoreEvent := false
 				changeLock.Lock()
 				glog.V(4).Infof("filesystem watch event: %s", event)
 
 				if !(event.Op&fsnotify.Remove == fsnotify.Remove || event.Op&fsnotify.Rename == fsnotify.Rename) {
 					stat, err := os.Lstat(event.Name)
 					if err != nil {
 						glog.Errorf("Failed getting details of the changed file %s", event.Name)
-						watchError = errors.Wrap(err, "unable to watch changes")
+						//watchError = errors.Wrap(err, "unable to watch changes")
```
Comment (kadel) [inline pkg/component/watch.go]: why is this error ignored? If there is a reason for it it should be explained in the comment

File: pkg/component/watch.go [hunk 2]
```diff
@@ -134,27 +134,29 @@ func WatchAndPush(client *occlient.Client, componentName string, applicationName
...
 					}
 					// Some of the editors generate temporary buffer files during update to the file and deletes it soon after exiting from the editor
 					// Avoid pushing such buffer files
 					if stat == nil {
-						break
+						glog.V(4).Infof("Ignoring event for temp file %s", event.Name)
+						isIgnoreEvent = true
```
Comment (kadel) [inline pkg/component/watch.go]: How do you know that it is a temporary file?

File: pkg/component/watch.go (hunk 1 above)
Comment (anmolbabu) [reply pkg/component/watch.go]: The error is ignored because, in case of temporary files created by editors like vi or gedit that get deleted almost immediately and we get file not exists error sometimes. But if we feed this to error then the watch breaks, so I feel its better only to log it and leave it WDYT? @kadel

File: pkg/component/watch.go (hunk 2 above)
Comment (anmolbabu) [reply pkg/component/watch.go]: Because, the file was almost quickly(within interval between the event to handling the event) deleted . But I think I'll change it to say ignoring event for the now non-existant file

Comment (anmolbabu) [reply pkg/component/watch.go]: to be more relaistic than making assumptions

File: pkg/component/watch.go [hunk 3]
```diff
@@ -134,27 +134,32 @@ func WatchAndPush(client *occlient.Client, componentName string, applicationName
...
+				isIgnoreEvent := false
 				changeLock.Lock()
 				glog.V(4).Infof("filesystem watch event: %s", event)
 
 				if !(event.Op&fsnotify.Remove == fsnotify.Remove || event.Op&fsnotify.Rename == fsnotify.Rename) {
 					stat, err := os.Lstat(event.Name)
 					if err != nil {
-						glog.Errorf("Failed getting details of the changed file %s", event.Name)
-						watchError = errors.Wrap(err, "unable to watch changes")
+						// Some of the editors generate temporary buffer files during update to the file and deletes it soon after exiting from the editor
```
Comment (surajnarwade) [inline pkg/component/watch.go]: can you please mention the editors name as well for which you faced the problem

Comment (anmolbabu) [reply pkg/component/watch.go]: Ack Done

**Comment by anmolbabu** [comment]
@surajnarwade @kadel Incoporated your comments.. Please revisit the PR

@cdrage @syamgk @mik-dass Please review the PR

File: pkg/component/watch.go [hunk 4]
```diff
@@ -134,27 +134,32 @@ func WatchAndPush(client *occlient.Client, componentName string, applicationName
...
+						// So, its better to log the error rather than feeding it to error handler via `watchError = errors.Wrap(err, "unable to watch changes")`,
+						// which will terminate the watch
+						glog.Errorf("Failed getting details of the changed file %s. So, ignoring te event", event.Name)
```
[the remark this answers is not in the document]
Comment (cdrage) [reply pkg/component/watch.go]: Actually, remove `So,` `Ignoring the change` sounds a bit better

[the remark this answers is not in the document]
Comment (anmolbabu) [reply pkg/component/watch.go]: Ack

**Comment by anmolbabu** [comment]
@kadel @cdrage @surajnarwade All comments incorporated Please revisit the PR

@syamgk @mik-dass Please review

**Comment by cdrage** [comment]
Seems to work :+1: 

After you merge this, can you create another issue indicating that we should have an e2e test created for this?

**Comment by anmolbabu** [comment]
> Seems to work 
> 
> After you merge this, can you create another issue indicating that we should have an e2e test created for this?

There's an issue for the tests already as in https://github.com/redhat-developer/odo/issues/770 and it is targeted for this sprint

**Comment by anmolbabu** [comment]
Thanks @syamgk @cdrage @kadel For reviews

Pushing the PR in as it gets 2 acks :)

File: pkg/component/watch.go (hunk 2 above)
Comment (anmolbabu) [reply pkg/component/watch.go]: Marking the conversation resolved as the comments have been incoporated

**Comment by anmolbabu** [comment]
> Thanks @syamgk @cdrage @kadel For reviews
> 
> Pushing the PR in as it gets 2 acks :)

Aah doesn't seem like I can do it without approval from @kadel and I don't want to misuse my privileges so will patiently wait for @kadel approval :)
