### PR TITLE
Fix panic with interactive odo create when talking to a disconnected cluster

### LINKED ISSUE #5283: Interactive component creation fails if disconnected from the cluster(offline)
/kind bug
## What versions of software are you using?

**Operating System:**
All

**Output of `odo version`:**
odo v2.4.3 (12b79aaa5)

## How did you run odo exactly?
1. `odo create`

## Actual behavior
Fails at retrieving namespace.
```shell
➜  odo create               
Devfile Object Creation
? Which devfile component type do you wish to create  [Use arrows to move, enter
? Which devfile component type do you wish to create  [Use arrows to move, enter
? Which devfile component type do you wish to create  [Use arrows to move, enter
? Which devfile component type do you wish to create  [Use arrows to move, enter
? Which devfile component type do you wish to create go
? What do you wish to name the new devfile component go
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x130 pc=0x292c3a6]

goroutine 1 [running]:
github.com/redhat-developer/odo/pkg/odo/cli/component.InteractiveCreateMethod.FetchDevfileAndCreateComponent(0xc00045e2c0, 0xc0003e5680, 0x47744a0, 0x0, 0x0, 0x2da1840, 0xc00074df50)
        /home/pvala/go/src/github.com/redhat-developer/odo/pkg/odo/cli/component/create_methods.go:65 +0x5a6
github.com/redhat-developer/odo/pkg/odo/cli/component.(*CreateOptions).Complete(0xc00045e2c0, 0xc000385e30, 0x6, 0xc0003e5680, 0x47744a0, 0x0, 0x0, 0x0, 0x0)
        /home/pvala/go/src/github.com/redhat-developer/odo/pkg/odo/cli/component/create.go:194 +0x451
github.com/redhat-developer/odo/pkg/odo/genericclioptions.GenericRun(0x359c2c0, 0xc00045e2c0, 0xc0003e5680, 0x47744a0, 0x0, 0x0)
        /home/pvala/go/src/github.com/redhat-developer/odo/pkg/odo/genericclioptions/runnable.go:85 +0x3c4
github.com/redhat-developer/odo/pkg/odo/cli/component.NewCmdCreate.func1(0xc0003e5680, 0x47744a0, 0x0, 0x0)
        /home/pvala/go/src/github.com/redhat-developer/odo/pkg/odo/cli/component/create.go:356 +0x5e
github.com/spf13/cobra.(*Command).execute(0xc0003e5680, 0x47744a0, 0x0, 0x0, 0xc0003e5680, 0x47744a0)
        /home/pvala/go/src/github.com/redhat-developer/odo/vendor/github.com/spf13/cobra/command.go:856 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc0009b9400, 0xc000058150, 0x2ea1e80, 0x47744a0)
        /home/pvala/go/src/github.com/redhat-developer/odo/vendor/github.com/spf13/cobra/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/pvala/go/src/github.com/redhat-developer/odo/vendor/github.com/spf13/cobra/command.go:897
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /home/pvala/go/src/github.com/redhat-developer/odo/vendor/github.com/spf13/cobra/command.go:890
main.main()
        /home/pvala/go/src/github.com/redhat-developer/odo/cmd/odo/odo.go:70 +0x426
```
## Expected behavior
Should successfully create component.

## Any logs, error output, etc?
Errors indicate that the panic is caused by uninitialized value of KClient, see https://github.com/redhat-developer/odo/blob/main/pkg/odo/cli/component/create_methods.go#L65.

### PR DESCRIPTION
**Pull request by valaparthvi**
**What type of PR is this?**
/kind bug

**What does this PR do / why we need it**:
This PR fixes the panic caused while using odo create interactively with a disconnected cluster
**Which issue(s) this PR fixes**:

Fixes #5283 

**PR acceptance criteria**:

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

- [ ] I have read the [test guidelines](https://github.com/redhat-developer/odo/blob/master/docs/dev/test-architecture.adoc)

**How to test changes / Special notes to the reviewer**:
1. Set the current-context to "".
2. `odo create`
Recreate the above steps on main branch to see the panic.

### CODE REVIEW

**Comment by feloy** [comment]
Kubernetes Tests finished successfully.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5286-kubernetes-tests-142.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5286-kubernetes-tests-142.html)

**Comment by feloy** [comment]
Unit Tests finished successfully.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5286-unit-tests-155.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5286-unit-tests-155.html)

**Comment by feloy** [comment]
OpenShift Tests finished successfully.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5286-openshift-tests-171.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5286-openshift-tests-171.html)

File: pkg/odo/cli/component/create_methods.go [hunk 1]
```diff
@@ -60,9 +61,15 @@ func (icm InteractiveCreateMethod) FetchDevfileAndCreateComponent(co *CreateOpti
 		if err != nil {
 			return err
 		}
-	} else {
-		// if the user is logged in or if we have cluster information, display the default project
+	} else if co.KClient != nil {
+		// Get the current project if no --project is passed, but --now is passed
 		componentNamespace = ui.EnterDevfileComponentProject(co.KClient.GetCurrentProjectName())
+	} else {
+		client, _ := kclient.New()
```
Comment (kadel) [inline pkg/odo/cli/component/create_methods.go:68]: The error is not checked. Isn't there still a chance that odo will end up with `panic` if if `kclient.New()` returns error and `client` is `nil`?

Comment (valaparthvi) [reply pkg/odo/cli/component/create_methods.go:68]: Looking at the `kclient.New()` it does not seem like we would land in this situation since it handles all the errors, but to be on the safe side, I'll switch the change to check if `err == nil`. I hope that works. I do not want to return an error in the case if we're using offline context.

**Comment by feloy** [comment]
Unit Tests finished with errors.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5286-unit-tests-161.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5286-unit-tests-161.html)

**Comment by feloy** [comment]
Kubernetes Tests finished successfully.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5286-kubernetes-tests-148.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5286-kubernetes-tests-148.html)

**Comment by feloy** [comment]
OpenShift Tests finished successfully.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5286-openshift-tests-177.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5286-openshift-tests-177.html)

**Comment by feloy** [comment]
Kubernetes Tests finished successfully.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5286-kubernetes-tests-151.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5286-kubernetes-tests-151.html)

**Comment by feloy** [comment]
Unit Tests finished successfully.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5286-unit-tests-164.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5286-unit-tests-164.html)

**Comment by feloy** [comment]
OpenShift Tests finished successfully.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5286-openshift-tests-180.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5286-openshift-tests-180.html)

File: pkg/odo/cli/component/create_methods.go [hunk 2]
```diff
@@ -60,9 +61,17 @@ func (icm InteractiveCreateMethod) FetchDevfileAndCreateComponent(co *CreateOpti
...
+		// Get the current project if no --project is passed, but --now is passed
 		componentNamespace = ui.EnterDevfileComponentProject(co.KClient.GetCurrentProjectName())
+	} else {
+		var client kclient.ClientInterface
+		client, err = kclient.New()
+		// Continue if an error is encountered
+		if err == nil && client != nil {
+			// Get the current project if no --project is passed and using offline context
+			componentNamespace = ui.EnterDevfileComponentProject(client.GetCurrentProjectName())
+		}
```
Comment (feloy) [inline pkg/odo/cli/component/create_methods.go:74]: If kclient.New() fails, componentNamespace won't be set. Isn't it problematic? Also, don't we want to get it from the envfile?

Comment (valaparthvi) [reply pkg/odo/cli/component/create_methods.go:74]: >Also, don't we want to get it from the envfile?

We will first need to obtain the (desired) namespace from the user, only then can we add it to the envfile. So, at this stage, there is no question of obtaining the namespace from envfile.

**Comment by feloy** [comment]
Kubernetes Tests finished successfully.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5286-kubernetes-tests-196.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5286-kubernetes-tests-196.html)

**Comment by feloy** [comment]
Unit Tests finished successfully.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5286-unit-tests-209.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5286-unit-tests-209.html)

**Comment by feloy** [comment]
OpenShift Tests finished successfully.
View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5286-openshift-tests-226.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5286-openshift-tests-226.html)
