### PR TITLE
Fixed the problem of displaying wrong project as active after project delete

### LINKED ISSUE #887: Project delete setting current to different project than what is shown
Project delete setting current to different than what is shown after deletion.
```
[mrinaldas@localhost odo]$  odo project create myproject
New project created and now using project : myproject
[mrinaldas@localhost odo]$ odo project delete myproject -f
Deleting project myproject...
(this operation may take some time)
Deleted project : myproject
myproject has been set as the active project
```

### PR DESCRIPTION
**Pull request by mik-dass**
fixes #887 

The project delete function in pkg folder now returns the current set project along with the error if any. If no project is left to be set active, "" is returned.

To test :
1. Create a new project
2. Delete the project and check the name of the project which is set as active.

### CODE REVIEW

File: pkg/project/project.go [hunk 1]
```diff
@@ -53,13 +53,14 @@ func Create(client *occlient.Client, projectName string) error {
 	return nil
 }
 
-// Delete deletes the project with name projectName and sets the project with name currentProject as current project and returns errors if any
-func Delete(client *occlient.Client, projectName string) error {
+// Delete deletes the project with name projectName and sets the project with name currentProject as current project
+// and returns the current project or ("" if no current project is set) and errors if any
+func Delete(client *occlient.Client, projectName string) (string, error) {
```
Comment (metacosm) [inline pkg/project/project.go]: This `Delete` function is weird but it's off-topic for this PR. I just find the logic very convoluted. Will look into it at some point.

File: cmd/project.go [hunk 2]
```diff
@@ -146,21 +146,15 @@ var projectDeleteCmd = &cobra.Command{
...
-		currProject := project.GetCurrent(client)
+		fmt.Printf("Deleted project : %v\n", projectName)
 
-		// Check if List returns empty, if so, the currProject is showing old currentProject
-		// In openshift, when the project is deleted, it does not reset the current project in kube config file which is used by odo for current project
-		projects, err := project.List(client)
-		util.CheckError(err, "")
-		if len(projects) != 0 {
-			fmt.Printf("%s has been set as the active project\n", currProject)
+		if currentProject != "" {
```
[the remark this answers is not in the document]
Comment (mik-dass) [reply cmd/project.go]: Yeah I guess, I am more used to this :)

File: pkg/project/project.go (hunk 1 above)
Comment (mik-dass) [reply pkg/project/project.go]: ok :+1:

**Comment by mik-dass** [comment]
@metacosm Fixed :)

**Comment by anmolbabu** [comment]
Works Great...
Merging based on 3 acks above

**Comment by mik-dass** [comment]
@anmolbabu Rebased to the latest master :)

**Comment by anmolbabu** [comment]
@mik-dass Done merged
