### PR TITLE
Fix some flaky tests

### LINKED ISSUE #5568: [Flake] odo dev test `should run odo dev on initial namespace` failing on periodic jobs
/kind flake
/area testing

## What versions of software are you using?
Operating System:
Linux(openshift-ci)

## Actual behavior
There is an increased number of flake of test case `[Fail] odo dev command tests when a component is bootstrapped and pushed when odo dev is executed when deleting previous deployment and switching kubeconfig to another namespace [It] should run odo dev on initial namespace` on periodic jobs.

## Expected behavior
Tests should pass successfully every time

### PR DESCRIPTION
**Pull request by feloy**
**What type of PR is this:**

/kind bug

**What does this PR do / why we need it:**

**Which issue(s) this PR fixes:**

```
odo delete command tests
/go/src/github.com/redhat-developer/odo/tests/integration/devfile/cmd_delete_test.go:13
  when a component is bootstrapped
  /go/src/github.com/redhat-developer/odo/tests/integration/devfile/cmd_delete_test.go:32
    when the component is deployed in DEV mode and dev mode stopped
    /go/src/github.com/redhat-developer/odo/tests/integration/devfile/cmd_delete_test.go:68
      when the component is deleted using its name and namespace from another directory
      /go/src/github.com/redhat-developer/odo/tests/integration/devfile/cmd_delete_test.go:76
        when odo delete command is run again with nothing deployed on the cluster
        /go/src/github.com/redhat-developer/odo/tests/integration/devfile/cmd_delete_test.go:94
          should output that there are no resources to be deleted [It]
          /go/src/github.com/redhat-developer/odo/tests/integration/devfile/cmd_delete_test.go:102
          Expected
              
              <string>: Searching resources to delete, please wait...
              This will delete "mynodejs" from the namespace "cmd-delete-test102goj".
               •  The component contains the following resources that will get deleted:
              	- PodMetrics: mynodejs-app-6d84cf9975-jw4pv
              The component "mynodejs" is successfully deleted from namespace "cmd-delete-test102goj"
              
          to contain substring
              <string>: No resource found for component "mynodejs" in namespace "cmd-delete-test102goj"
```

+ Fixes #5568 

- Bug ps -ef receiving SIGURG: replacing ps with a grep on `proc/*/cmdline` as Docker seems to send SIGURG signals from time to time (https://github.com/flatcar-linux/Flatcar/issues/315)
 
**PR acceptance criteria:**

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**

### CODE REVIEW

**Comment by feloy** [comment]
> Kubernetes Tests on commit finished with errors. View logs: [TXT](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5586-kubernetes-tests-925.txt) [HTML](https://s3.eu-de.cloud-object-storage.appdomain.cloud/odo-tests-openshift-logs/pr-5586-kubernetes-tests-925.html)

@anandrkskd Could you please increase the number of nodes on this cluster?

```
[odo] I0322 18:47:39.453150   11036 events.go:53] Warning Event: Count: 5, Reason: FailedScheduling, Message: 0/3 nodes are available: 3 Insufficient memory.
```

**Comment by feloy** [comment]
/test v4.10-integration-e2e
Infra error

**Comment by feloy** [comment]
/test v4.10-integration-e2e
Infra error

**Comment by rm3l** [comment]
Thanks! I had the exact issue reported in a PR, and was wondering what could cause this,... until I saw this PR :)

/lgtm

File: tests/integration/devfile/cmd_delete_test.go [hunk 1]
```diff
@@ -97,10 +97,12 @@ ComponentSettings:
...
 						Eventually(string(commonVar.CliRunner.Run(getDeployArgs...).Out.Contents()), 60, 3).ShouldNot(ContainSubstring(deploymentName))
 						Eventually(string(commonVar.CliRunner.Run(getSVCArgs...).Out.Contents()), 60, 3).ShouldNot(ContainSubstring(serviceName))
-						stdOut = helper.Cmd("odo", "delete", "component", "--name", cmpName, "--namespace", commonVar.Project, "-f").ShouldPass().Out()
 					})
 					It("should output that there are no resources to be deleted", func() {
-						Expect(stdOut).To(ContainSubstring("No resource found for component %q in namespace %q", cmpName, commonVar.Project))
+						Eventually(func() string {
+							stdOut = helper.Cmd("odo", "delete", "component", "--name", cmpName, "--namespace", commonVar.Project, "-f").ShouldPass().Out()
+							return stdOut
+						}, 60, 3).Should(ContainSubstring("No resource found for component %q in namespace %q", cmpName, commonVar.Project))
```
Comment (valaparthvi) [inline tests/integration/devfile/cmd_delete_test.go:105]: I think instead of this, you can wait for Pods to not be present.

**Review by valaparthvi — CHANGES_REQUESTED** [review]

File: tests/integration/devfile/cmd_delete_test.go (hunk 1 above)
Comment (feloy) [reply tests/integration/devfile/cmd_delete_test.go:105]: No, I would really want to test that the `delete component` command displays that no resources found

Comment (valaparthvi) [reply tests/integration/devfile/cmd_delete_test.go:105]: I meant, you wait for the pods to not be present, and then run the delete command to ensure it gives the right message. Why do you choose otherwise?

**Comment by valaparthvi** [comment]
@feloy Why have IBM cloud tests not triggered yet?

**Comment by valaparthvi** [comment]
/approve
Tests pass locally with multiple runs.

**Comment by feloy** [comment]
IBM Cloud OpenShift & Kubernetes tests pass

```
Exceeded limit MAX_RRSETS_BY_ZONE for zone: ...
```

/override ci/prow/v4.10-integration-e2e
