### PR TITLE
Fix: (odo list) Empty parenthesis for odo version if component is not on the cluster

### LINKED ISSUE #6061: `odo list`: Empty parentheses for odo version if component is not running yet in the cluster
/kind bug

## What versions of software are you using?

**Operating System:**
Fedora 36

**Output of `odo version`:**
odo v3.0.0-beta3 (644d94cde)

## How did you run odo exactly?
```shell
❯ # From a new empty directory, but you can skip the "odo init" step if you already have a component.
❯ # The important point is that the component must not be running yet in the cluster.
❯ odo init --name my-sample-go --devfile go --starter go-starter
❯ odo list
```

## Actual behavior

```
❯ odo list
 ✓  Listing components from namespace 'default' [175ms]
 NAME                              PROJECT TYPE  RUNNING IN  MANAGED            
 * my-sample-go                    go            None        odo ()             
 my-nodesjs-with-k8s-uri-with-var  nodejs        Deploy      odo (v3.0.0-beta3) 
```

## Expected behavior
The `odo ()` cell seems odd to me, at first sight. We could either report the current version of `odo`, or just "odo" if we are unable to determine the version?

## Any logs, error output, etc?

_Originally posted by @rm3l in https://github.com/redhat-developer/odo/pull/6028#discussion_r955968706_

### PR DESCRIPTION
**Pull request by valaparthvi**
**What type of PR is this:**
/kind bug

**What does this PR do / why we need it:**

**Which issue(s) this PR fixes:**

Fixes #6061

**PR acceptance criteria:**

- [ ] Unit test 

- [ ] Integration test 

- [ ] Documentation 

**How to test changes / Special notes to the reviewer:**
1. `mkdir /tmp/101; cd /tmp/101`
2. `odo init --devfile go --name my-go --starter go-starter`
3. `odo list` should not show empty parenthesis for odo version

### CODE REVIEW

**Review by rm3l — CHANGES_REQUESTED** [review]
Added a few comments.

Also, a simple test case that makes sure we don't have `odo ()` displayed for non-deployed components would be helpful, I think.

**Review by rm3l — APPROVED** [review]
/approve

(this is a straightforward change)

**Comment by valaparthvi** [comment]
/hold
Failure of the unit test. It fails through the script, but individual test passes.
```sh
 Based on the files in the current directory odo detected
Language: 
Project type: 
The devfile "a-devfile-name" from the registry "a-registry" will be downloaded.
Based on the files in the current directory odo detected
Language: 
Project type: 
The devfile "" from the registry "" will be downloaded.
--- FAIL: TestInteractiveBackend_PersonalizeName (6.44s)
    --- FAIL: TestInteractiveBackend_PersonalizeName/no_flag (6.44s)
        controller.go:137: missing call(s) to *asker.MockAsker.AskName(is anything) /go/src/github.com/redhat-developer/odo/pkg/init/backend/interactive_test.go:223
        controller.go:137: aborting test due to missing call(s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x26b3592]
goroutine 101 [running]:
testing.tRunner.func1.2({0x30ce1e0, 0x496e500})
	/usr/local/go/src/testing/testing.go:1209 +0x36c
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1212 +0x3b6
panic({0x30ce1e0, 0x496e500})
	/usr/local/go/src/runtime/panic.go:1047 +0x266
github.com/redhat-developer/alizer/go/pkg/apis/recognizer.GetFilePathsFromRoot.func1({0xc0007a3011, 0xf}, {0x0, 0x0}, {0xc00078f070, 0xc000c2e0d0})
	/go/src/github.com/redhat-developer/odo/vendor/github.com/redhat-developer/alizer/go/pkg/apis/recognizer/language_recognizer.go:125 +0x132
path/filepath.walk({0x333268b, 0x4}, {0x378e5e0, 0xc000c2e0d0}, 0xc000bdf070)
	/usr/local/go/src/path/filepath/path.go:438 +0x2a3
path/filepath.Walk({0x333268b, 0x4}, 0xc00078f070)
	/usr/local/go/src/path/filepath/path.go:505 +0x85
github.com/redhat-developer/alizer/go/pkg/apis/recognizer.GetFilePathsFromRoot({0x333268b, 0x4})
	/go/src/github.com/redhat-developer/odo/vendor/github.com/redhat-developer/alizer/go/pkg/apis/recognizer/language_recognizer.go:116 +0xdf
github.com/redhat-developer/alizer/go/pkg/apis/recognizer.Analyze({0x333268b, 0x4})
	/go/src/github.com/redhat-developer/odo/vendor/github.com/redhat-developer/alizer/go/pkg/apis/recognizer/language_recognizer.go:36 +0x158
github.com/redhat-developer/alizer/go/pkg/apis/recognizer.detectComponent({0x333268b, 0x4}, {0xc000bdf918, 0x0, 0x0})
	/go/src/github.com/redhat-developer/odo/vendor/github.com/redhat-developer/alizer/go/pkg/apis/recognizer/component_recognizer.go:237 +0x9a
github.com/redhat-developer/alizer/go/pkg/apis/recognizer.getComponentsWithoutConfigFile({0xc000597250, 0x1, 0x0})
	/go/src/github.com/redhat-developer/odo/vendor/github.com/redhat-developer/alizer/go/pkg/apis/recognizer/component_recognizer.go:66 +0xee
github.com/redhat-developer/alizer/go/pkg/apis/recognizer.DetectComponents({0x333268b, 0x4})
	/go/src/github.
github.com/redhat-developer/odo/pkg/alizer.DetectName({0x333268b, 0x4})
	/go/src/github.
com/redhat-developer/odo/pkg/alizer/alizer.go:92 +0x94
github.com/redhat-developer/odo/pkg/init/backend.(*InteractiveBackend).PersonalizeName(0xc000bdfd38, {{{0x0, 0x0}, {0x333268b, 0x11}, {0x0, 0x0}, {0x0, 0x0, 0x0}, ...}, ...}, ...)
	/go/src/github.com/redhat-developer/odo/pkg/init/backend/interactive.go:126 +0x69
github.com/redhat-developer/odo/pkg/init/backend.TestInteractiveBackend_PersonalizeName.func4(0xc0000ea4e0)
	/go/src/github.com/redhat-developer/odo/pkg/init/backend/interactive_test.go:256 +0x2ca
testing.tRunner(0xc0000ea4e0, 0xc000457cd0)
	/usr/local/go/src/testing/testing.go:1259 +0x230
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1306 +0x727
FAIL	github.com/redhat-developer/odo/pkg/init/backend	6.925s
```

**Comment by rm3l** [comment]
> /hold Failure of the unit test. It fails through the script, but individual test passes.
> 
> ```shell
>  Based on the files in the current directory odo detected
> Language: 
> Project type: 
> The devfile "a-devfile-name" from the registry "a-registry" will be downloaded.
> Based on the files in the current directory odo detected
> Language: 
> Project type: 
> The devfile "" from the registry "" will be downloaded.
> --- FAIL: TestInteractiveBackend_PersonalizeName (6.44s)
>     --- FAIL: TestInteractiveBackend_PersonalizeName/no_flag (6.44s)
>         controller.go:137: missing call(s) to *asker.MockAsker.AskName(is anything) /go/src/github.com/redhat-developer/odo/pkg/init/backend/interactive_test.go:223
>         controller.go:137: aborting test due to missing call(s)
> panic: runtime error: invalid memory address or nil pointer dereference [recovered]
> 	panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x26b3592]
> goroutine 101 [running]:
> testing.tRunner.func1.2({0x30ce1e0, 0x496e500})
> 	/usr/local/go/src/testing/testing.go:1209 +0x36c
> testing.tRunner.func1()
> 	/usr/local/go/src/testing/testing.go:1212 +0x3b6
> panic({0x30ce1e0, 0x496e500})
> 	/usr/local/go/src/runtime/panic.go:1047 +0x266
> github.com/redhat-developer/alizer/go/pkg/apis/recognizer.GetFilePathsFromRoot.func1({0xc0007a3011, 0xf}, {0x0, 0x0}, {0xc00078f070, 0xc000c2e0d0})
> 	/go/src/github.com/redhat-developer/odo/vendor/github.com/redhat-developer/alizer/go/pkg/apis/recognizer/language_recognizer.go:125 +0x132
> path/filepath.walk({0x333268b, 0x4}, {0x378e5e0, 0xc000c2e0d0}, 0xc000bdf070)
> 	/usr/local/go/src/path/filepath/path.go:438 +0x2a3
> path/filepath.Walk({0x333268b, 0x4}, 0xc00078f070)
> 	/usr/local/go/src/path/filepath/path.go:505 +0x85
> github.com/redhat-developer/alizer/go/pkg/apis/recognizer.GetFilePathsFromRoot({0x333268b, 0x4})
> 	/go/src/github.com/redhat-developer/odo/vendor/github.com/redhat-developer/alizer/go/pkg/apis/recognizer/language_recognizer.go:116 +0xdf
> github.com/redhat-developer/alizer/go/pkg/apis/recognizer.Analyze({0x333268b, 0x4})
> 	/go/src/github.com/redhat-developer/odo/vendor/github.com/redhat-developer/alizer/go/pkg/apis/recognizer/language_recognizer.go:36 +0x158
> github.com/redhat-developer/alizer/go/pkg/apis/recognizer.detectComponent({0x333268b, 0x4}, {0xc000bdf918, 0x0, 0x0})
> 	/go/src/github.com/redhat-developer/odo/vendor/github.com/redhat-developer/alizer/go/pkg/apis/recognizer/component_recognizer.go:237 +0x9a
> github.com/redhat-developer/alizer/go/pkg/apis/recognizer.getComponentsWithoutConfigFile({0xc000597250, 0x1, 0x0})
> 	/go/src/github.com/redhat-developer/odo/vendor/github.com/redhat-developer/alizer/go/pkg/apis/recognizer/component_recognizer.go:66 +0xee
> github.com/redhat-developer/alizer/go/pkg/apis/recognizer.DetectComponents({0x333268b, 0x4})
> 	/go/src/github.
> github.com/redhat-developer/odo/pkg/alizer.DetectName({0x333268b, 0x4})
> 	/go/src/github.
> com/redhat-developer/odo/pkg/alizer/alizer.go:92 +0x94
> github.com/redhat-developer/odo/pkg/init/backend.(*InteractiveBackend).PersonalizeName(0xc000bdfd38, {{{0x0, 0x0}, {0x333268b, 0x11}, {0x0, 0x0}, {0x0, 0x0, 0x0}, ...}, ...}, ...)
> 	/go/src/github.com/redhat-developer/odo/pkg/init/backend/interactive.go:126 +0x69
> github.com/redhat-developer/odo/pkg/init/backend.TestInteractiveBackend_PersonalizeName.func4(0xc0000ea4e0)
> 	/go/src/github.com/redhat-developer/odo/pkg/init/backend/interactive_test.go:256 +0x2ca
> testing.tRunner(0xc0000ea4e0, 0xc000457cd0)
> 	/usr/local/go/src/testing/testing.go:1259 +0x230
> created by testing.(*T).Run
> 	/usr/local/go/src/testing/testing.go:1306 +0x727
> FAIL	github.com/redhat-developer/odo/pkg/init/backend	6.925s
> ```

This has been reported in #6092, and should be fixed by #6093 - thanks @feloy !

**Comment by valaparthvi** [comment]
>This has been reported in https://github.com/redhat-developer/odo/issues/6092, and should be fixed by https://github.com/redhat-developer/odo/pull/6093

Oh. It passes on the main branch, so I figured it was something with my PR. I'll cancel the hold then.

/hold cancel
/override Kubernetes Integration Tests/Kubernetes Integration Tests
/override ci/prow/unit-and-validate-test
/override ci/prow/v4.10-integration-e2e

**Comment by valaparthvi** [comment]
/override  Kubernetes Integration Tests/Kubernetes Integration Tests

**Comment by valaparthvi** [comment]
/override "Kubernetes Integration Tests/Kubernetes Integration Tests"

**Comment by dharmit** [comment]
Why do you want to override IBM k8s tests? Aren't they necessary? That's the only k8s tests running in CI, AFAIK.

**Comment by dharmit** [comment]
> It is a flake. The failure wasn't here before and is unrelated to my changes.

Do we have an issue tracking it? If not, can you open one?
Hope the override works.

/override Kubernetes Integration Tests/Kubernetes Integration Tests

**Comment by dharmit** [comment]
/override Kubernetes Integration Tests\/Kubernetes Integration Tests

**Comment by dharmit** [comment]
/override 'Kubernetes Integration Tests/Kubernetes Integration Tests'

File: tests/integration/cmd_dev_test.go [hunk 1]
```diff
@@ -847,9 +847,6 @@ ComponentSettings:
 
 		When("Starting a PostgreSQL service", func() {
 			BeforeEach(func() {
-				if helper.IsKubernetesCluster() {
```
Comment (rm3l) [inline tests/integration/cmd_dev_test.go:850]: I didn't see the changes in `cmd_dev_test`, but maybe that's why the K8s tests are no longer passing for this PR?
I understand why those lines have been removed (ref #5861), and maybe the tests should be passing, but the changes in this file do not seem relevant to the original issue being addressed by this PR.
Maybe this could be done in a separate PR, to better isolate the changes.

Comment (valaparthvi) [reply tests/integration/cmd_dev_test.go:850]: I don't think that is the cause of failure because the tests are passing now,but you're right about it not being relevant, I'll raise a separate PR.

**Review by rm3l — APPROVED** [review]

**Comment by feloy** [comment]
/override ci/prow/unit-and-validate-test
Pass on IBM Cloud

/override windows-integration-test/Windows-test
Windows are not running for the moment, and these changes have no chance to have any influence on Windows

**Comment by valaparthvi** [comment]
/override ci/prow/v4.10-integration-e2e

IBM tests have passed.

**Comment by feloy** [comment]
/override OpenShift-Integration-tests/OpenShift-Integration-tests
We still need to check if a namespace already exists when creating namespaces with random name:
```
unable to create new project: unable to create new project cmd-namespace-test75xrs: project.project.openshift.io "cmd-namespace-test75xrs" already exists
```

**Comment by feloy** [comment]
/override ci/prow/v4.10-integration-e2e
IBM Could Tests pass
